package defpackage;
/* compiled from: PG */
/* renamed from: awwm  reason: default package */
/* loaded from: classes.dex */
public enum awwm {
    CAMERA_CHANGE,
    GOLDFINGER_TAB_SWITCH,
    LOCATION_ACCESS_GRANTED,
    LOCATION_CHANGE,
    LOCATION_FIRST_AVAILABLE,
    LOCATION_FIX_FAILED,
    LOCATION_FIX_TIMEOUT,
    LOGIN_STATUS_EVENT,
    MANUAL_RETRY,
    NEW_LISTENER_REGISTERED,
    SCHEDULED_CACHE_REEVALUATION,
    USER_DATA_UPDATE,
    GOLDFINGER_SHEET_UNCOLLAPSE,
    GOLDFINGER_USER_SCROLL,
    GOLDFINGER_BELOW_FOLD_PREFETCH,
    BATCHED_REQUEST,
    USER_BLOCKING
}
