package defpackage;

import android.view.View;
/* compiled from: PG */
/* renamed from: bdyl  reason: default package */
/* loaded from: classes3.dex */
public final class bdyl {
    private final dzsj<cjqy> A;
    private final dzsj<iqs> B;
    private final dzsj<bego> C;
    private final dzsj<abfa> D;
    private final dzsj<cpv> E;
    private final dzsj<dxio<bhdx>> F;
    private final dzsj<bhat> G;
    private final dzsj<gga> a;
    private final dzsj<btrm> b;
    private final dzsj<behx> c;
    private final dzsj<behy> d;
    private final dzsj<bniv> e;
    private final dzsj<bniy> f;
    private final dzsj<bdwu> g;
    private final dzsj<bmyh> h;
    private final dzsj<bmyo> i;
    private final dzsj<bmlm> j;
    private final dzsj<bfle> k;
    private final dzsj<bfhn> l;
    private final dzsj<bfhu> m;
    private final dzsj<bfhf> n;
    private final dzsj<blyj> o;
    private final dzsj<bniw> p;
    private final dzsj<bfgy> q;
    private final dzsj<bfea> r;
    private final dzsj<jkf> s;
    private final dzsj<dxio<bhjf>> t;
    private final dzsj<dxio<bkgw>> u;
    private final dzsj<bfvw> v;
    private final dzsj<bfaq> w;
    private final dzsj<btvo> x;
    private final dzsj<cqhn> y;
    private final dzsj<cqhu> z;

    public bdyl(dzsj<gga> dzsjVar, dzsj<btrm> dzsjVar2, dzsj<behx> dzsjVar3, dzsj<behy> dzsjVar4, dzsj<bniv> dzsjVar5, dzsj<bniy> dzsjVar6, dzsj<bdwu> dzsjVar7, dzsj<bmyh> dzsjVar8, dzsj<bmyo> dzsjVar9, dzsj<bmlm> dzsjVar10, dzsj<bfle> dzsjVar11, dzsj<bfhn> dzsjVar12, dzsj<bfhu> dzsjVar13, dzsj<bfhf> dzsjVar14, dzsj<blyj> dzsjVar15, dzsj<bniw> dzsjVar16, dzsj<bfgy> dzsjVar17, dzsj<bfea> dzsjVar18, dzsj<jkf> dzsjVar19, dzsj<dxio<bhjf>> dzsjVar20, dzsj<dxio<bkgw>> dzsjVar21, dzsj<bfvw> dzsjVar22, dzsj<bfaq> dzsjVar23, dzsj<btvo> dzsjVar24, dzsj<cqhn> dzsjVar25, dzsj<cqhu> dzsjVar26, dzsj<cjqy> dzsjVar27, dzsj<iqs> dzsjVar28, dzsj<bego> dzsjVar29, dzsj<abfa> dzsjVar30, dzsj<cpv> dzsjVar31, dzsj<dxio<bhdx>> dzsjVar32, dzsj<bhat> dzsjVar33) {
        b(dzsjVar, 1);
        this.a = dzsjVar;
        b(dzsjVar2, 2);
        this.b = dzsjVar2;
        b(dzsjVar3, 3);
        this.c = dzsjVar3;
        b(dzsjVar4, 4);
        this.d = dzsjVar4;
        b(dzsjVar5, 5);
        this.e = dzsjVar5;
        b(dzsjVar6, 6);
        this.f = dzsjVar6;
        b(dzsjVar7, 7);
        this.g = dzsjVar7;
        b(dzsjVar8, 8);
        this.h = dzsjVar8;
        b(dzsjVar9, 9);
        this.i = dzsjVar9;
        b(dzsjVar10, 10);
        this.j = dzsjVar10;
        b(dzsjVar11, 11);
        this.k = dzsjVar11;
        b(dzsjVar12, 12);
        this.l = dzsjVar12;
        b(dzsjVar13, 13);
        this.m = dzsjVar13;
        b(dzsjVar14, 14);
        this.n = dzsjVar14;
        b(dzsjVar15, 15);
        this.o = dzsjVar15;
        b(dzsjVar16, 16);
        this.p = dzsjVar16;
        b(dzsjVar17, 17);
        this.q = dzsjVar17;
        b(dzsjVar18, 18);
        this.r = dzsjVar18;
        b(dzsjVar19, 19);
        this.s = dzsjVar19;
        b(dzsjVar20, 20);
        this.t = dzsjVar20;
        b(dzsjVar21, 21);
        this.u = dzsjVar21;
        b(dzsjVar22, 22);
        this.v = dzsjVar22;
        b(dzsjVar23, 23);
        this.w = dzsjVar23;
        b(dzsjVar24, 24);
        this.x = dzsjVar24;
        b(dzsjVar25, 25);
        this.y = dzsjVar25;
        b(dzsjVar26, 26);
        this.z = dzsjVar26;
        b(dzsjVar27, 27);
        this.A = dzsjVar27;
        b(dzsjVar28, 28);
        this.B = dzsjVar28;
        b(dzsjVar29, 29);
        this.C = dzsjVar29;
        b(dzsjVar30, 30);
        this.D = dzsjVar30;
        b(dzsjVar31, 31);
        this.E = dzsjVar31;
        b(dzsjVar32, 32);
        this.F = dzsjVar32;
        b(dzsjVar33, 33);
        this.G = dzsjVar33;
    }

    private static <T> void b(T t, int i) {
        if (t != null) {
            return;
        }
        StringBuilder sb = new StringBuilder(93);
        sb.append("@AutoFactory method argument is null but is not marked @Nullable. Argument index: ");
        sb.append(i);
        throw new NullPointerException(sb.toString());
    }

    public final bdyk a(begl beglVar, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, @dzsi gn gnVar, View.OnClickListener onClickListener) {
        b(beglVar, 1);
        b(onClickListener, 9);
        gga a = this.a.a();
        b(a, 10);
        btrm a2 = this.b.a();
        b(a2, 11);
        behx a3 = this.c.a();
        b(a3, 12);
        behy a4 = this.d.a();
        b(a4, 13);
        bniv a5 = this.e.a();
        b(a5, 14);
        bniy a6 = this.f.a();
        b(a6, 15);
        bdwu a7 = this.g.a();
        b(a7, 16);
        bmyh a8 = this.h.a();
        b(a8, 17);
        bmyo a9 = this.i.a();
        b(a9, 18);
        bmlm a10 = this.j.a();
        b(a10, 19);
        bfle a11 = this.k.a();
        b(a11, 20);
        bfhn a12 = this.l.a();
        b(a12, 21);
        bfhu a13 = this.m.a();
        b(a13, 22);
        bfhf a14 = this.n.a();
        b(a14, 23);
        blyj a15 = this.o.a();
        b(a15, 24);
        bniw a16 = this.p.a();
        b(a16, 25);
        bfgy a17 = this.q.a();
        b(a17, 26);
        bfea a18 = this.r.a();
        b(a18, 27);
        jkf a19 = this.s.a();
        b(a19, 28);
        dxio a20 = ((dxjh) this.t).a();
        b(a20, 29);
        dxio a21 = ((dxjh) this.u).a();
        b(a21, 30);
        bfvw a22 = this.v.a();
        b(a22, 31);
        bfaq a23 = this.w.a();
        b(a23, 32);
        btvo a24 = this.x.a();
        b(a24, 33);
        cqhn a25 = this.y.a();
        b(a25, 34);
        cqhu a26 = this.z.a();
        b(a26, 35);
        cjqy a27 = this.A.a();
        b(a27, 36);
        iqs a28 = this.B.a();
        b(a28, 37);
        bego a29 = this.C.a();
        b(a29, 38);
        abfa a30 = this.D.a();
        b(a30, 39);
        cpv a31 = this.E.a();
        b(a31, 40);
        dxio a32 = ((dxjh) this.F).a();
        b(a32, 41);
        bhat a33 = this.G.a();
        b(a33, 42);
        return new bdyk(beglVar, z, z2, z3, z4, z5, z6, gnVar, onClickListener, a, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33);
    }
}
