package defpackage;
/* compiled from: PG */
/* renamed from: ckjw  reason: default package */
/* loaded from: classes4.dex */
public final class ckjw {
    public static final ckhf A;
    public static final ckhf B;
    public static final ckhf C;
    public static final ckhf D;
    public static final ckhf E;
    public static final ckhf F;
    public static final ckhf G;
    public static final ckhf H;
    public static final ckhf I;
    public static final ckhf J;
    public static final ckhf K;
    public static final ckhf L;
    public static final ckhf M;
    public static final ckhf N;
    public static final ckhf O;
    public static final ckhf P;
    public static final ckhf Q;
    public static final ckha R;
    public static final ckha S;
    public static final ckha T;
    public static final ckha U;
    public static final ckha V;
    public static final ckha W;
    public static final ckha X;
    public static final ckha Y;
    public static final ckha Z;
    public static final ckha aa;
    public static final ckha ab;
    public static final ckha ac;
    public static final ckha ad;
    public static final ckha ae;
    public static final ckha af;
    public static final ckhf ag;
    public static final ckhf ah;
    public static final ckhf ai;
    public static final ckgu aj;
    public static final ckgu ak;
    public static final ckhf al;
    public static final ckgu am;
    public static final ckgu an;
    public static final ckgu ao;
    public static final ckhf ap;
    public static final ckhf aq;
    public static final ckhf ar;
    public static final ckhf as;
    public static final ckhf at;
    public static final ckhf au;
    public static final ckhf av;
    public static final ckgz aw;
    public static final ckgz ax;
    public static final ckgz ay;
    public static final ckgu h;
    public static final ckgu i;
    public static final ckgu j;
    public static final ckgu k;
    public static final ckgu l;
    public static final ckgz m;
    public static final ckgu n;
    public static final ckgz o;
    public static final ckgz p;
    public static final ckgz q;
    public static final ckha r;
    public static final ckha s;
    public static final ckha t;
    public static final ckgu u;
    public static final ckhf v;
    public static final ckhf w;
    public static final ckhf x;
    public static final ckhf y;
    public static final ckhf z;
    public static final ckgz a = new ckgz("SearchCategoricalCount", ckgy.SEARCH);
    public static final ckgz b = new ckgz("SearchOfflineCategoricalCount", ckgy.SEARCH);
    public static final ckgz c = new ckgz("SearchNavigationalCount", ckgy.SEARCH);
    public static final ckgz d = new ckgz("SearchOfflineNavigationalCount", ckgy.SEARCH);
    public static final ckha e = new ckha("SearchOfflineResultToOnlineResultTime", ckgy.SEARCH, ckde.g);
    public static final ckha f = new ckha("SearchOfflineResultToOnlineResultTime2000ms", ckgy.SEARCH, ckde.g);
    public static final ckha g = new ckha("SearchOfflineResultToOnlineResultTime5000ms", ckgy.SEARCH, ckde.g);

    static {
        new ckgu("SearchDirectionsCount", ckgy.SEARCH);
        h = new ckgu("SearchNoResultCount", ckgy.SEARCH);
        i = new ckgu("SearchOfflineNoResultCount", ckgy.SEARCH);
        j = new ckgu("SearchFromSearchboxCount", ckgy.SEARCH);
        k = new ckgu("SearchFromSuggestionCount", ckgy.SEARCH);
        l = new ckgu("SearchFromVoiceCount", ckgy.SEARCH);
        m = new ckgz("SearchFromListCount", ckgy.SEARCH);
        n = new ckgu("SearchFromMapCount", ckgy.SEARCH);
        o = new ckgz("SearchResponseSequence", ckgy.SEARCH);
        p = new ckgz("SearchEnrouteResponseSequence", ckgy.SEARCH);
        q = new ckgz("SearchOnlineVsOfflineOfflineRegionsOnlineResult", ckgy.SEARCH);
        r = new ckha("SearchOnlineVsOfflineOfflineRegionsOnlineDistanceNavigational", ckgy.SEARCH);
        s = new ckha("SearchOnlineVsOfflineOfflineRegionsOnlineDistanceCategorical", ckgy.SEARCH);
        t = new ckha("SearchOnlineVsOfflineCr5", ckgy.SEARCH, ckde.h);
        u = new ckgu("AplosBarChartDraws", ckgy.SEARCH);
        v = new ckhf("SearchToListTime", ckgy.SEARCH);
        w = new ckhf("SearchOfflineToListTime", ckgy.SEARCH);
        x = new ckhf("SearchSuggestToListTime", ckgy.SEARCH);
        y = new ckhf("SearchOfflineSuggestToListTime", ckgy.SEARCH);
        z = new ckhf("SearchPoiClickToPlaceSheetTime", ckgy.SEARCH);
        A = new ckhf("SearchOfflinePoiClickToPlaceSheetTime", ckgy.SEARCH);
        B = new ckhf("SearchListItemClickToPlaceSheetTime", ckgy.SEARCH);
        C = new ckhf("SearchPanToNewResultsTime", ckgy.SEARCH);
        D = new ckhf("SearchListResultsAppendTime", ckgy.SEARCH);
        E = new ckhf("SearchFilterApplyToListTime", ckgy.SEARCH);
        new ckhf("SearchHotelPlacePageWebViewLoadingTime", ckgy.SEARCH);
        new ckhf("SearchHotelPlacePageWebViewPrefetchLoadingTime", ckgy.SEARCH);
        F = new ckhf("SearchRapWebViewLoadingTime", ckgy.SEARCH);
        G = new ckhf("SearchRapWebViewNativeDialogLoadingTime", ckgy.SEARCH);
        H = new ckhf("SearchRapWebViewNativeDialogPrefetchLoadingTime", ckgy.SEARCH);
        new ckgu("SearchRiddlerChromeplateFirstRunNotDoneCount", ckgy.SEARCH);
        new ckhf("SearchRiddlerChromeplateLoadingTime", ckgy.SEARCH);
        I = new ckhf("SearchRiddlerNativePageLoadingTime", ckgy.SEARCH);
        J = new ckhf("SearchRiddlerNotificationWebViewLoadingTime", ckgy.SEARCH);
        K = new ckhf("SearchRiddlerNotificationNativeLoadingTime", ckgy.SEARCH);
        L = new ckhf("SearchRiddlerWebViewLoadingTime", ckgy.SEARCH);
        M = new ckhf("SearchRiddlerWebViewPrefetchUserLoadingTime", ckgy.SEARCH);
        N = new ckhf("SearchRiddlerNativePageLoadingTimeFromContributionsTab", ckgy.SEARCH);
        O = new ckhf("SearchRiddlerWebViewLoadingTimeFromContributionsTab", ckgy.SEARCH);
        P = new ckhf("SearchRiddlerWebViewPrefetchUserLoadingTimeFromContributionsTab", ckgy.SEARCH);
        Q = new ckhf("SearchRiddlerWebViewLoadingTimeFromLocalGuidesCampaign", ckgy.SEARCH);
        R = new ckha("SuggestLatencyOffline", ckgy.SEARCH);
        S = new ckha("SuggestLatencyOnline", ckgy.SEARCH);
        T = new ckha("SuggestLatencyOfflinePartial", ckgy.SEARCH);
        U = new ckha("SuggestLatencyMixed", ckgy.SEARCH);
        V = new ckha("SuggestLatencyOfflineAfterPartial", ckgy.SEARCH);
        W = new ckha("PlaceDetailsLatencyOffline", ckgy.SEARCH);
        X = new ckha("PlaceDetailsLatencyOnline", ckgy.SEARCH);
        Y = new ckha("SearchLatencyOffline", ckgy.SEARCH);
        Z = new ckha("SearchLatencyOfflineNoOnline", ckgy.SEARCH);
        aa = new ckha("SearchLatencyOnline", ckgy.SEARCH);
        ab = new ckha("SearchEnrouteLatencyOffline", ckgy.SEARCH);
        ac = new ckha("SearchEnrouteLatencyOfflineNoOnline", ckgy.SEARCH);
        ad = new ckha("SearchEnrouteLatencyOnline", ckgy.SEARCH);
        ae = new ckha("SearchLatencyOnlineCancelAfterOfflineReady", ckgy.SEARCH);
        af = new ckha("SearchLatencyOnlineTimeoutAfterOfflineReady", ckgy.SEARCH);
        ag = new ckhf("SearchToPlaceSheetTime", ckgy.SEARCH);
        ah = new ckhf("SearchOfflineToPlaceSheetTime", ckgy.SEARCH);
        ai = new ckhf("SearchSabPageLoadingTimeFromContributionsTab", ckgy.SEARCH);
        aj = new ckgu("SearchSabPageOpensFromContributionsTab", ckgy.SEARCH);
        ak = new ckgu("SearchSabPageLoadsFromContributionsTab", ckgy.SEARCH);
        al = new ckhf("SearchSabPageLoadingTimeFromNotification", ckgy.SEARCH);
        am = new ckgu("SearchSabPageOpensFromNotification", ckgy.SEARCH);
        an = new ckgu("SearchSabPageLoadsFromNotification", ckgy.SEARCH);
        ao = new ckgu("SearchSabPageLoadsFromUnknownEntrypoint", ckgy.SEARCH);
        ap = new ckhf("SearchSuggestToPlaceSheetTime", ckgy.SEARCH);
        aq = new ckhf("SearchOfflineSuggestToPlaceSheetTime", ckgy.SEARCH);
        ar = new ckhf("PlaceSuggestToPlaceSheetTime", ckgy.SEARCH);
        as = new ckhf("PlaceOfflineSuggestToPlaceSheetTime", ckgy.SEARCH);
        new ckgz("SearchInferredHomeWorkShown", ckgy.SEARCH);
        new ckgz("SearchInferredHomeWorkAction", ckgy.SEARCH);
        at = new ckhf("SearchSuggestDisplayTime", ckgy.SEARCH);
        au = new ckhf("SearchZeroSuggestAecRequestTime", ckgy.SEARCH);
        new ckha("SearchZeroSuggestGmailSuggestionsCount", ckgy.SEARCH);
        av = new ckhf("SearchZeroSuggestResultsLoadingTime", ckgy.SEARCH);
        new ckgu("SearchScalableAttributesDelayStartCancelled", ckgy.SEARCH);
        new ckgu("SearchScalableAttributesDelayStartFinished", ckgy.SEARCH);
        aw = new ckgz("SuggestClickAgmm", ckgy.SEARCH);
        ax = new ckgz("SuggestClickEgmm", ckgy.SEARCH);
        ay = new ckgz("SuggestOfflineVsOnline", ckgy.SEARCH);
    }
}
