#!/bin/bash

if [ $# -ne 3 ]
  then
    echo "Usage is ./hbcgen <proj_dir> <entry_filename> <output_name>"
    exit 1
fi

# Switch into project dir
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ORG_DIR=$(pwd)
cd $1
echo "Switching to path:" $(pwd)
mkdir hbcgen_logs

# Ensure the project directory is a nodejs directory
if [ ! -f "./package.json" ]
  then
    echo "Error: Directory found is not an NPM root directory"
    exit 1
fi

echo "Converting react-native project in '$1' to Hermes Byte Code:"

# Install required npm library components
echo -n "  Installing npm library packages..."
npm install --force > ./hbcgen_logs/npm_install.log 2>&1
if [ ! $? ]
  then
    echo; echo "Error: Failed to install npm packages, see logs in '$1/hbcgen_logs/npm_install.log'"
    exit 1
fi
echo " DONE"

# Build code bundle from project
echo -n "  Building code bundle from '$2' to 'index.android.bundle'..."
npx react-native bundle --dev false --platform android --entry-file $2 --bundle-output ./index.android.bundle --minify false > ./hbcgen_logs/bundle_js.log 2>&1
if [ ! $? ]
  then
    echo; echo "Error: Failed to build code bundle, see logs in '$1/hbcgen_logs/bundle_js.log'"
    exit 1
fi
echo " DONE"

# Ensure that hermes engine was installed by npm
if [ ! -e "./node_modules/hermes-engine" ]
  then
    echo "Error: Hermes not detected in project"
    exit 1
fi

# Detect Hermes version in project
PROJ_HBC=$(./node_modules/hermes-engine/linux64-bin/hermesc -version | egrep -oe "HBC bytecode version: [0-9]{1,}" | egrep -oe "[0-9]{1,}")
if [ ! $? ]
  then
    echo "Error: Could not determine hermes bytecode version"
    exit 1
fi
echo "  Detected project hermes version: $PROJ_HBC"

# Compile js bundle into hermes binary
echo -n "  Assembling js bundle into hermes binary to 'index.android.bundle.hbc'..."
./node_modules/hermes-engine/linux64-bin/hermesc -O -emit-binary -out=index.android.bundle.hbc index.android.bundle > ./hbcgen_logs/bundle_to_hbc_binary.log 2>&1
if [ ! $? ]
  then
    echo; echo "Error: Failed to assemble js into hermes binary, see logs in '$1/hbcgen_logs/bundle_to_hbc_binary.log'"
    exit 1
fi
echo " DONE"

# Disassemble hermes binary in readable hermes bytecode
echo -n "  Disassembling hermes binary into hermes readable bytecode to '$3'..."
$SCRIPT_DIR/build/bin$PROJ_HBC/hermesc -dump-bytecode index.android.bundle.hbc -out $3 > ./hbcgen_logs/binary_to_hbc.log 2>&1
if [ ! $? ]
  then
    echo; echo "Error: Failed to disassemble hermes binary into bytecode, see logs in '$1/hbcgen_logs/binary_to_hbc.log'"
    exit 1
fi
echo " DONE"

echo "HBC Generation successful! Enjoy :)"

# Reset path and unset variables
cd $ORG_DIR
unset SCRIPT_DIR
unset ORG_DIR
unset PROJ_HBC
