package defpackage;
/* compiled from: PG */
/* renamed from: autb  reason: default package */
/* loaded from: classes2.dex */
public final class autb {
    public static final int A;
    public static final int B;
    public static final int C;
    public static final int D;
    public static final int E;
    public static final int F;
    public static final int G;
    public static final int H;
    public static final int I;
    public static final int J;
    public static final int K;
    public static final int L;
    public static final int M;
    public static final int N;
    public static final int O;
    public static final int P;
    public static final int Q;
    public static final int R;
    public static final int S;
    public static final int T;
    public static final int U;
    public static final int V;
    public static final int W;
    public static final int X;
    public static final int Y;
    public static final int Z;
    public static final int a;
    public static final int aa;
    public static final int ab;
    public static final int ac;
    public static final int ad;
    public static final int ae;
    public static final int af;
    public static final int ag;
    public static final int ah;
    public static final int ai;
    public static final int aj;
    public static final int ak;
    public static final int al;
    public static final int am;
    public static final int an;
    public static final int ao;
    public static final int ap;
    public static final int aq;
    public static final int b;
    public static final int c;
    public static final int d;
    public static final int e;
    public static final int f;
    public static final int g;
    public static final int h;
    public static final int i;
    public static final int j;
    public static final int k;
    public static final int l;
    public static final int m;
    public static final int n;
    public static final int o;
    public static final int p;
    public static final int q;
    public static final int r;
    public static final int s;
    public static final int t;
    public static final int u;
    public static final int v;
    public static final int w;
    public static final int x;
    public static final int y;
    public static final int z;
    public final dcdn<Integer, auta> ar;

    static {
        auiy.GENERIC_NOTIFICATION.a();
        a = auiy.ANNOUNCEMENTS.a().intValue();
        b = auiy.AREA_TRAFFIC.a().intValue();
        c = auiy.TODO_LIST.a().intValue();
        d = auiy.TODO_PHOTO_GENERIC.a().intValue();
        e = auiy.TODO_REVIEW.a().intValue();
        f = auiy.TRAFFIC_TO_PLACE.a().intValue();
        g = auiy.TIME_TO_LEAVE.a().intValue();
        h = auiy.BUSINESS_OWNER_HOURS.a().intValue();
        i = auiy.EMPLOYEE_HOURS.a().intValue();
        j = auiy.FOOD_REMINDER.a().intValue();
        k = auiy.MADDEN_GROWTH.a().intValue();
        l = auiy.BUSINESS_LISTINGS.a().intValue();
        m = auiy.REENGAGEMENT_CATEGORICAL_SEARCH_REOPENED_BUSINESS.a().intValue();
        n = auiy.REENGAGEMENT_CATEGORICAL_SEARCH_TAKEOUT.a().intValue();
        o = auiy.REENGAGEMENT_PLACESHEET_REOPENED_BUSINESS.a().intValue();
        p = auiy.REENGAGEMENT_PLACESHEET_TAKEOUT.a().intValue();
        q = auiy.SERVICE_RECOMMENDATION.a().intValue();
        r = auiy.SERVICE_RECOMMENDATION_POST_INTERACTION.a().intValue();
        s = auiy.REVIEW_AT_A_PLACE.a().intValue();
        t = auiy.PHOTO_TAKEN.a().intValue();
        u = auiy.PLACE_LIST_JOINED.a().intValue();
        v = auiy.SOCIAL_PLANNING_PLACE_ADDED.a().intValue();
        w = auiy.SOCIAL_PLANNING_PLACE_REACTION.a().intValue();
        x = auiy.SET_ALIAS.a().intValue();
        y = auiy.TIMELINE_RECEIPTS_PARSED.a().intValue();
        z = auiy.TIMELINE_WARM_WELCOME.a().intValue();
        A = auiy.PLACE_QA.a().intValue();
        B = auiy.PLACE_QA_MERCHANT.a().intValue();
        C = auiy.MAPS_BADGES.a().intValue();
        D = auiy.UGC_HOME_STREET.a().intValue();
        E = auiy.UGC_POST_TRIP_QUESTIONS.a().intValue();
        F = auiy.POST_CONTRIBUTION_IMPACT.a().intValue();
        G = auiy.POST_PHOTO_VIEWS.a().intValue();
        H = auiy.POST_PLACE_QA_BEST_ANSWER.a().intValue();
        I = auiy.POST_PLACE_QA_LIKE.a().intValue();
        J = auiy.UGC_PHOTO_BECAME_PLACE_HERO_IMAGE.a().intValue();
        K = auiy.CONTRIBUTION_IMPACT_MILESTONE.a().intValue();
        L = auiy.UGC_FACTUAL_IMPACT_ADD_A_PLACE.a().intValue();
        M = auiy.UGC_FACTUAL_IMPACT_LOCATION_EDIT.a().intValue();
        N = auiy.UGC_FACTUAL_IMPACT_PHONE_NUMBER_EDIT.a().intValue();
        O = auiy.LOCAL_DISCOVERY_AT_A_PLACE.a().intValue();
        P = auiy.LOCAL_DISCOVERY_FOODIE_FAVORITE.a().intValue();
        Q = auiy.LOCAL_DISCOVERY_FOODIE_FAVORITE_ONBOARD_BY_NOTIF.a().intValue();
        R = auiy.LOCAL_DISCOVERY_NEWLY_OPENED_PLACES.a().intValue();
        S = auiy.LOCAL_DISCOVERY_NEWLY_OPENED_PLACES_ONBOARD_BY_NOTIF.a().intValue();
        T = auiy.LOCAL_DISCOVERY_PERSONALIZED_RECOMMENDATION.a().intValue();
        U = auiy.LOCAL_DISCOVERY_PERSONALIZED_RECOMMENDATION_ONBOARD_BY_NOTIF.a().intValue();
        V = auiy.LOCAL_DISCOVERY_PLACES_IN_THE_NEWS.a().intValue();
        W = auiy.LOCAL_DISCOVERY_PUBLIC_LIST.a().intValue();
        X = auiy.LOCAL_DISCOVERY_PUBLIC_LIST_ONBOARD_BY_NOTIF.a().intValue();
        Y = auiy.LOCAL_DISCOVERY_SAVED_PLACE_NEARBY.a().intValue();
        Z = auiy.LOCAL_DISCOVERY_TRAVEL.a().intValue();
        aa = auiy.LOCAL_DISCOVERY_TRAVEL_ONBOARD_BY_NOTIF.a().intValue();
        ab = auiy.LOCAL_DISCOVERY_TRENDING_PLACES.a().intValue();
        ac = auiy.LOCAL_DISCOVERY_TRENDING_PLACES_ONBOARD_BY_NOTIF.a().intValue();
        ad = auiy.LOCAL_DISCOVERY_NEW_POST.a().intValue();
        ae = auiy.LOCAL_DISCOVERY_NEW_POST_ONBOARD_BY_NOTIF.a().intValue();
        af = auiy.LOCAL_DISCOVERY_UPCOMING_EVENTS.a().intValue();
        ag = auiy.LOCAL_DISCOVERY_WELCOME_TO_DESTINATION.a().intValue();
        ah = auiy.LOCAL_GUIDES_PERKS.a().intValue();
        ai = auiy.RIDDLER.a().intValue();
        auiy.IN_APP_SHARE.a();
        aj = auiy.REVIEW_REPLY.a().intValue();
        ak = auiy.NEW_BUSINESS_REVIEW.a().intValue();
        al = auiy.BUSINESS_INSIGHTS.a().intValue();
        am = auiy.BUSINESS_MESSAGING_MERCHANT_UNRESPONSIVE_SUMMARY.a().intValue();
        an = auiy.IN_APP_SURVEY.a().intValue();
        ao = auiy.DESKTOP_CALL.a().intValue();
        ap = auiy.PEOPLE_FOLLOW_NEW_FOLLOWER.a().intValue();
        aq = auiy.PEOPLE_FOLLOW_NEW_REQUEST.a().intValue();
    }

    public autb() {
        dcdg p2 = dcdn.p();
        a(p2, a, dpyv.ANNOUNCEMENTS);
        a(p2, b, dpyv.AREA_TRAFFIC);
        a(p2, c, dpyv.TODO_LIST);
        a(p2, h, dpyv.BUSINESS_OWNER_HOURS);
        a(p2, i, dpyv.EMPLOYEE_HOURS);
        a(p2, d, dpyv.TODO_PHOTO);
        a(p2, j, dpyv.FOOD_REMINDER);
        a(p2, e, dpyv.TODO_REVIEW);
        a(p2, f, dpyv.TRAFFIC_TO_PLACE);
        a(p2, g, dpyv.TIME_TO_LEAVE);
        a(p2, k, dpyv.MADDEN_GROWTH);
        a(p2, l, dpyv.BUSINESS_LISTINGS);
        a(p2, s, dpyv.REVIEW_AT_A_PLACE);
        a(p2, t, dpyv.PHOTO_TAKEN);
        a(p2, y, dpyv.TIMELINE_RECEIPTS_PARSED);
        a(p2, z, dpyv.TIMELINE_WARM_WELCOME);
        a(p2, x, dpyv.SET_ALIAS);
        a(p2, A, dpyv.PLACE_QA);
        a(p2, B, dpyv.PLACE_QA_MERCHANT);
        a(p2, C, dpyv.MAPS_BADGES);
        a(p2, D, dpyv.UGC_HOME_STREET);
        a(p2, E, dpyv.UGC_POST_TRIP_QUESTIONS);
        a(p2, F, dpyv.POST_CONTRIBUTION_IMPACT);
        a(p2, H, dpyv.POST_PLACE_QA_BEST_ANSWER);
        a(p2, I, dpyv.POST_PLACE_QA_LIKE);
        a(p2, J, dpyv.UGC_PHOTO_BECAME_PLACE_HERO_IMAGE);
        a(p2, G, dpyv.POST_PHOTO_VIEWS);
        a(p2, K, dpyv.CONTRIBUTION_IMPACT_MILESTONE);
        a(p2, L, dpyv.UGC_FACTUAL_IMPACT_ADD_A_PLACE);
        a(p2, M, dpyv.UGC_FACTUAL_IMPACT_LOCATION_EDIT);
        a(p2, N, dpyv.UGC_FACTUAL_IMPACT_PHONE_NUMBER_EDIT);
        a(p2, O, dpyv.LOCAL_DISCOVERY_AT_A_PLACE);
        a(p2, P, dpyv.LOCAL_DISCOVERY_FOODIE_FAVORITE);
        a(p2, Q, dpyv.LOCAL_DISCOVERY_FOODIE_FAVORITE_ONBOARD_BY_NOTIF);
        a(p2, R, dpyv.LOCAL_DISCOVERY_NEWLY_OPENED_PLACES);
        a(p2, S, dpyv.LOCAL_DISCOVERY_NEWLY_OPENED_PLACES_ONBOARD_BY_NOTIF);
        a(p2, T, dpyv.LOCAL_DISCOVERY_PERSONALIZED_RECOMMENDATION);
        a(p2, U, dpyv.LOCAL_DISCOVERY_PERSONALIZED_RECOMMENDATION_ONBOARD_BY_NOTIF);
        a(p2, V, dpyv.LOCAL_DISCOVERY_PLACES_IN_THE_NEWS);
        a(p2, W, dpyv.LOCAL_DISCOVERY_PUBLIC_LIST);
        a(p2, X, dpyv.LOCAL_DISCOVERY_PUBLIC_LIST_ONBOARD_BY_NOTIF);
        a(p2, Y, dpyv.LOCAL_DISCOVERY_SAVED_PLACE_NEARBY);
        a(p2, ab, dpyv.LOCAL_DISCOVERY_TRENDING_PLACES);
        a(p2, ac, dpyv.LOCAL_DISCOVERY_TRENDING_PLACES_ONBOARD_BY_NOTIF);
        a(p2, Z, dpyv.LOCAL_DISCOVERY_TRAVEL);
        a(p2, aa, dpyv.LOCAL_DISCOVERY_TRAVEL_ONBOARD_BY_NOTIF);
        a(p2, ag, dpyv.LOCAL_DISCOVERY_WELCOME_TO_DESTINATION);
        a(p2, ao, dpyv.DESKTOP_CALL);
        a(p2, ad, dpyv.LOCAL_DISCOVERY_NEW_POST);
        a(p2, ae, dpyv.LOCAL_DISCOVERY_NEW_POST_ONBOARD_BY_NOTIF);
        a(p2, af, dpyv.LOCAL_DISCOVERY_UPCOMING_EVENTS);
        a(p2, ah, dpyv.LOCAL_GUIDES_PERKS);
        a(p2, q, dpyv.SERVICE_RECOMMENDATION);
        a(p2, r, dpyv.SERVICE_RECOMMENDATION_POST_INTERACTION);
        a(p2, u, dpyv.PLACE_LIST_JOINED);
        a(p2, v, dpyv.SOCIAL_PLANNING_PLACE_ADDED);
        a(p2, w, dpyv.SOCIAL_PLANNING_PLACE_REACTION);
        a(p2, ai, dpyv.RIDDLER);
        a(p2, aj, dpyv.REVIEW_REPLY);
        a(p2, ak, dpyv.NEW_BUSINESS_REVIEW);
        a(p2, al, dpyv.INSIGHTS_BUSINESS_NOTIFICATION);
        a(p2, am, dpyv.BUSINESS_MESSAGING_MERCHANT_UNRESPONSIVE_SUMMARY);
        a(p2, an, dpyv.IN_APP_SURVEY);
        a(p2, ap, dpyv.PEOPLE_FOLLOW_NEW_FOLLOWER);
        a(p2, aq, dpyv.PEOPLE_FOLLOW_NEW_REQUEST);
        a(p2, m, dpyv.REENGAGEMENT_CATEGORICAL_SEARCH_REOPENED_BUSINESS);
        a(p2, n, dpyv.REENGAGEMENT_CATEGORICAL_SEARCH_TAKEOUT);
        a(p2, o, dpyv.REENGAGEMENT_PLACESHEET_REOPENED_BUSINESS);
        a(p2, p, dpyv.REENGAGEMENT_PLACESHEET_TAKEOUT);
        this.ar = p2.b();
    }

    private static void a(dcdg<Integer, auta> dcdgVar, int i2, dpyv dpyvVar) {
        dcdgVar.f(Integer.valueOf(i2), new auta(dpyvVar));
    }
}
