package defpackage;

import android.app.Application;
import java.util.concurrent.Executor;
/* compiled from: PG */
/* renamed from: bwpo  reason: default package */
/* loaded from: classes4.dex */
public final class bwpo {
    private final dzsj<qeg> A;
    private final dzsj<dxio<vrc>> B;
    private final dzsj<dxio<vrp>> C;
    private final dzsj<dxio<vri>> D;
    private final dzsj<dxio<bwqg>> E;
    private final dzsj<cqhn> F;
    private final dzsj<ff> a;
    private final dzsj<eeu> b;
    private final dzsj<Application> c;
    private final dzsj<cqat> d;
    private final dzsj<ckcw> e;
    private final dzsj<btvo> f;
    private final dzsj<btpc> g;
    private final dzsj<bvsl> h;
    private final dzsj<ahjq> i;
    private final dzsj<akfc> j;
    private final dzsj<bypr> k;
    private final dzsj<glj> l;
    private final dzsj<dxio<avij>> m;
    private final dzsj<Executor> n;
    private final dzsj<Executor> o;
    private final dzsj<qbt> p;
    private final dzsj<akfa> q;
    private final dzsj<awre> r;
    private final dzsj<awti> s;
    private final dzsj<bvjj> t;
    private final dzsj<awtj> u;
    private final dzsj<bwpa> v;
    private final dzsj<bwow> w;
    private final dzsj<dxio<bwpz>> x;
    private final dzsj<dxio<vpd>> y;
    private final dzsj<dxio<vrg>> z;

    public bwpo(dzsj<ff> dzsjVar, dzsj<eeu> dzsjVar2, dzsj<Application> dzsjVar3, dzsj<cqat> dzsjVar4, dzsj<ckcw> dzsjVar5, dzsj<btvo> dzsjVar6, dzsj<btpc> dzsjVar7, dzsj<bvsl> dzsjVar8, dzsj<ahjq> dzsjVar9, dzsj<akfc> dzsjVar10, dzsj<bypr> dzsjVar11, dzsj<glj> dzsjVar12, dzsj<dxio<avij>> dzsjVar13, dzsj<Executor> dzsjVar14, dzsj<Executor> dzsjVar15, dzsj<qbt> dzsjVar16, dzsj<akfa> dzsjVar17, dzsj<awre> dzsjVar18, dzsj<awti> dzsjVar19, dzsj<bvjj> dzsjVar20, dzsj<awtj> dzsjVar21, dzsj<bwpa> dzsjVar22, dzsj<bwow> dzsjVar23, dzsj<dxio<bwpz>> dzsjVar24, dzsj<dxio<vpd>> dzsjVar25, dzsj<dxio<vrg>> dzsjVar26, dzsj<qeg> dzsjVar27, dzsj<dxio<vrc>> dzsjVar28, dzsj<dxio<vrp>> dzsjVar29, dzsj<dxio<vri>> dzsjVar30, dzsj<dxio<bwqg>> dzsjVar31, dzsj<cqhn> dzsjVar32) {
        b(dzsjVar, 1);
        this.a = dzsjVar;
        b(dzsjVar2, 2);
        this.b = dzsjVar2;
        b(dzsjVar3, 3);
        this.c = dzsjVar3;
        b(dzsjVar4, 4);
        this.d = dzsjVar4;
        b(dzsjVar5, 5);
        this.e = dzsjVar5;
        b(dzsjVar6, 6);
        this.f = dzsjVar6;
        b(dzsjVar7, 7);
        this.g = dzsjVar7;
        b(dzsjVar8, 8);
        this.h = dzsjVar8;
        b(dzsjVar9, 9);
        this.i = dzsjVar9;
        b(dzsjVar10, 10);
        this.j = dzsjVar10;
        b(dzsjVar11, 11);
        this.k = dzsjVar11;
        b(dzsjVar12, 12);
        this.l = dzsjVar12;
        b(dzsjVar13, 13);
        this.m = dzsjVar13;
        b(dzsjVar14, 14);
        this.n = dzsjVar14;
        b(dzsjVar15, 15);
        this.o = dzsjVar15;
        b(dzsjVar16, 16);
        this.p = dzsjVar16;
        b(dzsjVar17, 17);
        this.q = dzsjVar17;
        b(dzsjVar18, 18);
        this.r = dzsjVar18;
        b(dzsjVar19, 19);
        this.s = dzsjVar19;
        b(dzsjVar20, 20);
        this.t = dzsjVar20;
        b(dzsjVar21, 21);
        this.u = dzsjVar21;
        b(dzsjVar22, 22);
        this.v = dzsjVar22;
        b(dzsjVar23, 23);
        this.w = dzsjVar23;
        b(dzsjVar24, 24);
        this.x = dzsjVar24;
        b(dzsjVar25, 25);
        this.y = dzsjVar25;
        b(dzsjVar26, 26);
        this.z = dzsjVar26;
        b(dzsjVar27, 27);
        this.A = dzsjVar27;
        b(dzsjVar28, 28);
        this.B = dzsjVar28;
        b(dzsjVar29, 29);
        this.C = dzsjVar29;
        b(dzsjVar30, 30);
        this.D = dzsjVar30;
        b(dzsjVar31, 31);
        this.E = dzsjVar31;
        b(dzsjVar32, 32);
        this.F = dzsjVar32;
    }

    private static <T> void b(T t, int i) {
        if (t != null) {
            return;
        }
        StringBuilder sb = new StringBuilder(93);
        sb.append("@AutoFactory method argument is null but is not marked @Nullable. Argument index: ");
        sb.append(i);
        throw new NullPointerException(sb.toString());
    }

    public final bwpn a(bwnj bwnjVar) {
        b(bwnjVar, 1);
        ff ffVar = (ff) ((dxjd) this.a).a;
        b(ffVar, 2);
        eeu a = this.b.a();
        b(a, 3);
        Application a2 = this.c.a();
        b(a2, 4);
        cqat a3 = this.d.a();
        b(a3, 5);
        ckcw a4 = this.e.a();
        b(a4, 6);
        btvo a5 = this.f.a();
        b(a5, 7);
        btpc a6 = this.g.a();
        b(a6, 8);
        bvsl a7 = this.h.a();
        b(a7, 9);
        ahjq a8 = this.i.a();
        b(a8, 10);
        akfc a9 = this.j.a();
        b(a9, 11);
        bypr a10 = this.k.a();
        b(a10, 12);
        dzsj<glj> dzsjVar = this.l;
        dxio a11 = ((dxjh) this.m).a();
        b(a11, 14);
        Executor a12 = this.n.a();
        b(a12, 15);
        Executor a13 = this.o.a();
        b(a13, 16);
        dzsj<qbt> dzsjVar2 = this.p;
        akfa a14 = this.q.a();
        b(a14, 18);
        dzsj<awre> dzsjVar3 = this.r;
        awti a15 = this.s.a();
        b(a15, 20);
        bvjj a16 = this.t.a();
        b(a16, 21);
        awtj a17 = this.u.a();
        b(a17, 22);
        bwpa a18 = this.v.a();
        b(a18, 23);
        bwow a19 = this.w.a();
        b(a19, 24);
        dxio a20 = ((dxjh) this.x).a();
        b(a20, 25);
        dxio a21 = ((dxjh) this.y).a();
        b(a21, 26);
        dxio a22 = ((dxjh) this.z).a();
        b(a22, 27);
        qeg a23 = this.A.a();
        b(a23, 28);
        dxio a24 = ((dxjh) this.B).a();
        b(a24, 29);
        dxio a25 = ((dxjh) this.C).a();
        b(a25, 30);
        dxio a26 = ((dxjh) this.D).a();
        b(a26, 31);
        dxio a27 = ((dxjh) this.E).a();
        b(a27, 32);
        cqhn a28 = this.F.a();
        b(a28, 33);
        return new bwpn(bwnjVar, ffVar, a, a2, a3, a4, a5, a6, a7, a8, a9, a10, dzsjVar, a11, a12, a13, dzsjVar2, a14, dzsjVar3, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28);
    }
}
