package defpackage;
/* compiled from: PG */
/* renamed from: bzmm  reason: default package */
/* loaded from: classes.dex */
public interface bzmm {
    public static final dcep<dqkc> a = dcep.G(dqkc.AREA_EXPLORE_TOOLTIP, dqkc.AREA_TRAFFIC_WARMUP, dqkc.ARWN_GUIDED_NAV_START_AR_PROMO, dqkc.ARWN_ONE_DIRECTION_OTHER_TRAVEL_MODE_PROMO, dqkc.ARWN_ONE_DIRECTION_START_BUTTON_PROMO, dqkc.AR_LIGHTHOUSE_FAB_TOOLTIP, dqkc.AR_LIGHTHOUSE_LOCATION_SHARING_FAB_TOOLTIP, dqkc.BLUE_DOT, dqkc.CARNAVAL_HOME_SCREEN_PROMO, dqkc.COMMUTE_HUB_SHORTCUT_PROMO, dqkc.COMMUTE_TAB_TOOLTIP, dqkc.CONFIDENTIALITY_REMINDER, dqkc.COVID19_LAYER_TOOLTIP, dqkc.DARK_MODE_USER_EDUCATION_TOOLTIP, dqkc.DATEPICKER_DEFAULT_DATES_TOOLTIP, dqkc.DIRECTIONS_NUDGEBAR_SHORTCUT, dqkc.DIRECTIONS_TAXI_DEEP_INTEGRATION, dqkc.DONUT_PLACESHEET_HEADER, dqkc.EDIT_PLACE_NOTE, dqkc.ELECTRIC_VEHICLE_PIVOT_TOOLTIP, dqkc.ELECTRIC_VEHICLE_PROFILE_SEARCH_RESULT_PROMO, dqkc.EXTRA_DETAIL_WALKING_NAV_PROMO, dqkc.FEED_TAB_TOOLTIP, dqkc.GHOST_HAMBURGER_MENU_TOOLTIP, dqkc.HAPPINESS_TRACKING_SURVEY, dqkc.HOME_SCREEN_TAB_BUTTON_TOOLTIP, dqkc.HOME_WORK_SIDE_MENU_ATTENTION, dqkc.INBOX_NOTIFICATION_SYSTEM_BAN_PROMO, dqkc.INFERRED_COMMUTE_DESTINATION_LABELING_PROMO, dqkc.LABEL_FREQUENTLY_SEARCHED_PLACE, dqkc.LOCAL_STREAM_ENTRYPOINT_PEOPLE_FOLLOW_TOOLTIP, dqkc.LOCAL_STREAM_PEOPLE_FOLLOW_RECOMMENDATIONS_CARD_TOOLTIP, dqkc.LOCAL_STREAM_TRAVEL_TOOLTIP, dqkc.LOGIN_OOB, dqkc.MERCHANT_PANEL_PROMO_TOOLTIP, dqkc.MESSAGE_ON_LOCAL_POST_TOOLTIP, dqkc.MORRIS_OOBE, dqkc.NAVIGATION_WELCOME, dqkc.NEW_TRIP_TOOLTIP, dqkc.OFFLINE_FIRST_RESULT_PROMO, dqkc.OFFLINE_ONBOARDING, dqkc.PARKING_LOCATION, dqkc.PEOPLE_FOLLOW_FIRST_FOLLOW_ACKNOWLEDGEMENT_POPUP, dqkc.PERSONAL_SCORE_SEARCH_RESULT_PROMO, dqkc.PERSONAL_SEARCH, dqkc.PICTURE_IN_PICTURE_DISMISSAL, dqkc.PROMOTED_PLACES_USER_EDUCATION_TOOLTIP, dqkc.PULL_UP, dqkc.REPORT_INCIDENT_FAB, dqkc.SAVE_TO_PLACE_LIST, dqkc.SAVE_TRIP_BUTTON_DIRECTIONS_TOOLTIP, dqkc.SAVE_TRIP_BUTTON_SUGGESTION_TOOLTIP, dqkc.SHORTLIST_SEARCH_RESULT_PROMO, dqkc.SIDE_MENU_DELETED_TOOLTIP, dqkc.SPEED_LIMIT_REPORT, dqkc.SUGGEST_LAYER_TOOLTIP, dqkc.TERMS_OF_SERVICE, dqkc.TIMELINE_INTRO, dqkc.TIMELINE_RECEIPT_UPLOAD_PROMO, dqkc.TRAFFIC_TO_PLACE, dqkc.TRANSIT_DEPARTURE_BOARD_FEEDBACK_BANNER, dqkc.TRANSIT_NEW_FEED_PROMO, dqkc.TRANSIT_TAB_POPUP, dqkc.TRANSIT_TAB_PROMOTIONS, dqkc.TRANSIT_TO_GO_LINK, dqkc.TRANSIT_TRIP_ATTRIBUTE_CHIP_TOOLTIP, dqkc.TRANSPORTATION_TAB_COMMUTE_TOOLTIP, dqkc.TRANSPORTATION_TAB_NEW_TRIP_TOOLTIP, dqkc.TWO_WHEELER_TAB_POPUP_AND_SWITCH, dqkc.UGC_TASKS_SEARCH_BUTTON, dqkc.USER_LOCATION_REPORTING, dqkc.WHEELCHAIR_ACCESSIBILITY_SEARCH_PROMO);
    public static final dcep<dqkc> b = dcep.G(dqkc.COMMUTE_HUB_TRANSIT_TRANSFER_SWIPE_PROMO, dqkc.DEPRECATED_VOICE_FREE_NAV, dqkc.DEPRECATED_VOICE_GUIDED_NAV, dqkc.DIRECTIONS_CRITICAL_NOTICE, dqkc.DIRECTIONS_MULTI_WAYPOINT, dqkc.EXPLORE_TAB_CONTENT, dqkc.EXPLORE_TAB_TOOLTIP, dqkc.IMPROVE_LOCATION_OOB, dqkc.INBOX_NOTIFICATION_SWIPE_TOOLTIP, dqkc.INBOX_TAB_TOOLTIP, dqkc.JOURNEY_SHARING_GUIDED_NAV, dqkc.LAYERS, dqkc.LOCATION_SHARING_SIDEMENU, dqkc.LOCATION_SHARING_SIDEMENU_V2, dqkc.NAVIGATION_FAB, dqkc.OFFLINE_MODE, dqkc.OFF_ROUTE_ALERTS_DETAILS, dqkc.ONEDIRECTION_TAXI_TAB, dqkc.PARKING_PLANNER_SEARCH_OVERFLOW, dqkc.SAFETY_LAYER_TOOLTIP, dqkc.SAVED_TRIPS_COMMUTE_MIGRATION_TOOLTIP, dqkc.SMART_DRIVE_SHORTCUT_AFTER_NAV, dqkc.SMART_DRIVE_SHORTCUT_REPEATED_USE, dqkc.SMART_DRIVE_SIDEMENU, dqkc.STAY_SAFER_PROMO, dqkc.TWO_WHEELER_ODELAY_CARD, dqkc.TWO_WHEELER_START_SCREEN_CARD, dqkc.VEHICLE_ROTATION_RESTRICTION_MAP_BUBBLE);

    boolean a(bzml bzmlVar);

    bzmk b(dqkc dqkcVar);

    long c(dqkc dqkcVar);

    int d(dqkc dqkcVar);

    void e(dqkc dqkcVar);

    void f(dqkc dqkcVar);
}
