package defpackage;

import java.util.concurrent.TimeUnit;
/* compiled from: PG */
/* renamed from: ckht  reason: default package */
/* loaded from: classes.dex */
public final class ckht {
    public static final ckgz P;
    public static final ckgu Q;
    public static final ckgz R;
    public static final ckgz S;
    public static final ckgz T;
    public static final ckha U;
    public static final ckgz V;
    public static final ckha W;
    public static final ckgu X;
    public static final ckgz Y;
    public static final ckgz Z;
    public static final ckgz aA;
    public static final ckgz aB;
    public static final ckgz aC;
    public static final ckgz aD;
    public static final ckgz aE;
    public static final ckgz aF;
    public static final ckgz aG;
    public static final ckgz aH;
    public static final ckgz aI;
    public static final ckgz aJ;
    public static final ckgz aK;
    public static final ckgz aL;
    public static final ckha aM;
    public static final ckgz aN;
    public static final ckgz aO;
    public static final ckgu aP;
    public static final ckha aQ;
    public static final ckha aR;
    public static final ckgu aS;
    public static final ckgz aT;
    public static final ckhf aU;
    public static final ckgz aV;
    public static final ckgz aW;
    public static final ckgz aX;
    public static final ckgz aY;
    public static final ckgz aZ;
    public static final ckgz aa;
    public static final ckgz ab;
    public static final ckgz ac;
    public static final ckgz ad;
    public static final ckha ae;
    public static final ckha af;
    public static final ckgu ag;
    public static final ckgz ah;
    public static final ckha ai;
    public static final ckgz aj;
    public static final ckgz ak;
    public static final ckha al;
    public static final ckha am;
    public static final ckgz an;
    public static final ckha ao;
    public static final ckgz ap;
    public static final ckgz aq;
    public static final ckgz ar;
    public static final ckgz as;
    public static final ckgz at;
    public static final ckgu au;
    public static final ckgz av;
    public static final ckgz aw;
    public static final ckgz ax;
    public static final ckgz ay;
    public static final ckgz az;
    public static final ckgz a = new ckgz("NotificationsReceivedCounts", ckgy.NOTIFICATIONS);
    public static final ckgz b = new ckgz("NotificationsDisabledCounts", ckgy.NOTIFICATIONS);
    public static final ckgz c = new ckgz("NotificationsChannelGroupDisabledCounts", ckgy.NOTIFICATIONS);
    public static final ckgz d = new ckgz("NotificationsChannelDisabledCounts", ckgy.NOTIFICATIONS);
    public static final ckgz e = new ckgz("NotificationsTypeDisabledCounts", ckgy.NOTIFICATIONS);
    public static final ckgz f = new ckgz("NotificationsShownCounts", ckgy.NOTIFICATIONS);
    public static final ckgz g = new ckgz("NotificationsImpressionsCounts", ckgy.NOTIFICATIONS);
    public static final ckgz h = new ckgz("NotificationsUpdatedCounts", ckgy.NOTIFICATIONS);
    public static final ckgz i = new ckgz("NotificationsClickedCounts", ckgy.NOTIFICATIONS);
    public static final ckgz j = new ckgz("NotificationsActionClickedCounts", ckgy.NOTIFICATIONS);
    public static final ckgz k = new ckgz("NotificationsRemoteViewsClickedCounts", ckgy.NOTIFICATIONS);
    public static final ckgz l = new ckgz("NotificationsDismissedCounts", ckgy.NOTIFICATIONS);
    public static final ckgz m = new ckgz("NotificationsOptOutClickedCounts", ckgy.NOTIFICATIONS);
    public static final ckgz n = new ckgz("NotificationsGunsGenericCounts", ckgy.NOTIFICATIONS);
    public static final ckgz o = new ckgz("NotificationsDroppedCounts", ckgy.NOTIFICATIONS);
    public static final ckgz p = new ckgz("NotificationsDroppedNotLoggedInCounts", ckgy.NOTIFICATIONS);
    public static final ckgz q = new ckgz("NotificationsDroppedNotActiveCounts", ckgy.NOTIFICATIONS);
    public static final ckgz r = new ckgz("NotificationsDroppedExpiredOnReceipt", ckgy.NOTIFICATIONS);
    public static final ckgz s = new ckgz("NotificationsDroppedNoLocationPermission", ckgy.NOTIFICATIONS);
    public static final ckgz t = new ckgz("NotificationsDroppedBackoff", ckgy.NOTIFICATIONS);
    public static final ckgz u = new ckgz("NotificationsDroppedFeatureIdBackoff", ckgy.NOTIFICATIONS);
    public static final ckgz v = new ckgz("NotificationsDroppedCounterfactual", ckgy.NOTIFICATIONS);
    public static final ckgz w = new ckgz("NotificationsDroppedForegroundOnlyLocationPermission", ckgy.NOTIFICATIONS);
    public static final ckgz x = new ckgz("NotificationsDroppedGenericType", ckgy.NOTIFICATIONS);
    public static final ckgz y = new ckgz("NotificationsDroppedSuppressorNotification", ckgy.NOTIFICATIONS);
    public static final ckgz z = new ckgz("NotificationsDroppedTargetAccountDifferentFromCurrent", ckgy.NOTIFICATIONS);
    public static final ckgz A = new ckgz("NotificationsDroppedTargetAccountNotOnDevice", ckgy.NOTIFICATIONS);
    public static final ckgz B = new ckgz("NotificationsDroppedTargetAccountNotSet", ckgy.NOTIFICATIONS);
    public static final ckgz C = new ckgz("NotificationsDroppedTargetDeviceIsTablet", ckgy.NOTIFICATIONS);
    public static final ckgz D = new ckgz("NotificationsOptedOutCounts", ckgy.NOTIFICATIONS);
    public static final ckgu E = new ckgu("NotificationsNotSupportedCount", ckgy.NOTIFICATIONS);
    public static final ckgz F = new ckgz("NotificationsAttemptedImageAuthentication", ckgy.NOTIFICATIONS);
    public static final ckgz G = new ckgz("NotificationsLoadedLargeIcon", ckgy.NOTIFICATIONS);
    public static final ckgz H = new ckgz("NotificationsLoadedAuthenticatedLargeIcon", ckgy.NOTIFICATIONS);
    public static final ckgz I = new ckgz("NotificationsFailedToLoadLargeIcon", ckgy.NOTIFICATIONS);
    public static final ckgz J = new ckgz("NotificationsFailedToLoadAuthenticatedLargeIcon", ckgy.NOTIFICATIONS);
    public static final ckgz K = new ckgz("NotificationsLoadedBigPicture", ckgy.NOTIFICATIONS);
    public static final ckgz L = new ckgz("NotificationsLoadedAuthenticatedBigPicture", ckgy.NOTIFICATIONS);
    public static final ckgz M = new ckgz("NotificationsFailedToLoadBigPicture", ckgy.NOTIFICATIONS);
    public static final ckgz N = new ckgz("NotificationsFailedToLoadAuthenticatedBigPicture", ckgy.NOTIFICATIONS);
    public static final ckgz O = new ckgz("NotificationsFailedToGetImageAccessToken", ckgy.NOTIFICATIONS);

    static {
        new ckgz("NotificationsScheduledRpcScheduleTime", ckgy.NOTIFICATIONS);
        new ckgz("NotificationsScheduledRpcSendTime", ckgy.NOTIFICATIONS);
        new ckgz("NotificationsBackupDatabaseWriteScheduleTime", ckgy.NOTIFICATIONS);
        new ckgz("NotificationsBackupDatabaseWriteRunTime", ckgy.NOTIFICATIONS);
        P = new ckgz("NotificationsStateLoadResult", ckgy.NOTIFICATIONS);
        Q = new ckgu("LocaleUpdatedCount", ckgy.NOTIFICATIONS);
        R = new ckgz("PulseNotificationReceivedCounts", ckgy.NOTIFICATIONS);
        S = new ckgz("PulseNotificationClickedCounts", ckgy.NOTIFICATIONS);
        T = new ckgz("PulseNotificationDismissedCounts", ckgy.NOTIFICATIONS);
        U = new ckha("AreaTrafficNotificationTimeBetweenSubscriptionRequests", ckgy.NOTIFICATIONS);
        new ckgz("AreaTrafficNotificationGcmTaskSubscriptionResult", ckgy.NOTIFICATIONS);
        V = new ckgz("AreaTrafficNotificationShouldNotRenderReason", ckgy.NOTIFICATIONS);
        W = new ckha("AreaTrafficNotificationStalenessCheckerLocationAgeMinutes", ckgy.NOTIFICATIONS, new cnkg(1, -1, 30));
        X = new ckgu("AreaTrafficNotificationGeofenceTriggeredCount", ckgy.NOTIFICATIONS);
        Y = new ckgz("AreaTrafficNotificationAddGeofenceResult", ckgy.NOTIFICATIONS);
        Z = new ckgz("AreaTrafficNotificationPeriodicSubscriptionResult", ckgy.NOTIFICATIONS);
        aa = new ckgz("AreaTrafficNotificationToggledOnSubscriptionResult", ckgy.NOTIFICATIONS);
        ab = new ckgz("AreaTrafficNotificationStaleNotificationSubscriptionResult", ckgy.NOTIFICATIONS);
        ac = new ckgz("AreaTrafficNotificationExitGeofenceSubscriptionResult", ckgy.NOTIFICATIONS);
        ad = new ckgz("TrafficToPlaceNotificationDestinationGeofenceConfigurationResult", ckgy.NOTIFICATIONS);
        ae = new ckha("TrafficToPlaceNotificationFirstNotificationDelayMs", ckgy.NOTIFICATIONS, new cnkg((int) TimeUnit.SECONDS.toMillis(30L), 0, (int) TimeUnit.HOURS.toMillis(4L)));
        af = new ckha("TrafficToPlaceNotificationExecutionTimeDelayMs", ckgy.NOTIFICATIONS, new cnkg(30000, 0, 43200000));
        ag = new ckgu("TrafficToPlaceNotificationForceSyncPersonalPlacesCount", ckgy.NOTIFICATIONS);
        ah = new ckgz("TrafficToPlaceNotificationGeofenceTriggered", ckgy.NOTIFICATIONS);
        ai = new ckha("TrafficToPlaceNotificationServiceRuntimeMs", ckgy.NOTIFICATIONS, ckde.a);
        aj = new ckgz("TrafficToPlaceNotificationSessionRegistrationResult", ckgy.NOTIFICATIONS);
        ak = new ckgz("TrafficToPlaceNotificationGeofencingEvent", ckgy.NOTIFICATIONS);
        al = new ckha("TrafficToPlaceNotificationEtaSlowerMins", ckgy.NOTIFICATIONS);
        am = new ckha("TrafficToPlaceNotificationEtaFasterMins", ckgy.NOTIFICATIONS);
        an = new ckgz("TransitStationNotificationEarlyExitKind", ckgy.NOTIFICATIONS);
        ao = new ckha("TransitStationNotificationElsaConfidence", ckgy.NOTIFICATIONS);
        ap = new ckgz("TransitStationNotificationNearbyAlertErrorCode", ckgy.NOTIFICATIONS);
        aq = new ckgz("TransitStationNotificationPlaceUpdateErrorCode", ckgy.NOTIFICATIONS);
        ar = new ckgz("TransitStationNotificationLocationHistoryCheckResult", ckgy.NOTIFICATIONS);
        as = new ckgz("TransitStationNotificationReregistration", ckgy.NOTIFICATIONS);
        at = new ckgz("TransitToPlaceNotificationDestinationGeofenceConfigurationResult", ckgy.NOTIFICATIONS);
        au = new ckgu("TransitToPlaceNotificationForceSyncPersonalPlacesCount", ckgy.NOTIFICATIONS);
        av = new ckgz("TransitToPlaceNotificationGeofenceTriggered", ckgy.NOTIFICATIONS);
        aw = new ckgz("TransitToPlaceNotificationGeofencingEvent", ckgy.NOTIFICATIONS);
        ax = new ckgz("CommuteNotificationMinimapNotSupportedReason", ckgy.NOTIFICATIONS);
        ay = new ckgz("CommuteNotificationMinimapBasemapCacheDiskLoadOutcome", ckgy.NOTIFICATIONS);
        az = new ckgz("CommuteNotificationMinimapRouteOverlayCacheDiskLoadOutcome", ckgy.NOTIFICATIONS);
        aA = new ckgz("CommuteNotificationMinimapBasemapCacheDiskSaveOutcome", ckgy.NOTIFICATIONS);
        aB = new ckgz("CommuteNotificationMinimapRouteOverlayCacheDiskSaveOutcome", ckgy.NOTIFICATIONS);
        aC = new ckgz("CommuteNotificationMinimapBasemapRpcFetchOutcome", ckgy.NOTIFICATIONS);
        aD = new ckgz("CommuteNotificationMinimapImageUsed", ckgy.NOTIFICATIONS);
        aE = new ckgz("CommuteNotificationMinimapFallbackIconFetchOutcome", ckgy.NOTIFICATIONS);
        aF = new ckgz("CommuteNotificationMinimapTrafficToPlaceNotificationReceivedOutcome", ckgy.NOTIFICATIONS);
        aG = new ckgz("CommuteNotificationMinimapRouteOverlayTopPaddingPixels", ckgy.NOTIFICATIONS);
        aH = new ckgz("CommuteNotificationMinimapRouteOverlayBottomPaddingPixels", ckgy.NOTIFICATIONS);
        aI = new ckgz("CommuteNotificationMinimapRouteOverlayLeftPaddingPixels", ckgy.NOTIFICATIONS);
        aJ = new ckgz("CommuteNotificationMinimapRouteOverlayRightPaddingPixels", ckgy.NOTIFICATIONS);
        aK = new ckgz("CommuteProberNotificationResult", ckgy.NOTIFICATIONS);
        new ckgz("CommuteSetupPromoNotificationStep", ckgy.NOTIFICATIONS);
        aL = new ckgz("SmartspaceNotificationDelivery", ckgy.NOTIFICATIONS);
        aM = new ckha("SmartspaceNotificationSendLatencyMs", ckgy.NOTIFICATIONS, new cnkg((int) TimeUnit.SECONDS.toMillis(30L), 0, (int) TimeUnit.HOURS.toMillis(4L)));
        aN = new ckgz("SmartspaceNotificationProcessingOutcomeDrivingCommute", ckgy.NOTIFICATIONS);
        aO = new ckgz("SmartspaceNotificationProcessingOutcomeTransitCommute", ckgy.NOTIFICATIONS);
        aP = new ckgu("NotificationsGunsFetchByKey", ckgy.NOTIFICATIONS);
        aQ = new ckha("NotificationsGunsFetchByKeyScheduleTimeMs", ckgy.NOTIFICATIONS, ckde.a);
        aR = new ckha("NotificationsGunsFetchByKeyTimeMs", ckgy.NOTIFICATIONS, ckde.a);
        aS = new ckgu("NotificationsGunsFetchByKeyFailure", ckgy.NOTIFICATIONS);
        aT = new ckgz("LocalDiscoveryNotificationAlreadySeenContentCount", ckgy.NOTIFICATIONS);
        aU = new ckhf("GenericWebviewNotificationLatency", ckgy.NOTIFICATIONS);
        aV = new ckgz("GenericWebviewNotificationCount", ckgy.NOTIFICATIONS);
        new ckgu("Maps15NotificationSuppressFromAppOpen", ckgy.NOTIFICATIONS);
        new ckha("Maps15NotificationSendLatency", ckgy.NOTIFICATIONS);
        aW = new ckgz("NotificationsNonGenericOptOutAction", ckgy.NOTIFICATIONS);
        aX = new ckgz("NotificationsMaxActionsVersionNOrAbove", ckgy.NOTIFICATIONS);
        aY = new ckgz("NotificationsMaxActionsVersionLessThanN", ckgy.NOTIFICATIONS);
        aZ = new ckgz("NotificationsIhnrSuppressedActionCount", ckgy.NOTIFICATIONS);
    }
}
