package defpackage;
/* compiled from: PG */
/* renamed from: acwu  reason: default package */
/* loaded from: classes.dex */
public final class acwu {
    public static final amuk a = amuk.v(1, 6, 22, 3, 20);
    public final boolean A;
    public final long B;
    public final boolean C;
    public final boolean D;
    public final float E;
    public final float F;
    public final int G;
    public final boolean H;
    public final boolean I;

    /* renamed from: J  reason: collision with root package name */
    public final int f31J;
    public final boolean K;
    public final int L;
    public final int M;
    public final boolean N;
    public final int O;
    public final int P;
    public final int Q;
    public final int R;
    public final int S;
    public final int T;
    public final int U;
    public final int V;
    public final amuk W;
    public final int X;
    public final int Y;
    public final int Z;
    private final boolean aA;
    private final boolean aB;
    public final int aa;
    public final boolean ab;
    public final boolean ac;
    public final boolean ad;
    public final boolean ae;
    public final int af;
    public final amuk ag;
    public final boolean ah;
    public final boolean ai;
    public final int aj;
    public final long ak;
    public final long al;
    public final double am;
    public final boolean an;
    public final boolean ao;
    public final amuk ap;
    public final boolean aq;
    public final amuk ar;
    public final long as;
    public final boolean at;
    public final amvn au;
    public final boolean av;
    private final long aw;
    private final boolean ax;
    private final boolean ay;
    private final boolean az;
    public final amvn b;
    public final amvn c;
    public final int d;
    public final amvn e;
    public final amvn f;
    public final atdl g;
    public final boolean h;
    public final boolean i;
    public final int j;
    public final boolean k;
    public final String l;
    public final boolean m;
    public final boolean n;
    public final boolean o;
    public final boolean p;
    public final boolean q;
    public final boolean r;
    public final boolean s;
    public final boolean t;
    public final int u;
    public final boolean v;
    public final boolean w;
    public final int x;
    public final boolean y;
    public final boolean z;

    public acwu() {
    }

    public acwu(amvn amvnVar, amvn amvnVar2, int i, amvn amvnVar3, amvn amvnVar4, atdl atdlVar, boolean z, boolean z2, int i2, boolean z3, String str, boolean z4, boolean z5, boolean z6, boolean z7, long j, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, int i3, boolean z13, boolean z14, boolean z15, boolean z16, boolean z17, int i4, boolean z18, boolean z19, boolean z20, boolean z21, long j2, boolean z22, boolean z23, float f, float f2, int i5, boolean z24, boolean z25, int i6, boolean z26, int i7, int i8, boolean z27, int i9, int i10, int i11, int i12, int i13, int i14, int i15, int i16, amuk amukVar, int i17, int i18, int i19, int i20, boolean z28, boolean z29, boolean z30, boolean z31, int i21, amuk amukVar2, boolean z32, boolean z33, int i22, long j3, long j4, double d, boolean z34, boolean z35, amuk amukVar3, boolean z36, amuk amukVar4, long j5, boolean z37, amvn amvnVar5, boolean z38) {
        this.b = amvnVar;
        this.c = amvnVar2;
        this.d = i;
        this.e = amvnVar3;
        this.f = amvnVar4;
        this.g = atdlVar;
        this.h = z;
        this.i = z2;
        this.j = i2;
        this.k = z3;
        this.l = str;
        this.m = z4;
        this.n = z5;
        this.o = z6;
        this.p = z7;
        this.aw = j;
        this.q = z8;
        this.ax = z9;
        this.r = z10;
        this.s = z11;
        this.t = z12;
        this.u = i3;
        this.ay = z13;
        this.az = z14;
        this.aA = z15;
        this.v = z16;
        this.w = z17;
        this.x = i4;
        this.y = z18;
        this.aB = z19;
        this.z = z20;
        this.A = z21;
        this.B = j2;
        this.C = z22;
        this.D = z23;
        this.E = f;
        this.F = f2;
        this.G = i5;
        this.H = z24;
        this.I = z25;
        this.f31J = i6;
        this.K = z26;
        this.L = i7;
        this.M = i8;
        this.N = z27;
        this.O = i9;
        this.P = i10;
        this.Q = i11;
        this.R = i12;
        this.S = i13;
        this.T = i14;
        this.U = i15;
        this.V = i16;
        this.W = amukVar;
        this.X = i17;
        this.Y = i18;
        this.Z = i19;
        this.aa = i20;
        this.ab = z28;
        this.ac = z29;
        this.ad = z30;
        this.ae = z31;
        this.af = i21;
        this.ag = amukVar2;
        this.ah = z32;
        this.ai = z33;
        this.aj = i22;
        this.ak = j3;
        this.al = j4;
        this.am = d;
        this.an = z34;
        this.ao = z35;
        this.ap = amukVar3;
        this.aq = z36;
        this.ar = amukVar4;
        this.as = j5;
        this.at = z37;
        this.au = amvnVar5;
        this.av = z38;
    }

    public final boolean equals(Object obj) {
        atdl atdlVar;
        if (obj == this) {
            return true;
        }
        if (obj instanceof acwu) {
            acwu acwuVar = (acwu) obj;
            if (this.b.equals(acwuVar.b) && this.c.equals(acwuVar.c) && this.d == acwuVar.d && this.e.equals(acwuVar.e) && this.f.equals(acwuVar.f) && ((atdlVar = this.g) != null ? atdlVar.equals(acwuVar.g) : acwuVar.g == null) && this.h == acwuVar.h && this.i == acwuVar.i && this.j == acwuVar.j && this.k == acwuVar.k && this.l.equals(acwuVar.l) && this.m == acwuVar.m && this.n == acwuVar.n && this.o == acwuVar.o && this.p == acwuVar.p && this.aw == acwuVar.aw && this.q == acwuVar.q && this.ax == acwuVar.ax && this.r == acwuVar.r && this.s == acwuVar.s && this.t == acwuVar.t && this.u == acwuVar.u && this.ay == acwuVar.ay && this.az == acwuVar.az && this.aA == acwuVar.aA && this.v == acwuVar.v && this.w == acwuVar.w && this.x == acwuVar.x && this.y == acwuVar.y && this.aB == acwuVar.aB && this.z == acwuVar.z && this.A == acwuVar.A && this.B == acwuVar.B && this.C == acwuVar.C && this.D == acwuVar.D && Float.floatToIntBits(this.E) == Float.floatToIntBits(acwuVar.E) && Float.floatToIntBits(this.F) == Float.floatToIntBits(acwuVar.F) && this.G == acwuVar.G && this.H == acwuVar.H && this.I == acwuVar.I && this.f31J == acwuVar.f31J && this.K == acwuVar.K && this.L == acwuVar.L && this.M == acwuVar.M && this.N == acwuVar.N && this.O == acwuVar.O && this.P == acwuVar.P && this.Q == acwuVar.Q && this.R == acwuVar.R && this.S == acwuVar.S && this.T == acwuVar.T && this.U == acwuVar.U && this.V == acwuVar.V && amxp.v(this.W, acwuVar.W) && this.X == acwuVar.X && this.Y == acwuVar.Y && this.Z == acwuVar.Z && this.aa == acwuVar.aa && this.ab == acwuVar.ab && this.ac == acwuVar.ac && this.ad == acwuVar.ad && this.ae == acwuVar.ae && this.af == acwuVar.af && amxp.v(this.ag, acwuVar.ag) && this.ah == acwuVar.ah && this.ai == acwuVar.ai && this.aj == acwuVar.aj && this.ak == acwuVar.ak && this.al == acwuVar.al && Double.doubleToLongBits(this.am) == Double.doubleToLongBits(acwuVar.am) && this.an == acwuVar.an && this.ao == acwuVar.ao && amxp.v(this.ap, acwuVar.ap) && this.aq == acwuVar.aq && amxp.v(this.ar, acwuVar.ar) && this.as == acwuVar.as && this.at == acwuVar.at && this.au.equals(acwuVar.au) && this.av == acwuVar.av) {
                return true;
            }
        }
        return false;
    }

    public final int hashCode() {
        int hashCode = (((((((((this.b.hashCode() ^ 1000003) * 1000003) ^ this.c.hashCode()) * 1000003) ^ this.d) * 1000003) ^ this.e.hashCode()) * 1000003) ^ this.f.hashCode()) * 1000003;
        atdl atdlVar = this.g;
        int i = 1237;
        int hashCode2 = (((((((((((((((((hashCode ^ (atdlVar == null ? 0 : atdlVar.hashCode())) * 1000003) ^ (true != this.h ? 1237 : 1231)) * 1000003) ^ (true != this.i ? 1237 : 1231)) * 1000003) ^ this.j) * 1000003) ^ (true != this.k ? 1237 : 1231)) * 1000003) ^ this.l.hashCode()) * 1000003) ^ (true != this.m ? 1237 : 1231)) * 1000003) ^ (true != this.n ? 1237 : 1231)) * 1000003) ^ (true != this.o ? 1237 : 1231)) * 1000003;
        int i2 = true != this.p ? 1237 : 1231;
        long j = this.aw;
        int i3 = (((((((((((((((((((((((((((((((((hashCode2 ^ i2) * 1000003) ^ ((int) (j ^ (j >>> 32)))) * 1000003) ^ (true != this.q ? 1237 : 1231)) * 1000003) ^ (true != this.ax ? 1237 : 1231)) * 1000003) ^ (true != this.r ? 1237 : 1231)) * 1000003) ^ (true != this.s ? 1237 : 1231)) * 1000003) ^ (true != this.t ? 1237 : 1231)) * 1000003) ^ this.u) * 1000003) ^ (true != this.ay ? 1237 : 1231)) * 1000003) ^ (true != this.az ? 1237 : 1231)) * 1000003) ^ (true != this.aA ? 1237 : 1231)) * 1000003) ^ (true != this.v ? 1237 : 1231)) * 1000003) ^ (true != this.w ? 1237 : 1231)) * 1000003) ^ this.x) * 1000003) ^ (true != this.y ? 1237 : 1231)) * 1000003) ^ (true != this.aB ? 1237 : 1231)) * 1000003) ^ (true != this.z ? 1237 : 1231)) * 1000003;
        int i4 = true != this.A ? 1237 : 1231;
        long j2 = this.B;
        int floatToIntBits = (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((i3 ^ i4) * 1000003) ^ ((int) (j2 ^ (j2 >>> 32)))) * 1000003) ^ (true != this.C ? 1237 : 1231)) * 1000003) ^ (true != this.D ? 1237 : 1231)) * 1000003) ^ Float.floatToIntBits(this.E)) * 1000003) ^ Float.floatToIntBits(this.F)) * 1000003) ^ this.G) * 1000003) ^ (true != this.H ? 1237 : 1231)) * 1000003) ^ (true != this.I ? 1237 : 1231)) * 1000003) ^ this.f31J) * 1000003) ^ (true != this.K ? 1237 : 1231)) * 1000003) ^ this.L) * 1000003) ^ this.M) * 1000003) ^ (true != this.N ? 1237 : 1231)) * 1000003) ^ this.O) * 1000003) ^ this.P) * 1000003) ^ this.Q) * 1000003) ^ this.R) * 1000003) ^ this.S) * 1000003) ^ this.T) * 1000003) ^ this.U) * 1000003) ^ this.V) * 1000003) ^ this.W.hashCode()) * 1000003) ^ this.X) * 1000003) ^ this.Y) * 1000003) ^ this.Z) * 1000003) ^ this.aa) * 1000003) ^ (true != this.ab ? 1237 : 1231)) * 1000003) ^ (true != this.ac ? 1237 : 1231)) * 1000003) ^ (true != this.ad ? 1237 : 1231)) * 1000003) ^ (true != this.ae ? 1237 : 1231)) * 1000003) ^ this.af) * 1000003) ^ this.ag.hashCode()) * 1000003) ^ (true != this.ah ? 1237 : 1231)) * 1000003;
        int i5 = true != this.ai ? 1237 : 1231;
        int i6 = this.aj;
        long j3 = this.ak;
        long j4 = this.al;
        int doubleToLongBits = (((((((((((((((floatToIntBits ^ i5) * 1000003) ^ i6) * 1000003) ^ ((int) ((j3 >>> 32) ^ j3))) * 1000003) ^ ((int) ((j4 >>> 32) ^ j4))) * 1000003) ^ ((int) ((Double.doubleToLongBits(this.am) >>> 32) ^ Double.doubleToLongBits(this.am)))) * 1000003) ^ (true != this.an ? 1237 : 1231)) * 1000003) ^ (true != this.ao ? 1237 : 1231)) * 1000003) ^ this.ap.hashCode()) * 1000003;
        int i7 = true != this.aq ? 1237 : 1231;
        int hashCode3 = this.ar.hashCode();
        long j5 = this.as;
        int hashCode4 = (((((((((doubleToLongBits ^ i7) * 1000003) ^ hashCode3) * 1000003) ^ ((int) ((j5 >>> 32) ^ j5))) * 1000003) ^ (true != this.at ? 1237 : 1231)) * 1000003) ^ this.au.hashCode()) * 1000003;
        if (true == this.av) {
            i = 1231;
        }
        return hashCode4 ^ i;
    }

    public final String toString() {
        String valueOf = String.valueOf(this.b);
        String valueOf2 = String.valueOf(this.c);
        int i = this.d;
        String valueOf3 = String.valueOf(this.e);
        String valueOf4 = String.valueOf(this.f);
        String valueOf5 = String.valueOf(this.g);
        boolean z = this.h;
        boolean z2 = this.i;
        int i2 = this.j;
        boolean z3 = this.k;
        String str = this.l;
        boolean z4 = this.m;
        boolean z5 = this.n;
        boolean z6 = this.o;
        boolean z7 = this.p;
        long j = this.aw;
        boolean z8 = this.q;
        boolean z9 = this.ax;
        boolean z10 = this.r;
        boolean z11 = this.s;
        boolean z12 = this.t;
        int i3 = this.u;
        boolean z13 = this.ay;
        boolean z14 = this.az;
        boolean z15 = this.aA;
        boolean z16 = this.v;
        boolean z17 = this.w;
        int i4 = this.x;
        boolean z18 = this.y;
        boolean z19 = this.aB;
        boolean z20 = this.z;
        boolean z21 = this.A;
        long j2 = this.B;
        boolean z22 = this.C;
        boolean z23 = this.D;
        float f = this.E;
        float f2 = this.F;
        int i5 = this.G;
        boolean z24 = this.H;
        boolean z25 = this.I;
        int i6 = this.f31J;
        boolean z26 = this.K;
        int i7 = this.L;
        int i8 = this.M;
        boolean z27 = this.N;
        int i9 = this.O;
        int i10 = this.P;
        int i11 = this.Q;
        int i12 = this.R;
        int i13 = this.S;
        int i14 = this.T;
        int i15 = this.U;
        int i16 = this.V;
        String valueOf6 = String.valueOf(this.W);
        int i17 = this.X;
        int i18 = this.Y;
        int i19 = this.Z;
        int i20 = this.aa;
        boolean z28 = this.ab;
        boolean z29 = this.ac;
        boolean z30 = this.ad;
        boolean z31 = this.ae;
        int i21 = this.af;
        String valueOf7 = String.valueOf(this.ag);
        boolean z32 = this.ah;
        boolean z33 = this.ai;
        int i22 = this.aj;
        long j3 = this.ak;
        long j4 = this.al;
        double d = this.am;
        boolean z34 = this.an;
        boolean z35 = this.ao;
        String valueOf8 = String.valueOf(this.ap);
        boolean z36 = this.aq;
        String valueOf9 = String.valueOf(this.ar);
        long j5 = this.as;
        boolean z37 = this.at;
        String valueOf10 = String.valueOf(this.au);
        boolean z38 = this.av;
        int length = String.valueOf(valueOf).length() + 3167 + String.valueOf(valueOf2).length() + String.valueOf(valueOf3).length();
        int length2 = String.valueOf(valueOf4).length();
        int length3 = String.valueOf(valueOf5).length();
        int length4 = String.valueOf(str).length();
        int length5 = String.valueOf(valueOf6).length();
        int length6 = String.valueOf(valueOf7).length();
        int length7 = String.valueOf(valueOf8).length();
        StringBuilder sb = new StringBuilder(length + length2 + length3 + length4 + length5 + length6 + length7 + String.valueOf(valueOf9).length() + String.valueOf(valueOf10).length());
        sb.append("MdxConfig{capabilities=");
        sb.append(valueOf);
        sb.append(", experiments=");
        sb.append(valueOf2);
        sb.append(", promotionCounterReferenceId=");
        sb.append(i);
        sb.append(", promotions=");
        sb.append(valueOf3);
        sb.append(", promotionTriggers=");
        sb.append(valueOf4);
        sb.append(", allowlistingConfig=");
        sb.append(valueOf5);
        sb.append(", enableSkippableAds=");
        sb.append(z);
        sb.append(", enablePlaylistModes=");
        sb.append(z2);
        sb.append(", localTransportOption=");
        sb.append(i2);
        sb.append(", isLivingRoomNotificationsEnabled=");
        sb.append(z3);
        sb.append(", mdxImpactedSessionsServerEvent=");
        sb.append(str);
        sb.append(", enableErrorDialogForMdxConnections=");
        sb.append(z4);
        sb.append(", enableCastToNative=");
        sb.append(z5);
        sb.append(", mdxSmartRemoteEnableMealbar=");
        sb.append(z6);
        sb.append(", enableRemoteButtonsInCastDialog=");
        sb.append(z7);
        sb.append(", persistentCastIconDialogTimeoutMs=");
        sb.append(j);
        sb.append(", enablePersistentCastIcon=");
        sb.append(z8);
        sb.append(", enableLinkTvCode=");
        sb.append(z9);
        sb.append(", enableSeamlessDelegateAccountSignInFix=");
        sb.append(z10);
        sb.append(", enableWoL=");
        sb.append(z11);
        sb.append(", enableCompassSessionServerRouting=");
        sb.append(z12);
        sb.append(", mdxNotificationsMaxDetectedScreensNum=");
        sb.append(i3);
        sb.append(", enableMdxNotifViaGelLog=");
        sb.append(z13);
        sb.append(", enableMdxNotifViaGelAndInnertube=");
        sb.append(z14);
        sb.append(", enableDialCacheUseIpIdentifier=");
        sb.append(z15);
        sb.append(", prioritizeMobileSenderPlaybackStateOnConnection=");
        sb.append(z16);
        sb.append(", enableRemoteDeviceContext=");
        sb.append(z17);
        sb.append(", mdxAssistedSignInQuietPeriodDays=");
        sb.append(i4);
        sb.append(", enablePassiveSignIn=");
        sb.append(z18);
        sb.append(", enableMediaRouteProviderService=");
        sb.append(z19);
        sb.append(", enableGelForCsi=");
        sb.append(z20);
        sb.append(", enableRetryOnCastConnectionFailure=");
        sb.append(z21);
        sb.append(", oauthTokenRefreshIntervalMs=");
        sb.append(j2);
        sb.append(", enableClearOauthTokenOnAuthError=");
        sb.append(z22);
        sb.append(", enableMediaRouteOutputSwitcher=");
        sb.append(z23);
        sb.append(", castV3InitializationInitialRetryIntervalSec=");
        sb.append(f);
        sb.append(", castV3InitializationRetryBackoffFactor=");
        sb.append(f2);
        sb.append(", connectionFailureMaxRetryAttempt=");
        sb.append(i5);
        sb.append(", enableDialShortLivedLoungeToken=");
        sb.append(z24);
        sb.append(", enableCastShortLivedLoungeToken=");
        sb.append(z25);
        sb.append(", mdxHeartbeatIntervalMinutes=");
        sb.append(i6);
        sb.append(", enableSignInButtonInCastDialog=");
        sb.append(z26);
        sb.append(", shortLivedLoungeTokenDialRefreshFailureRetryIntervalSec=");
        sb.append(i7);
        sb.append(", shortLivedLoungeTokenCastRefreshFailureRetryIntervalSec=");
        sb.append(i8);
        sb.append(", enableAnrFixes=");
        sb.append(z27);
        sb.append(", loungeTokenPollingTimeoutMs=");
        sb.append(i9);
        sb.append(", loungeTokenPollingMaxRetries=");
        sb.append(i10);
        sb.append(", bindToLoungeTimeoutMs=");
        sb.append(i11);
        sb.append(", hangingGetToLoungeTimeoutMs=");
        sb.append(i12);
        sb.append(", joinLoungeMaxRetries=");
        sb.append(i13);
        sb.append(", dialCheckAppStatusHttpRequestTimeoutMs=");
        sb.append(i14);
        sb.append(", dialLaunchAppHttpRequestTimeoutMs=");
        sb.append(i15);
        sb.append(", dialScreenIdPollingTimeoutMs=");
        sb.append(i16);
        sb.append(", dialScreenIdPollingIntervalsMs=");
        sb.append(valueOf6);
        sb.append(", wolMagicPacketBroadcastIntervalMs=");
        sb.append(i17);
        sb.append(", wolStatusCheckIntervalMs=");
        sb.append(i18);
        sb.append(", wolStatusCheckDefaultTimeoutMs=");
        sb.append(i19);
        sb.append(", wolCacheEntryDurationMs=");
        sb.append(i20);
        sb.append(", disableDialOnCastDevices=");
        sb.append(z28);
        sb.append(", disableSavedDialScreenId=");
        sb.append(z29);
        sb.append(", enableAutoconnectPrompt=");
        sb.append(z30);
        sb.append(", enableAutoconnectPromptCounterfactual=");
        sb.append(z31);
        sb.append(", shortLivedLoungeTokenCastTimeoutSecBeforeTriggeringNoLoungeTokenResponseError=");
        sb.append(i21);
        sb.append(", blockedDialModels=");
        sb.append(valueOf7);
        sb.append(", enableCastSettingsPrompt=");
        sb.append(z32);
        sb.append(", enableGetScreenAvailabilityRequestWithExtraInfo=");
        sb.append(z33);
        sb.append(", deviceManagementSnapshotLoggingDurationCoveredHour=");
        sb.append(i22);
        sb.append(", wolSmartFilteringEffectiveLogDurationHour=");
        sb.append(j3);
        sb.append(", wolSmartFilteringEffectiveUsageCount=");
        sb.append(j4);
        sb.append(", wolSmartFilteringSuccessRateThreshold=");
        sb.append(d);
        sb.append(", disableSaveSessionStarting=");
        sb.append(z34);
        sb.append(", enforceDialIncludeListAfterStatusCheck=");
        sb.append(z35);
        sb.append(", expectedDisconnectReasonList=");
        sb.append(valueOf8);
        sb.append(", disableRelaunchingCastAppForSingleUserSessions=");
        sb.append(z36);
        sb.append(", forcefullyRetryDisconnectReasonList=");
        sb.append(valueOf9);
        sb.append(", sessionRecoveryExpirationTimeMs=");
        sb.append(j5);
        sb.append(", disableWolOnUnknownReceiver=");
        sb.append(z37);
        sb.append(", connectionRetryExcludedReasonList=");
        sb.append(valueOf10);
        sb.append(", enableCastAuthErrorDialog=");
        sb.append(z38);
        sb.append("}");
        return sb.toString();
    }
}
