package defpackage;

import java.util.Arrays;
import java.util.HashMap;
/* compiled from: PG */
/* renamed from: ain  reason: default package */
/* loaded from: classes.dex */
public final class ain {
    int a;
    public final aiq b = new aiq();
    public final aip c = new aip();
    public final aio d = new aio();
    public final air e = new air();
    public HashMap f = new HashMap();
    aim g;

    public final void a(aii aiiVar) {
        aio aioVar = this.d;
        aiiVar.d = aioVar.i;
        aiiVar.e = aioVar.j;
        aiiVar.f = aioVar.k;
        aiiVar.g = aioVar.l;
        aiiVar.h = aioVar.m;
        aiiVar.i = aioVar.n;
        aiiVar.j = aioVar.o;
        aiiVar.k = aioVar.p;
        aiiVar.l = aioVar.q;
        aiiVar.m = aioVar.r;
        aiiVar.n = aioVar.s;
        aiiVar.r = aioVar.t;
        aiiVar.s = aioVar.u;
        aiiVar.t = aioVar.v;
        aiiVar.u = aioVar.w;
        aiiVar.leftMargin = aioVar.G;
        aiiVar.rightMargin = this.d.H;
        aiiVar.topMargin = this.d.I;
        aiiVar.bottomMargin = this.d.f52J;
        aio aioVar2 = this.d;
        aiiVar.z = aioVar2.S;
        aiiVar.A = aioVar2.R;
        aiiVar.w = aioVar2.O;
        aiiVar.y = aioVar2.Q;
        aiiVar.D = aioVar2.x;
        aiiVar.E = aioVar2.y;
        aiiVar.o = aioVar2.A;
        aiiVar.p = aioVar2.B;
        aiiVar.q = aioVar2.C;
        aiiVar.F = aioVar2.z;
        aiiVar.S = aioVar2.D;
        aiiVar.T = aioVar2.E;
        aiiVar.H = aioVar2.U;
        aiiVar.G = aioVar2.V;
        aiiVar.f50J = aioVar2.X;
        aiiVar.I = aioVar2.W;
        aiiVar.V = aioVar2.am;
        aiiVar.W = aioVar2.an;
        aiiVar.K = aioVar2.Y;
        aiiVar.L = aioVar2.Z;
        aiiVar.O = aioVar2.aa;
        aiiVar.P = aioVar2.ab;
        aiiVar.M = aioVar2.ac;
        aiiVar.N = aioVar2.ad;
        aiiVar.Q = aioVar2.ae;
        aiiVar.R = aioVar2.af;
        aiiVar.U = aioVar2.F;
        aiiVar.c = aioVar2.h;
        aiiVar.a = aioVar2.f;
        aiiVar.b = aioVar2.g;
        aiiVar.width = aioVar2.d;
        aiiVar.height = this.d.e;
        aio aioVar3 = this.d;
        String str = aioVar3.al;
        if (str != null) {
            aiiVar.X = str;
        }
        aiiVar.Y = aioVar3.ap;
        aiiVar.setMarginStart(aioVar3.L);
        aiiVar.setMarginEnd(this.d.K);
        aiiVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        ain ainVar = new ain();
        aio aioVar = ainVar.d;
        aio aioVar2 = this.d;
        aioVar.b = aioVar2.b;
        aioVar.d = aioVar2.d;
        aioVar.c = aioVar2.c;
        aioVar.e = aioVar2.e;
        aioVar.f = aioVar2.f;
        aioVar.g = aioVar2.g;
        aioVar.h = aioVar2.h;
        aioVar.i = aioVar2.i;
        aioVar.j = aioVar2.j;
        aioVar.k = aioVar2.k;
        aioVar.l = aioVar2.l;
        aioVar.m = aioVar2.m;
        aioVar.n = aioVar2.n;
        aioVar.o = aioVar2.o;
        aioVar.p = aioVar2.p;
        aioVar.q = aioVar2.q;
        aioVar.r = aioVar2.r;
        aioVar.s = aioVar2.s;
        aioVar.t = aioVar2.t;
        aioVar.u = aioVar2.u;
        aioVar.v = aioVar2.v;
        aioVar.w = aioVar2.w;
        aioVar.x = aioVar2.x;
        aioVar.y = aioVar2.y;
        aioVar.z = aioVar2.z;
        aioVar.A = aioVar2.A;
        aioVar.B = aioVar2.B;
        aioVar.C = aioVar2.C;
        aioVar.D = aioVar2.D;
        aioVar.E = aioVar2.E;
        aioVar.F = aioVar2.F;
        aioVar.G = aioVar2.G;
        aioVar.H = aioVar2.H;
        aioVar.I = aioVar2.I;
        aioVar.f52J = aioVar2.f52J;
        aioVar.K = aioVar2.K;
        aioVar.L = aioVar2.L;
        aioVar.M = aioVar2.M;
        aioVar.N = aioVar2.N;
        aioVar.O = aioVar2.O;
        aioVar.P = aioVar2.P;
        aioVar.Q = aioVar2.Q;
        aioVar.R = aioVar2.R;
        aioVar.S = aioVar2.S;
        aioVar.T = aioVar2.T;
        aioVar.U = aioVar2.U;
        aioVar.V = aioVar2.V;
        aioVar.W = aioVar2.W;
        aioVar.X = aioVar2.X;
        aioVar.Y = aioVar2.Y;
        aioVar.Z = aioVar2.Z;
        aioVar.aa = aioVar2.aa;
        aioVar.ab = aioVar2.ab;
        aioVar.ac = aioVar2.ac;
        aioVar.ad = aioVar2.ad;
        aioVar.ae = aioVar2.ae;
        aioVar.af = aioVar2.af;
        aioVar.ag = aioVar2.ag;
        aioVar.ah = aioVar2.ah;
        aioVar.ai = aioVar2.ai;
        aioVar.al = aioVar2.al;
        int[] iArr = aioVar2.aj;
        if (iArr != null) {
            aioVar.aj = Arrays.copyOf(iArr, iArr.length);
        } else {
            aioVar.aj = null;
        }
        aioVar.ak = aioVar2.ak;
        aioVar.am = aioVar2.am;
        aioVar.an = aioVar2.an;
        aioVar.ao = aioVar2.ao;
        aioVar.ap = aioVar2.ap;
        aip aipVar = ainVar.c;
        aip aipVar2 = this.c;
        aipVar.b = aipVar2.b;
        aipVar.c = aipVar2.c;
        aipVar.e = aipVar2.e;
        aipVar.f = aipVar2.f;
        aipVar.g = aipVar2.g;
        aipVar.j = aipVar2.j;
        aipVar.h = aipVar2.h;
        aipVar.i = aipVar2.i;
        aiq aiqVar = ainVar.b;
        aiq aiqVar2 = this.b;
        aiqVar.a = aiqVar2.a;
        aiqVar.b = aiqVar2.b;
        aiqVar.d = aiqVar2.d;
        aiqVar.e = aiqVar2.e;
        aiqVar.c = aiqVar2.c;
        air airVar = ainVar.e;
        air airVar2 = this.e;
        airVar.b = airVar2.b;
        airVar.c = airVar2.c;
        airVar.d = airVar2.d;
        airVar.e = airVar2.e;
        airVar.f = airVar2.f;
        airVar.g = airVar2.g;
        airVar.h = airVar2.h;
        airVar.i = airVar2.i;
        airVar.j = airVar2.j;
        airVar.k = airVar2.k;
        airVar.l = airVar2.l;
        airVar.m = airVar2.m;
        airVar.n = airVar2.n;
        airVar.o = airVar2.o;
        ainVar.a = this.a;
        ainVar.g = this.g;
        return ainVar;
    }
}
