package defpackage;
/* compiled from: PG */
/* renamed from: bs  reason: default package */
/* loaded from: classes2.dex */
public final class bs {
    public int b;
    public int c;
    int d;
    boolean a = false;
    public int e = -1;
    public int f = -1;
    public float g = -1.0f;
    public int h = -1;
    public int i = -1;
    public int j = -1;
    public int k = -1;
    public int l = -1;
    public int m = -1;
    public int n = -1;
    public int o = -1;
    public int p = -1;
    public int q = -1;
    public int r = -1;
    public int s = -1;
    public int t = -1;
    public float u = 0.5f;
    public float v = 0.5f;
    public String w = null;
    public int x = -1;
    public int y = -1;
    public int z = -1;
    public int A = -1;
    public int B = -1;
    public int C = -1;
    public int D = -1;
    public int E = -1;
    public int F = -1;
    public int G = 0;
    public int H = -1;
    public int I = -1;

    /* renamed from: J  reason: collision with root package name */
    public int f143J = -1;
    public int K = -1;
    public int L = -1;
    public int M = -1;
    public float N = 0.0f;
    public float O = 0.0f;
    public int P = 0;
    public int Q = 0;
    public float R = 1.0f;
    public boolean S = false;
    public float T = 0.0f;
    public float U = 0.0f;
    public float V = 0.0f;
    public float W = 1.0f;
    public float X = 1.0f;
    public float Y = 0.0f;
    public float Z = 0.0f;
    public float aa = 0.0f;
    public float ab = 0.0f;
    public float ac = 0.0f;
    public int ad = -1;
    public int ae = -1;
    public int af = -1;
    public int ag = -1;
    public int ah = -1;
    public int ai = -1;

    public final void a(br brVar) {
        brVar.d = this.h;
        brVar.e = this.i;
        brVar.f = this.j;
        brVar.g = this.k;
        brVar.h = this.l;
        brVar.i = this.m;
        brVar.j = this.n;
        brVar.k = this.o;
        brVar.l = this.p;
        brVar.m = this.q;
        brVar.n = this.r;
        brVar.o = this.s;
        brVar.p = this.t;
        brVar.leftMargin = this.A;
        brVar.rightMargin = this.B;
        brVar.topMargin = this.C;
        brVar.bottomMargin = this.D;
        brVar.u = this.M;
        brVar.v = this.L;
        brVar.w = this.u;
        brVar.x = this.v;
        brVar.y = this.w;
        brVar.K = this.x;
        brVar.L = this.y;
        brVar.B = this.N;
        brVar.A = this.O;
        brVar.D = this.Q;
        brVar.C = this.P;
        brVar.E = this.ad;
        brVar.F = this.ae;
        brVar.I = this.af;
        brVar.f142J = this.ag;
        brVar.G = this.ah;
        brVar.H = this.ai;
        brVar.M = this.z;
        brVar.c = this.g;
        brVar.a = this.e;
        brVar.b = this.f;
        brVar.width = this.b;
        brVar.height = this.c;
        brVar.setMarginStart(this.F);
        brVar.setMarginEnd(this.E);
        brVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        bs bsVar = new bs();
        bsVar.a = this.a;
        bsVar.b = this.b;
        bsVar.c = this.c;
        bsVar.e = this.e;
        bsVar.f = this.f;
        bsVar.g = this.g;
        bsVar.h = this.h;
        bsVar.i = this.i;
        bsVar.j = this.j;
        bsVar.k = this.k;
        bsVar.l = this.l;
        bsVar.m = this.m;
        bsVar.n = this.n;
        bsVar.o = this.o;
        bsVar.p = this.p;
        bsVar.q = this.q;
        bsVar.r = this.r;
        bsVar.s = this.s;
        bsVar.t = this.t;
        bsVar.u = this.u;
        bsVar.v = this.v;
        bsVar.w = this.w;
        bsVar.x = this.x;
        bsVar.y = this.y;
        bsVar.u = this.u;
        bsVar.u = this.u;
        bsVar.u = this.u;
        bsVar.u = this.u;
        bsVar.u = this.u;
        bsVar.z = this.z;
        bsVar.A = this.A;
        bsVar.B = this.B;
        bsVar.C = this.C;
        bsVar.D = this.D;
        bsVar.E = this.E;
        bsVar.F = this.F;
        bsVar.G = this.G;
        bsVar.H = this.H;
        bsVar.I = this.I;
        bsVar.f143J = this.f143J;
        bsVar.K = this.K;
        bsVar.L = this.L;
        bsVar.M = this.M;
        bsVar.N = this.N;
        bsVar.O = this.O;
        bsVar.P = this.P;
        bsVar.Q = this.Q;
        bsVar.R = this.R;
        bsVar.S = this.S;
        bsVar.T = this.T;
        bsVar.U = this.U;
        bsVar.V = this.V;
        bsVar.W = this.W;
        bsVar.X = this.X;
        bsVar.Y = this.Y;
        bsVar.Z = this.Z;
        bsVar.aa = this.aa;
        bsVar.ab = this.ab;
        bsVar.ac = this.ac;
        bsVar.ad = this.ad;
        bsVar.ae = this.ae;
        bsVar.af = this.af;
        bsVar.ag = this.ag;
        bsVar.ah = this.ah;
        bsVar.ai = this.ai;
        return bsVar;
    }
}
