package defpackage;
/* compiled from: PG */
/* renamed from: cee  reason: default package */
/* loaded from: classes2.dex */
public final class cee {
    static final ced a;
    public static final ced b;
    public static final ced c;
    static final ced d;
    static final ced e;
    static final ced f;
    public static final ced g;
    public static final ced h;
    static final ced i;
    static final ced j;
    static final ced k;

    static {
        cec a2 = ced.a();
        a2.a = 3;
        a2.b = "Google Play In-app Billing API version is less than 3";
        a = a2.a();
        cec a3 = ced.a();
        a3.a = 3;
        a3.b = "Google Play In-app Billing API version is less than 9";
        a3.a();
        cec a4 = ced.a();
        a4.a = 3;
        a4.b = "Billing service unavailable on device.";
        b = a4.a();
        cec a5 = ced.a();
        a5.a = 5;
        a5.b = "Client is already in the process of connecting to billing service.";
        c = a5.a();
        cec a6 = ced.a();
        a6.a = 3;
        a6.b = "Play Store version installed does not support cross selling products.";
        a6.a();
        cec a7 = ced.a();
        a7.a = 5;
        a7.b = "The list of SKUs can't be empty.";
        a7.a();
        cec a8 = ced.a();
        a8.a = 5;
        a8.b = "SKU type can't be empty.";
        a8.a();
        cec a9 = ced.a();
        a9.a = 5;
        a9.b = "Product type can't be empty.";
        a9.a();
        cec a10 = ced.a();
        a10.a = -2;
        a10.b = "Client does not support extra params.";
        d = a10.a();
        cec a11 = ced.a();
        a11.a = -2;
        a11.b = "Client does not support the feature.";
        e = a11.a();
        cec a12 = ced.a();
        a12.a = -2;
        a12.b = "Client does not support get purchase history.";
        a12.a();
        cec a13 = ced.a();
        a13.a = 5;
        a13.b = "Invalid purchase token.";
        a13.a();
        cec a14 = ced.a();
        a14.a = 6;
        a14.b = "An internal error occurred.";
        f = a14.a();
        cec a15 = ced.a();
        a15.a = 4;
        a15.b = "Item is unavailable for purchase.";
        a15.a();
        cec a16 = ced.a();
        a16.a = 5;
        a16.b = "SKU can't be null.";
        a16.a();
        cec a17 = ced.a();
        a17.a = 5;
        a17.b = "SKU type can't be null.";
        a17.a();
        cec a18 = ced.a();
        a18.a = 0;
        g = a18.a();
        cec a19 = ced.a();
        a19.a = -1;
        a19.b = "Service connection is disconnected.";
        h = a19.a();
        cec a20 = ced.a();
        a20.a = -3;
        a20.b = "Timeout communicating with service.";
        i = a20.a();
        cec a21 = ced.a();
        a21.a = -2;
        a21.b = "Client doesn't support subscriptions.";
        j = a21.a();
        cec a22 = ced.a();
        a22.a = -2;
        a22.b = "Client doesn't support subscriptions update.";
        a22.a();
        cec a23 = ced.a();
        a23.a = -2;
        a23.b = "Client doesn't support multi-item purchases.";
        k = a23.a();
        cec a24 = ced.a();
        a24.a = 5;
        a24.b = "Unknown feature";
        a24.a();
    }
}
