package defpackage;

import android.app.Application;
/* compiled from: PG */
/* renamed from: evt  reason: default package */
/* loaded from: classes3.dex */
public final class evt {
    public final acvp a;
    public final yni b;

    public evt(acvp acvpVar, yni yniVar) {
        acvpVar.getClass();
        this.a = acvpVar;
        yniVar.getClass();
        this.b = yniVar;
    }

    public final void a(Application application, azqb azqbVar) {
        application.registerActivityLifecycleCallbacks(new evr(this, azqbVar));
    }

    public final void b() {
        this.a.b(evi.class, new evb(0)).c(evk.class);
        this.a.k(eve.class, evj.class, new evb(1));
        this.a.h(evi.class, "f_unknown");
        this.a.h(eve.class, "f_proc");
        this.a.g(evi.class, new evq(1));
    }

    public final void c(aiji aijiVar, afkf afkfVar, ywk ywkVar) {
        aijiVar.getClass();
        afkfVar.getClass();
        ywkVar.getClass();
        evs evsVar = new evs();
        boolean l = ywkVar.l(ywk.O);
        Class cls = l ? ajps.class : ewc.class;
        acvn c = this.a.c(evc.class, evj.class, new evb(2), true);
        c.b(evw.class);
        c.c(ewb.class);
        c.c(cls);
        if (ywkVar.l(ywk.P)) {
            c.c(evy.class);
        }
        wwu wwuVar = new wwu(aijiVar, afkfVar, evsVar, 3, (char[]) null);
        acvn c2 = this.a.c(evl.class, evj.class, wwuVar, true);
        c2.b(evx.class);
        c2.c(ahgv.class);
        c2.c(ahgw.class);
        c2.c(ahgr.class);
        c2.c(ahha.class);
        c2.c(aikd.class);
        c2.c(ahgq.class);
        acvn c3 = this.a.c(evg.class, evd.class, new evb(4), true);
        c3.b(ewx.class);
        c3.b(ewv.class);
        c3.c(exb.class);
        acvn d = this.a.d(exd.class, wwuVar, new evp(this));
        d.c(ahgv.class);
        d.c(ahgw.class);
        d.c(ahgr.class);
        d.c(exd.class);
        d.c(ahha.class);
        d.c(aikd.class);
        d.c(ahgq.class);
        acvn b = this.a.b(ewg.class, new eud(1));
        b.c(ewh.class);
        b.c(ewi.class);
        b.c(ewk.class);
        b.c(ewj.class);
        b.c(ewl.class);
        b.c(ewr.class);
        if (!l) {
            this.a.c(ajpt.class, evd.class, new eud(5), false).c(ajps.class);
        }
        this.a.c(ajpr.class, evh.class, new eud(6), false).c(ajpq.class);
        acvn b2 = this.a.b(ahha.class, wwuVar);
        b2.c(ahgv.class);
        b2.c(ahgw.class);
        b2.c(ahgr.class);
        b2.c(exd.class);
        b2.c(ahha.class);
        b2.c(aikd.class);
        b2.c(ahgq.class);
        acvn b3 = this.a.b(wxo.class, new wwu(aijiVar, afkfVar, evsVar, 1));
        b3.c(ahgv.class);
        b3.c(ahgw.class);
        b3.c(ahgr.class);
        b3.b(exd.class);
        b3.b(ahha.class);
        b3.b(aikd.class);
        b3.b(ahgq.class);
        acvn b4 = this.a.b(wxu.class, new wwu(aijiVar, afkfVar, evsVar, 2, (byte[]) null));
        b4.c(ahgv.class);
        b4.c(ahgw.class);
        b4.c(ahgr.class);
        b4.b(wxt.class);
        b4.b(exd.class);
        b4.b(ahha.class);
        b4.b(aikd.class);
        b4.b(ahgq.class);
        acvn b5 = this.a.b(wyg.class, new wwu(aijiVar, afkfVar, evsVar));
        b5.c(ahgv.class);
        b5.c(ahgw.class);
        b5.c(ahgr.class);
        b5.b(exd.class);
        b5.b(ahha.class);
        b5.b(aikd.class);
        b5.b(ahgq.class);
        acvn b6 = this.a.b(wyo.class, new ahft("va"));
        b6.c(wxu.class);
        b6.b(wxt.class);
        b6.b(exd.class);
        acvn b7 = this.a.b(wyf.class, new ahft("av"));
        b7.c(wye.class);
        b7.b(exd.class);
        b7.b(ahha.class);
        b7.b(aikd.class);
        b7.b(ahgq.class);
        acvn b8 = this.a.b(ety.class, new eud());
        b8.c(ahgv.class);
        b8.c(ahgw.class);
        b8.b(aikd.class);
        b8.b(etx.class);
        b8.b(ety.class);
        this.a.h(evc.class, "f_home");
        this.a.h(evl.class, "f_watch");
        this.a.h(evg.class, "f_search");
        this.a.h(evk.class, "f_unknown_e");
        this.a.h(evv.class, "app_l");
        this.a.h(evw.class, "ol_i");
        this.a.h(evx.class, "pl_int");
        this.a.h(evu.class, "cfg_a");
        this.a.h(ewm.class, "cfg_c");
        this.a.h(ewq.class, "cfg_h");
        this.a.g(ewa.class, evo.b);
        this.a.h(ewa.class, "bres");
        this.a.h(evz.class, "brer");
        this.a.h(aado.class, "brns");
        this.a.h(aadn.class, "brnr");
        this.a.h(aadm.class, "brps");
        this.a.h(aadl.class, "brpe");
        this.a.h(ewb.class, "br_e");
        this.a.h(ewl.class, "br_s");
        this.a.h(ewg.class, "br_r");
        this.a.h(ewc.class, "ol");
        this.a.h(evy.class, "aa");
        this.a.h(exe.class, "ui_l");
        this.a.h(exd.class, "pl_int");
        this.a.h(ewu.class, "rurl_s");
        this.a.h(ewt.class, "rurl_r");
        this.a.h(aadu.class, "rurlps");
        this.a.h(aadt.class, "rurlpe");
        this.a.h(ewh.class, "br_ld");
        this.a.h(ewi.class, "brr_e");
        this.a.h(ewk.class, "brr_i");
        this.a.h(ewj.class, "brr_ius");
        this.a.h(ewr.class, "ne_r");
        this.a.h(exc.class, "sr_ui");
        this.a.h(ewz.class, "sr_pa");
        this.a.h(exa.class, "sr_s");
        this.a.h(ewy.class, "sr_r");
        this.a.h(ewv.class, "sr_e");
        this.a.h(ewx.class, "sf_i");
        this.a.h(exb.class, "sr_p");
        this.a.h(aadw.class, "ssns");
        this.a.h(aadv.class, "ssnr");
        this.a.h(ewp.class, "gu_s");
        this.a.h(ewo.class, "gu_r");
        this.a.h(ewn.class, "gu_e");
        acvp acvpVar = this.a;
        acvpVar.h(ajpt.class, "thmon_s");
        acvpVar.h(ajps.class, "thmon_e");
        acvpVar.h(ajpr.class, "thmon_s");
        acvpVar.h(ajpq.class, "thmon_e");
        acvpVar.i(ajpx.class, new ajpl());
        acvpVar.i(ajpw.class, new ajpl());
        acvpVar.i(ajpv.class, new ajpl());
        acvpVar.i(ajpu.class, new ajpl());
        acvpVar.g(ajpx.class, evo.r);
        this.a.h(exf.class, "uiwwa_c");
        this.a.h(exj.class, "uiwwa_s");
        this.a.h(exi.class, "uiwwa_r");
        this.a.h(exg.class, "uiwwa_pr");
        this.a.h(exh.class, "uiwwa_e");
        this.a.h(ewd.class, "uibf_c");
        this.a.h(ewf.class, "uibf_s");
        this.a.h(ewe.class, "uibf_r");
        this.a.h(ews.class, "uipb_gld");
        this.a.h(eww.class, "uisf_r");
        this.a.h(eub.class, "im_d");
        this.a.h(eub.class, "im_s");
        this.a.h(eua.class, "im_po");
        this.a.h(etz.class, "im_pl");
        this.a.h(ety.class, "im_vs");
        this.a.h(eul.class, "js_is");
        this.a.h(euf.class, "js_if");
        this.a.h(euk.class, "js_ebs");
        this.a.h(euj.class, "js_ebf");
        this.a.h(eui.class, "js_ebc");
        this.a.h(euh.class, "js_eas");
        this.a.h(eug.class, "js_eaf");
        this.a.g(aaoe.class, new evq());
        this.b.a(this, aaoe.class, evsVar);
        this.a.g(evk.class, new evq(2));
        this.a.g(actu.class, evo.a);
        acvp acvpVar2 = this.a;
        acvpVar2.h(ahgt.class, "pl_i");
        acvpVar2.h(ahgu.class, "pl_r");
        acvpVar2.h(ahgy.class, "ps_s");
        acvpVar2.h(ahgx.class, "ps_r");
        acvpVar2.h(aads.class, "psns");
        acvpVar2.h(aadr.class, "psnr");
        acvpVar2.h(aadq.class, "psps");
        acvpVar2.h(aadp.class, "pspe");
        acvpVar2.h(ahhe.class, "wn_s");
        acvpVar2.h(ahhd.class, "wn_r");
        acvpVar2.h(aady.class, "wnps");
        acvpVar2.h(aadx.class, "wnpe");
        acvpVar2.h(ahhc.class, "sw_s");
        acvpVar2.h(ahhb.class, "sw_r");
        acvpVar2.h(ahgo.class, "pc");
        acvpVar2.h(ahgz.class, "pl_s");
        acvpVar2.h(ahgv.class, "pbs");
        acvpVar2.h(ahgp.class, "pbi");
        acvpVar2.h(ahgw.class, "pbu");
        acvpVar2.h(ahgr.class, "pbp");
        acvpVar2.h(ahha.class, "pl_int");
        acvpVar2.h(aikd.class, "pl_ex");
        acvpVar2.h(ahgq.class, "pl_int");
        acvpVar2.g(ahgx.class, evo.m);
        acvpVar2.i(ahhw.class, ahfr.a);
        acvpVar2.g(ahhw.class, evo.o);
        acvpVar2.g(aikd.class, evo.q);
        acvpVar2.g(aiin.class, evo.p);
        acvpVar2.g(aesr.class, evo.k);
        acvpVar2.g(ahgz.class, evo.n);
        acvpVar2.g(ahgv.class, evo.l);
        afms.a(acvpVar2);
        aecq.a(acvpVar2);
        acvp acvpVar3 = this.a;
        acvpVar3.h(wxz.class, "ab_s");
        acvpVar3.h(wxy.class, "ab_r");
        acvpVar3.h(wyb.class, "ad_bl");
        acvpVar3.h(wxt.class, "ad_ba");
        acvpVar3.h(wxw.class, "msti");
        acvpVar3.h(wxv.class, "mstr");
        acvpVar3.h(wxx.class, "ad_bp");
        acvpVar3.h(wyd.class, "ads_s");
        acvpVar3.h(wyc.class, "ads_e");
        acvpVar3.h(wxu.class, "ab_cre");
        acvpVar3.h(wye.class, "ad_pre");
        acvpVar3.h(wyq.class, "pacf_ss");
        acvpVar3.h(wyp.class, "pacf_sb");
        acvpVar3.h(wyr.class, "pacf_ssc");
        acvpVar3.h(wyi.class, "pacf_ls");
        acvpVar3.h(wyh.class, "pacf_lb");
        acvpVar3.h(wyj.class, "pacf_lsc");
        acvpVar3.h(wys.class, "ad_vr");
        acvpVar3.h(wyn.class, "pb_s");
        acvpVar3.h(wyl.class, "pb_c");
        acvpVar3.h(wyk.class, "pb_ca");
        acvpVar3.h(wym.class, "pb_f");
        acvpVar3.i(wyv.class, new ajpl(1));
        acvpVar3.g(wyv.class, new evq(3));
        acvpVar3.g(wxr.class, new evq(4));
        acvpVar3.g(ahhw.class, evo.c);
        acvpVar3.g(wya.class, new evq(5));
        acvpVar3.g(wyf.class, new evq(6));
        acvpVar3.g(wxo.class, new evq(7));
        acvpVar3.g(wyn.class, new evq(8));
        acvpVar3.g(wyl.class, new evq(9));
        acvpVar3.g(wym.class, new evq(10));
        eun eunVar = new eun(this.a);
        if (!eunVar.a) {
            acvn d2 = eunVar.b.d(euy.class, new eud(2), new eum(eunVar));
            d2.c(euo.class);
            d2.c(eup.class);
            d2.b(euw.class);
            d2.b(euq.class);
            d2.b(eux.class);
            eunVar.b.h(euy.class, "ytro_s");
            eunVar.b.h(eur.class, "purb_c");
            eunVar.b.h(euv.class, "walti_s");
            eunVar.b.h(eus.class, "walnt_s");
            eunVar.b.h(eut.class, "walpt_s");
            eunVar.b.h(euu.class, "wali_s");
            eunVar.b.h(euo.class, "wali_c");
            eunVar.b.h(euq.class, "waltr_f");
            eunVar.b.h(euw.class, "waltr_s");
            eunVar.b.h(eup.class, "waltr_c");
            eunVar.b.h(eux.class, "ytrmsp_s");
            eunVar.a = true;
        }
        acvp acvpVar4 = this.a;
        acvpVar4.h(aieh.class, "pft_i");
        acvpVar4.h(aieg.class, "pbf_c");
    }
}
