package defpackage;

import android.content.Context;
import android.text.format.DateFormat;
import com.google.android.youtube.R;
import com.google.protos.youtube.api.innertube.ShowNoConnectionBarCommandOuterClass$ShowNoConnectionBarCommand;
import com.google.protos.youtube.api.innertube.SlimVideoMetadataRendererOuterClass;
import com.google.protos.youtube.api.innertube.SlimVideoMetadataSectionRendererOuterClass;
import java.util.Date;
/* compiled from: PG */
/* renamed from: jmu  reason: default package */
/* loaded from: classes3.dex */
public final class jmu extends jlq {
    private final Context a;

    public jmu(Context context) {
        super(agqo.class, auxn.class);
        this.a = context;
    }

    private static auwy a(arhr arhrVar, String str) {
        aopc aopcVar = (aopc) apoj.a.createBuilder();
        arag g = ajgl.g(str);
        aopcVar.copyOnWrite();
        apoj apojVar = (apoj) aopcVar.instance;
        g.getClass();
        apojVar.i = g;
        apojVar.b |= 256;
        aopc aopcVar2 = (aopc) arhs.a.createBuilder();
        aopcVar2.copyOnWrite();
        arhs arhsVar = (arhs) aopcVar2.instance;
        arhsVar.c = arhrVar.pS;
        arhsVar.b |= 1;
        aopcVar.copyOnWrite();
        apoj apojVar2 = (apoj) aopcVar.instance;
        arhs arhsVar2 = (arhs) aopcVar2.mo39build();
        arhsVar2.getClass();
        apojVar2.g = arhsVar2;
        apojVar2.b |= 32;
        g(aopcVar);
        aopa createBuilder = auwy.a.createBuilder();
        aopa createBuilder2 = apok.a.createBuilder();
        createBuilder2.copyOnWrite();
        apok apokVar = (apok) createBuilder2.instance;
        apoj apojVar3 = (apoj) aopcVar.mo39build();
        apojVar3.getClass();
        apokVar.c = apojVar3;
        apokVar.b |= 1;
        createBuilder.copyOnWrite();
        auwy auwyVar = (auwy) createBuilder.instance;
        apok apokVar2 = (apok) createBuilder2.mo39build();
        apokVar2.getClass();
        auwyVar.f = apokVar2;
        auwyVar.b |= 8;
        return (auwy) createBuilder.mo39build();
    }

    private static auwz f(auwy auwyVar) {
        aopa createBuilder = auwz.a.createBuilder();
        createBuilder.copyOnWrite();
        auwz auwzVar = (auwz) createBuilder.instance;
        auwyVar.getClass();
        auwzVar.c = auwyVar;
        auwzVar.b = 124608017;
        return (auwz) createBuilder.mo39build();
    }

    private static void g(aopc aopcVar) {
        aopa createBuilder = avgj.a.createBuilder();
        avgg avggVar = avgg.THEME_ATTRIBUTE_ICON_DISABLED;
        createBuilder.copyOnWrite();
        avgj avgjVar = (avgj) createBuilder.instance;
        avgjVar.d = avggVar.ai;
        avgjVar.b |= 2;
        avgg avggVar2 = avgg.THEME_ATTRIBUTE_TEXT_DISABLED;
        createBuilder.copyOnWrite();
        avgj avgjVar2 = (avgj) createBuilder.instance;
        avgjVar2.c = avggVar2.ai;
        avgjVar2.b |= 1;
        aopcVar.copyOnWrite();
        apoj apojVar = (apoj) aopcVar.instance;
        avgj avgjVar3 = (avgj) createBuilder.mo39build();
        apoj apojVar2 = apoj.a;
        avgjVar3.getClass();
        apojVar.d = avgjVar3;
        apojVar.c = 20;
        aopc aopcVar2 = (aopc) apzg.a.createBuilder();
        aopcVar2.e(ShowNoConnectionBarCommandOuterClass$ShowNoConnectionBarCommand.showNoConnectionBarCommand, ShowNoConnectionBarCommandOuterClass$ShowNoConnectionBarCommand.a);
        aopcVar.copyOnWrite();
        apoj apojVar3 = (apoj) aopcVar.instance;
        apzg apzgVar = (apzg) aopcVar2.mo39build();
        apzgVar.getClass();
        apojVar3.n = apzgVar;
        apojVar3.b |= 8192;
    }

    @Override // defpackage.jmf
    public final /* bridge */ /* synthetic */ Object b(Object obj, amup amupVar) {
        agqo agqoVar = (agqo) obj;
        aopc aopcVar = (aopc) auxn.a.createBuilder();
        String f = agqoVar.f();
        aopcVar.copyOnWrite();
        auxn auxnVar = (auxn) aopcVar.instance;
        f.getClass();
        auxnVar.b |= 1;
        auxnVar.d = f;
        String string = this.a.getString(R.string.video_views, Long.valueOf(agqoVar.b()));
        aopc aopcVar2 = (aopc) aunb.a.createBuilder();
        aopg aopgVar = SlimVideoMetadataSectionRendererOuterClass.slimVideoInformationRenderer;
        aopa createBuilder = auxm.a.createBuilder();
        arag g = ajgl.g(agqoVar.j());
        createBuilder.copyOnWrite();
        auxm auxmVar = (auxm) createBuilder.instance;
        g.getClass();
        auxmVar.c = g;
        auxmVar.b |= 1;
        arag g2 = ajgl.g(string);
        createBuilder.copyOnWrite();
        auxm auxmVar2 = (auxm) createBuilder.instance;
        g2.getClass();
        auxmVar2.d = g2;
        auxmVar2.b |= 2;
        arag g3 = ajgl.g(string);
        createBuilder.copyOnWrite();
        auxm auxmVar3 = (auxm) createBuilder.instance;
        g3.getClass();
        auxmVar3.e = g3;
        auxmVar3.b |= 4;
        aopcVar2.e(aopgVar, (auxm) createBuilder.mo39build());
        aopcVar.co((aunb) aopcVar2.mo39build());
        Context context = this.a;
        aopa createBuilder2 = auxj.a.createBuilder();
        createBuilder2.aP(f(a(arhr.LIKE, agqoVar.h())));
        createBuilder2.aP(f(a(arhr.DISLIKE, agqoVar.e())));
        aopc aopcVar3 = (aopc) apoj.a.createBuilder();
        aopc aopcVar4 = (aopc) arhs.a.createBuilder();
        arhr arhrVar = arhr.SHARE_ARROW;
        aopcVar4.copyOnWrite();
        arhs arhsVar = (arhs) aopcVar4.instance;
        arhsVar.c = arhrVar.pS;
        arhsVar.b |= 1;
        aopcVar3.copyOnWrite();
        apoj apojVar = (apoj) aopcVar3.instance;
        arhs arhsVar2 = (arhs) aopcVar4.mo39build();
        arhsVar2.getClass();
        apojVar.g = arhsVar2;
        apojVar.b |= 32;
        arag g4 = ajgl.g(context.getString(R.string.offline_share_button_text));
        aopcVar3.copyOnWrite();
        apoj apojVar2 = (apoj) aopcVar3.instance;
        g4.getClass();
        apojVar2.i = g4;
        apojVar2.b |= 256;
        g(aopcVar3);
        aopa createBuilder3 = auwy.a.createBuilder();
        aopa createBuilder4 = apok.a.createBuilder();
        createBuilder4.copyOnWrite();
        apok apokVar = (apok) createBuilder4.instance;
        apoj apojVar3 = (apoj) aopcVar3.mo39build();
        apojVar3.getClass();
        apokVar.c = apojVar3;
        apokVar.b |= 1;
        createBuilder3.copyOnWrite();
        auwy auwyVar = (auwy) createBuilder3.instance;
        apok apokVar2 = (apok) createBuilder4.mo39build();
        apokVar2.getClass();
        auwyVar.f = apokVar2;
        auwyVar.b |= 8;
        createBuilder2.aP(f((auwy) createBuilder3.mo39build()));
        aopa createBuilder5 = auwy.a.createBuilder();
        aopa createBuilder6 = apok.a.createBuilder();
        apoj apojVar4 = apoj.a;
        createBuilder6.copyOnWrite();
        apok apokVar3 = (apok) createBuilder6.instance;
        apojVar4.getClass();
        apokVar3.c = apojVar4;
        apokVar3.b |= 1;
        createBuilder5.copyOnWrite();
        auwy auwyVar2 = (auwy) createBuilder5.instance;
        apok apokVar4 = (apok) createBuilder6.mo39build();
        apokVar4.getClass();
        auwyVar2.f = apokVar4;
        auwyVar2.b |= 8;
        createBuilder5.copyOnWrite();
        auwy.a((auwy) createBuilder5.instance);
        arag g5 = ajgl.g(context.getString(R.string.offline_button_progress_text));
        createBuilder5.copyOnWrite();
        auwy auwyVar3 = (auwy) createBuilder5.instance;
        g5.getClass();
        auwyVar3.d = g5;
        auwyVar3.b |= 2;
        arag g6 = ajgl.g(context.getString(R.string.offline_button_complete_text));
        createBuilder5.copyOnWrite();
        auwy auwyVar4 = (auwy) createBuilder5.instance;
        g6.getClass();
        auwyVar4.e = g6;
        auwyVar4.b |= 4;
        createBuilder2.aP(f((auwy) createBuilder5.mo39build()));
        aopc aopcVar5 = (aopc) apoj.a.createBuilder();
        aopc aopcVar6 = (aopc) arhs.a.createBuilder();
        arhr arhrVar2 = arhr.ADD_TO_PLAYLIST;
        aopcVar6.copyOnWrite();
        arhs arhsVar3 = (arhs) aopcVar6.instance;
        arhsVar3.c = arhrVar2.pS;
        arhsVar3.b |= 1;
        aopcVar5.copyOnWrite();
        apoj apojVar5 = (apoj) aopcVar5.instance;
        arhs arhsVar4 = (arhs) aopcVar6.mo39build();
        arhsVar4.getClass();
        apojVar5.g = arhsVar4;
        apojVar5.b |= 32;
        arag g7 = ajgl.g(context.getString(R.string.offline_save_button_text));
        aopcVar5.copyOnWrite();
        apoj apojVar6 = (apoj) aopcVar5.instance;
        g7.getClass();
        apojVar6.i = g7;
        apojVar6.b |= 256;
        g(aopcVar5);
        aopa createBuilder7 = auwy.a.createBuilder();
        aopa createBuilder8 = apok.a.createBuilder();
        createBuilder8.copyOnWrite();
        apok apokVar5 = (apok) createBuilder8.instance;
        apoj apojVar7 = (apoj) aopcVar5.mo39build();
        apojVar7.getClass();
        apokVar5.c = apojVar7;
        apokVar5.b |= 1;
        createBuilder7.copyOnWrite();
        auwy auwyVar5 = (auwy) createBuilder7.instance;
        apok apokVar6 = (apok) createBuilder8.mo39build();
        apokVar6.getClass();
        auwyVar5.f = apokVar6;
        auwyVar5.b |= 8;
        createBuilder2.aP(f((auwy) createBuilder7.mo39build()));
        aopc aopcVar7 = (aopc) aunb.a.createBuilder();
        aopcVar7.e(SlimVideoMetadataSectionRendererOuterClass.slimVideoActionBarRenderer, (auxj) createBuilder2.mo39build());
        aopcVar.co((aunb) aopcVar7.mo39build());
        aopa createBuilder9 = auxc.a.createBuilder();
        agqa agqaVar = agqoVar.a;
        if (agqaVar != null) {
            arag g8 = ajgl.g(agqaVar.b);
            createBuilder9.copyOnWrite();
            auxc auxcVar = (auxc) createBuilder9.instance;
            g8.getClass();
            auxcVar.d = g8;
            auxcVar.b |= 2;
            avhn e = agqaVar.c.e();
            createBuilder9.copyOnWrite();
            auxc auxcVar2 = (auxc) createBuilder9.instance;
            e.getClass();
            auxcVar2.c = e;
            auxcVar2.b |= 1;
        }
        aopc aopcVar8 = (aopc) aunb.a.createBuilder();
        aopcVar8.e(SlimVideoMetadataRendererOuterClass.slimOwnerRenderer, (auxc) createBuilder9.mo39build());
        aopcVar.co((aunb) aopcVar8.mo39build());
        Context context2 = this.a;
        aopc aopcVar9 = (aopc) arag.a.createBuilder();
        Date date = agqoVar.d;
        aopc aopcVar10 = (aopc) arai.a.createBuilder();
        aopcVar10.copyOnWrite();
        arai.a((arai) aopcVar10.instance);
        String format = DateFormat.getLongDateFormat(context2).format(agqoVar.d);
        aopcVar10.copyOnWrite();
        arai araiVar = (arai) aopcVar10.instance;
        format.getClass();
        araiVar.b |= 1;
        araiVar.c = format;
        aopcVar9.cs(aopcVar10);
        aopa createBuilder10 = auxk.a.createBuilder();
        createBuilder10.copyOnWrite();
        auxk auxkVar = (auxk) createBuilder10.instance;
        arag aragVar = (arag) aopcVar9.mo39build();
        aragVar.getClass();
        auxkVar.c = aragVar;
        auxkVar.b |= 1;
        atsl atslVar = agqoVar.e;
        if ((atslVar.b & 512) != 0) {
            arag aragVar2 = atslVar.k;
            if (aragVar2 == null) {
                aragVar2 = arag.a;
            }
            createBuilder10.copyOnWrite();
            auxk auxkVar2 = (auxk) createBuilder10.instance;
            aragVar2.getClass();
            auxkVar2.d = aragVar2;
            auxkVar2.b |= 2;
        }
        aopc aopcVar11 = (aopc) aunb.a.createBuilder();
        aopcVar11.e(SlimVideoMetadataSectionRendererOuterClass.slimVideoDescriptionRenderer, (auxk) createBuilder10.mo39build());
        aopcVar.co((aunb) aopcVar11.mo39build());
        aopcVar.e(auxh.b, true);
        return (auxn) aopcVar.mo39build();
    }
}
