package defpackage;
/* compiled from: PG */
/* renamed from: achc  reason: default package */
/* loaded from: classes2.dex */
public enum achc {
    AR_CALIBRATOR(true),
    AR_LIGHTHOUSE(true),
    AR_PLACE_DISCOVERY(true),
    AR_WALKING(true),
    ACCOUNT_PARTICLE_MENU,
    BUSINESS_PLACE_PAGE,
    BUSINESS_PLACE_PAGE_FULLSCREEN,
    CARD_UI_ACTION,
    DIRECTION_PAGE,
    DISCOVERY_CATSEARCH_LIST,
    DISCOVERY_EXPERIENCE_SHEET,
    DISCOVERY_SOCIAL_PLANNING,
    DRAWER_MENU,
    EVENT_SHEET,
    EVENTS_UGC,
    EXPERIENCE_CATEGORICAL_LIST,
    FRIENDS_LIST,
    GEOCODE_PAGE,
    GEOCODE_PAGE_FULLSCREEN,
    HASHTAG_SEARCH_PAGE,
    HOME_SCREEN_DRIVING_TAB_FEEDBACK_CARD,
    HOME_SCREEN_EXPLORE_TAB_FEEDBACK_CARD,
    HOME_SCREEN_CONTRIBUTE_TAB,
    INBOX,
    LD_FOR_YOU_CARD(true),
    LD_FOR_YOU_PAGE(true),
    LOCAL_DISCOVERY,
    LOCATION_QUALITY_FEEDBACK,
    MAP,
    MERCHANT_BIZ_INFO,
    MERCHANT_INFO_UPDATE,
    MERCHANT_PERFORMANCE,
    NOTIFICATION,
    PLACE_PICKER,
    PLACE_PICKER_SUGGEST,
    RAP_DISAMBIGUATION_MENU,
    RIDDLER_QUESTION,
    RMI_FEATURE_PICKER,
    SETTINGS_MENU,
    STREETVIEW,
    SUGGEST_PAGE,
    TIMELINE,
    VISUAL_EXPLORE_IMMERSIVE,
    DEALS_CAROUSEL,
    MESSAGES,
    YOUR_EXPLORE_CARD(true);
    
    public final boolean U;

    achc() {
        this(false);
    }

    achc(boolean z) {
        this.U = z;
    }
}
