package defpackage;
/* compiled from: PG */
/* renamed from: acnr  reason: default package */
/* loaded from: classes.dex */
public enum acnr implements cqku {
    MIN_TAB_OVERFLOW,
    ON_TAB_SELECTED_LISTENER,
    SELECTED_INDICATOR_COLOR,
    SELECTED_INDICATOR_DRAWABLE,
    SELECTED_INDICATOR_FULL_WIDTH,
    SELECTED_INDICATOR_HEIGHT,
    SLIDING_PADDING,
    SLIDING_TAB_POSITION,
    TABS_FULL_WIDTH,
    SELECTED_INDICATOR_MIN_WIDTH,
    SELECTED_INDICATOR_PADDING_START,
    SELECTED_INDICATOR_PADDING_END,
    SELECTED_INDICATOR_CENTER_ON_TITLE
}
