package defpackage;
/* compiled from: PG */
/* renamed from: akez  reason: default package */
/* loaded from: classes2.dex */
public enum akez {
    UNKNOWN,
    NOTIFICATION,
    USER_TRIGERRED_SIDEMENU,
    USER_TRIGERRED_CAR,
    USER_TRIGERRED_PERSONAL_PLACES,
    PERSONAL_PLACES_AFTER_SYNC,
    ERROR_IN_INITIALIZATION,
    GAIA_LOGIN_DISABLED_IN_CLIENT_PARAMS,
    GAIA_LOGIN_DISABLED_IN_APP_START,
    DASHER_ADMIN_DISABLED,
    ACCOUNT_REMOVED,
    NAV_GO_AUTOLOGIN_NO_IDENTIFIER,
    NAV_GO_AUTOLOGIN_BAD_IDENTIFIER,
    NO_GOOGLE_ACCOUNT_AVAILABLE,
    UNAUTHENTICATED
}
