package defpackage;
/* compiled from: PG */
/* renamed from: axxx  reason: default package */
/* loaded from: classes3.dex */
enum axxx {
    DEFAULT(dmqc.LEGEND_STYLE_PERSONAL_PLACES_LABEL_LAYOUT, dmqc.LEGEND_STYLE_POI_CUSTOM, dmqc.LEGEND_STYLE_PERSONAL_PLACES_TEXT_TITLE, dmqc.LEGEND_STYLE_PERSONAL_PLACES_TEXT_SUBTITLE),
    HOME(dmqc.LEGEND_STYLE_HOME_LABEL_LAYOUT, dmqc.LEGEND_STYLE_HOME, dmqc.LEGEND_STYLE_HOME_TEXT_TITLE, null),
    WORK(dmqc.LEGEND_STYLE_WORK_LABEL_LAYOUT, dmqc.LEGEND_STYLE_WORK, dmqc.LEGEND_STYLE_WORK_TEXT_TITLE, null),
    FAVORITES(dmqc.LEGEND_STYLE_POI_FAVORITES_LABEL_LAYOUT, dmqc.LEGEND_STYLE_POI_FAVORITES, dmqc.LEGEND_STYLE_POI_FAVORITES_TEXT_TITLE, dmqc.LEGEND_STYLE_POI_FAVORITES_TEXT_SUBTITLE),
    WANT_TO_GO(dmqc.LEGEND_STYLE_POI_WANT_TO_GO_LABEL_LAYOUT, dmqc.LEGEND_STYLE_POI_WANT_TO_GO, dmqc.LEGEND_STYLE_POI_WANT_TO_GO_TEXT_TITLE, dmqc.LEGEND_STYLE_POI_WANT_TO_GO_TEXT_SUBTITLE),
    STAR(dmqc.LEGEND_STYLE_STAR_LABEL_LAYOUT, dmqc.LEGEND_STYLE_STAR, dmqc.LEGEND_STYLE_STAR_TEXT_TITLE, dmqc.LEGEND_STYLE_STAR_TEXT_SUBTITLE),
    CUSTOM(dmqc.LEGEND_STYLE_POI_CUSTOM_LABEL_LAYOUT, dmqc.LEGEND_STYLE_POI_CUSTOM, dmqc.LEGEND_STYLE_POI_CUSTOM_TEXT_TITLE, dmqc.LEGEND_STYLE_POI_CUSTOM_TEXT_SUBTITLE),
    CONTACT(dmqc.LEGEND_STYLE_POI_CONTACT_LABEL_LAYOUT, dmqc.LEGEND_STYLE_POI_CONTACT, dmqc.LEGEND_STYLE_POI_CONTACT_TEXT_TITLE, null),
    NICKNAME(dmqc.LEGEND_STYLE_POI_NICKNAME_LABEL_LAYOUT, dmqc.LEGEND_STYLE_POI_NICKNAME, dmqc.LEGEND_STYLE_POI_NICKNAME_TEXT_TITLE, null);
    
    public final dmqc j;
    public final dmqc k;
    public final dmqc l;
    public final dmqc m;

    axxx(dmqc dmqcVar, dmqc dmqcVar2, dmqc dmqcVar3, @dzsi dmqc dmqcVar4) {
        this.j = dmqcVar;
        this.k = dmqcVar2;
        this.l = dmqcVar3;
        this.m = dmqcVar4 == null ? dmqc.LEGEND_STYLE_PERSONAL_PLACES_TEXT_SUBTITLE : dmqcVar4;
    }
}
