package defpackage;
/* compiled from: PG */
/* renamed from: bvjk  reason: default package */
/* loaded from: classes.dex */
public class bvjk {
    public static final bvjk A;
    public static final bvjk B;
    public static final bvjk C;
    public static final bvjk D;
    public static final bvjk E;
    public static final bvjk F;
    public static final bvjk G;
    public static final bvjk H;
    public static final bvjk I;
    @Deprecated
    static final bvjk J;
    public static final bvjk K;
    public static final bvjk L;
    public static final bvjk M;
    public static final bvjk N;
    public static final bvjk O;
    public static final bvjk P;
    public static final bvjk Q;
    public static final bvjk R;
    public static final bvjk S;
    public static final bvjk T;
    public static final bvjk U;
    public static final bvjk V;
    public static final bvjk W;
    public static final bvjk X;
    public static final bvjk Y;
    public static final bvjk Z;
    static final bvjk a;
    public static final bvjk aA;
    public static final bvjk aB;
    public static final bvjk aC;
    public static final bvjk aD;
    public static final bvjk aE;
    public static final bvjk aF;
    public static final bvjk aG;
    public static final bvjk aH;
    public static final bvjk aI;
    public static final bvjk aJ;
    public static final bvjk aK;
    public static final bvjk aL;
    public static final bvjk aM;
    public static final bvjk aN;
    public static final bvjk aO;
    public static final bvjk aP;
    public static final bvjk aQ;
    public static final bvjk aR;
    public static final bvjk aS;
    public static final bvjk aT;
    public static final bvjk aU;
    public static final bvjk aV;
    public static final bvjk aW;
    @Deprecated
    public static final bvjk aX;
    @Deprecated
    public static final bvjk aY;
    @Deprecated
    public static final bvjk aZ;
    public static final bvjk aa;
    public static final bvjk ab;
    public static final bvjk ac;
    public static final bvjk ad;
    @Deprecated
    public static final bvjk ae;
    public static final bvjk af;
    public static final bvjk ag;
    public static final bvjk ah;
    @Deprecated
    public static final bvjk ai;
    public static final bvjk aj;
    public static final bvjk ak;
    public static final bvjk al;
    public static final bvjk am;
    public static final bvjk an;
    public static final bvjk ao;
    public static final bvjk ap;
    public static final bvjk aq;
    public static final bvjk ar;
    public static final bvjk as;
    public static final bvjk at;
    public static final bvjk au;
    public static final bvjk av;
    public static final bvjk aw;
    public static final bvjk ax;
    public static final bvjk ay;
    public static final bvjk az;
    public static final bvjl b;
    @Deprecated
    public static final bvjk bA;
    public static final bvjk bB;
    public static final bvjk bC;
    public static final bvjk bD;
    public static final bvjk bE;
    public static final bvjk bF;
    public static final bvjk bG;
    public static final bvjk bH;
    public static final bvjk bI;
    public static final bvjk bJ;
    public static final bvjk bK;
    public static final bvjk bL;
    public static final bvjk bM;
    public static final bvjk bN;
    public static final bvjk bO;
    public static final bvjk bP;
    public static final bvjk bQ;
    public static final bvjk bR;
    public static final bvjk bS;
    @Deprecated
    public static final bvjk bT;
    public static final bvjk bU;
    public static final bvjk bV;
    public static final bvjk bW;
    public static final bvjk bX;
    public static final bvjk bY;
    public static final bvjk bZ;
    @Deprecated
    public static final bvjk ba;
    public static final bvjk bb;
    @Deprecated
    public static final bvjk bc;
    public static final bvjk bd;
    public static final bvjk be;
    public static final bvjk bf;
    public static final bvjk bg;
    public static final bvjk bh;
    public static final bvjk bi;
    public static final bvjk bj;
    public static final bvjk bk;
    public static final bvjk bl;
    public static final bvjk bm;
    public static final bvjk bn;
    public static final bvjk bo;
    public static final bvjk bp;
    public static final bvjk bq;
    public static final bvjk br;
    public static final bvjk bs;
    public static final bvjk bt;
    public static final bvjk bu;
    public static final bvjk bv;
    public static final bvjk bw;
    public static final bvjk bx;
    @Deprecated
    public static final bvjk by;
    @Deprecated
    public static final bvjk bz;
    public static final bvjp c;
    public static final bvjk cA;
    public static final bvjk cB;
    public static final bvjk cC;
    public static final bvjk cD;
    public static final bvjk cE;
    public static final bvjk cF;
    public static final bvjk cG;
    @Deprecated
    public static final bvjk cH;
    public static final bvjk cI;
    public static final bvjk cJ;
    public static final bvjk cK;
    public static final bvjk cL;
    public static final bvjk cM;
    public static final bvjk cN;
    public static final bvjk cO;
    public static final bvjk cP;
    public static final bvjk cQ;
    public static final bvjk cR;
    @Deprecated
    public static final bvjk cS;
    public static final bvjk cT;
    public static final bvjk cU;
    public static final bvjk cV;
    public static final bvjk cW;
    public static final bvjk cX;
    @Deprecated
    public static final bvjk cY;
    public static final bvjk cZ;
    public static final bvjk ca;
    public static final bvjk cb;
    public static final bvjk cc;
    public static final bvjk cd;
    public static final bvjk ce;
    public static final bvjk cf;
    public static final bvjk cg;
    public static final bvjk ch;
    public static final bvjk ci;
    @Deprecated
    static final bvjk cj;
    @Deprecated
    static final bvjk ck;
    @Deprecated
    static final bvjk cl;
    @Deprecated
    static final bvjk cm;
    public static final bvjk cn;
    public static final bvjk co;
    public static final bvjk cp;
    public static final bvjk cq;
    @Deprecated
    public static final bvjk cr;
    public static final bvjk cs;
    public static final bvjk ct;
    public static final bvjk cu;
    public static final bvjk cv;
    public static final bvjk cw;
    public static final bvjk cx;
    public static final bvjk cy;
    public static final bvjk cz;
    public static final bvjk d;
    public static final bvjk dA;
    @Deprecated
    public static final bvjk dB;
    public static final bvjk dC;
    public static final bvjk dD;
    public static final bvjk dE;
    public static final bvjk dF;
    public static final bvjk dG;
    public static final bvjk dH;
    @Deprecated
    public static final bvjk dI;
    public static final bvjk dJ;
    public static final bvjk dK;
    public static final bvjk dL;
    @Deprecated
    public static final bvjk dM;
    public static final bvjk dN;
    public static final bvjk dO;
    public static final bvjk dP;
    public static final bvjk dQ;
    public static final bvjk dR;
    public static final bvjk dS;
    public static final bvjk dT;
    public static final bvjk dU;
    public static final bvjk dV;
    public static final bvjk dW;
    public static final bvjk dX;
    public static final bvjk dY;
    public static final bvjk dZ;
    public static final bvjk da;
    public static final bvjk db;
    public static final bvjk dc;
    public static final bvjk dd;
    public static final bvjk de;
    public static final bvjk df;
    public static final bvjk dg;
    @Deprecated
    public static final bvjk dh;
    public static final bvjk di;
    public static final bvjk dj;
    public static final bvjk dk;
    public static final bvjk dl;
    public static final bvjk dm;
    public static final bvjk dn;

    /* renamed from: do  reason: not valid java name */
    public static final bvjk f0do;
    public static final bvjk dp;
    @Deprecated
    public static final bvjk dq;
    @Deprecated
    public static final bvjk dr;
    public static final bvjk ds;
    public static final bvjk dt;
    @Deprecated
    public static final bvjk du;
    @Deprecated
    public static final bvjk dv;
    @Deprecated
    public static final bvjk dw;
    public static final bvjk dx;
    @Deprecated
    public static final bvjk dy;
    @Deprecated
    public static final bvjk dz;
    public static final bvjk e;
    public static final bvjk eA;
    public static final bvjk eB;
    public static final bvjk eC;
    public static final bvjk eD;
    public static final bvjk eE;
    public static final bvjk eF;
    public static final bvjk eG;
    public static final bvjk eH;
    public static final bvjk eI;
    public static final bvjk eJ;
    public static final bvjk eK;
    public static final bvjk eL;
    public static final bvjk eM;
    public static final bvjk eN;
    public static final bvjk eO;
    public static final bvjk eP;
    public static final bvjk eQ;
    public static final bvjk eR;
    public static final bvjk eS;
    public static final bvjk eT;
    public static final bvjk eU;
    public static final bvjk eV;
    public static final bvjk eW;
    public static final bvjk eX;
    public static final bvjk eY;
    public static final bvjk eZ;
    public static final bvjk ea;
    public static final bvjk eb;
    public static final bvjk ec;
    public static final bvjk ed;
    public static final bvjk ee;
    public static final bvjk ef;
    public static final bvjk eg;
    public static final bvjk eh;
    public static final bvjk ei;
    public static final bvjk ej;
    public static final bvjk ek;
    public static final bvjk el;
    public static final bvjk em;
    public static final bvjk en;
    public static final bvjk eo;
    public static final bvjk ep;
    public static final bvjk eq;
    public static final bvjk er;
    public static final bvjk es;
    public static final bvjk et;
    public static final bvjk eu;
    public static final bvjk ev;
    public static final bvjk ew;
    @Deprecated
    public static final bvjk ex;
    public static final bvjk ey;
    public static final bvjk ez;
    public static final bvjk f;
    @Deprecated
    public static final bvjk fA;
    public static final bvjk fB;
    @Deprecated
    static final bvjk fC;
    @Deprecated
    static final bvjk fD;
    @Deprecated
    static final bvjk fE;
    @Deprecated
    static final bvjk fF;
    @Deprecated
    public static final bvjk fG;
    public static final bvjk fH;
    public static final bvjk fI;
    public static final bvjk fJ;
    @Deprecated
    public static final bvjk fK;
    @Deprecated
    public static final bvjk fL;
    public static final bvjk fM;
    public static final bvjk fN;
    public static final bvjk fO;
    public static final bvjk fP;
    public static final bvjk fQ;
    @Deprecated
    public static final bvjk fR;
    public static final bvjk fS;
    public static final bvjk fT;
    public static final bvjk fU;
    public static final bvjk fV;
    public static final bvjk fW;
    public static final bvjk fX;
    public static final bvjk fY;
    public static final bvjk fZ;
    public static final bvjk fa;
    public static final bvjk fb;
    public static final bvjk fc;
    public static final bvjk fd;
    public static final bvjk fe;
    public static final bvjk ff;
    public static final bvjk fg;
    public static final bvjk fh;
    public static final bvjk fi;
    public static final bvjk fj;
    public static final bvjk fk;
    @Deprecated
    public static final bvjk fl;
    public static final bvjk fm;
    @Deprecated
    public static final bvjk fn;
    public static final bvjk fo;
    @Deprecated
    public static final bvjk fp;
    public static final bvjk fq;
    @Deprecated
    public static final bvjk fr;
    @Deprecated
    public static final bvjk fs;
    public static final bvjk ft;
    public static final bvjk fu;
    public static final bvjk fv;
    public static final bvjk fw;
    public static final bvjk fx;
    @Deprecated
    public static final bvjk fy;
    public static final bvjk fz;
    public static final bvjk g;
    public static final bvjk gA;
    public static final bvjk gB;
    public static final bvjk gC;
    public static final bvjk gD;
    public static final bvjk gE;
    public static final bvjk gF;
    public static final bvjk gG;
    public static final bvjk gH;
    public static final bvjk gI;
    public static final bvjk gJ;
    public static final bvjk gK;
    public static final bvjk gL;
    public static final bvjk gM;
    public static final bvjk gN;
    public static final bvjk gO;
    public static final bvjk gP;
    public static final bvjk gQ;
    public static final bvjk gR;
    public static final bvjk gS;
    public static final bvjk gT;
    public static final bvjk gU;
    public static final bvjk gV;
    public static final bvjk gW;
    public static final bvjk gX;
    public static final bvjk gY;
    public static final bvjk gZ;
    public static final bvjk ga;
    public static final bvjk gb;
    public static final bvjk gc;
    public static final bvjk gd;
    public static final bvjk ge;
    public static final bvjk gf;
    public static final bvjk gg;
    public static final bvjk gh;
    public static final bvjk gi;
    public static final bvjk gj;
    public static final bvjk gk;
    public static final bvjk gl;
    public static final bvjk gm;
    public static final bvjk gn;
    public static final bvjk go;
    public static final bvjk gp;
    public static final bvjk gq;
    public static final bvjk gr;
    public static final bvjk gs;
    public static final bvjk gt;
    public static final bvjk gu;
    public static final bvjk gv;
    public static final bvjk gw;
    public static final bvjk gx;
    public static final bvjk gy;
    public static final bvjk gz;
    public static final bvjk h;
    public static final bvjk hA;
    public static final bvjk hB;
    public static final bvjk hC;
    public static final bvjk hD;
    public static final bvjk hE;
    public static final bvjk hF;
    public static final bvjk hG;
    public static final bvjk hH;
    public static final bvjk hI;
    public static final bvjk hJ;
    public static final bvjk hK;
    public static final bvjk hL;
    public static final bvjk hM;
    public static final bvjk hN;
    public static final bvjk hO;
    public static final bvjk hP;
    @Deprecated
    public static final bvjk hQ;
    public static final bvjk hR;
    public static final bvjk hS;
    public static final bvjk hT;
    public static final bvjk hU;
    public static final bvjk hV;
    public static final bvjk hW;
    public static final bvjk hX;
    public static final bvjk hY;
    public static final bvjk hZ;
    public static final bvjk ha;
    public static final bvjk hb;
    public static final bvjk hc;
    public static final bvjk hd;
    public static final bvjk he;
    public static final bvjk hf;
    public static final bvjk hg;
    public static final bvjk hh;
    public static final bvjk hi;
    public static final bvjk hj;
    public static final bvjk hk;
    public static final bvjk hl;
    public static final bvjk hm;
    @Deprecated
    public static final bvjk hn;
    public static final bvjk ho;
    public static final bvjk hp;
    public static final bvjk hq;
    public static final bvjk hr;
    public static final bvjk hs;
    public static final bvjk ht;
    @Deprecated
    public static final bvjk hu;
    public static final bvjk hv;
    public static final bvjk hw;
    public static final bvjk hx;
    public static final bvjk hy;
    public static final bvjk hz;
    public static final bvjk i;
    public static final bvjk iA;
    public static final bvjk iB;
    public static final bvjk iC;
    public static final bvjk iD;
    public static final bvjk iE;
    @Deprecated
    public static final bvjk iF;
    public static final bvjk iG;
    public static final bvjk iH;
    public static final bvjk iI;
    @Deprecated
    public static final bvjk iJ;
    public static final bvjk iK;
    public static final bvjk iL;
    public static final bvjk iM;
    public static final bvjk iN;
    public static final bvjk iO;
    public static final bvjk iP;
    public static final bvjk iQ;
    public static final bvjk iR;
    public static final bvjk iS;
    public static final bvjk iT;
    public static final bvjk iU;
    public static final bvjk iV;
    public static final bvjk iW;
    public static final bvjk iX;
    public static final bvjk iY;
    public static final bvjk iZ;
    public static final bvjk ia;
    public static final bvjk ib;
    public static final bvjk ic;
    public static final bvjk id;
    @Deprecated
    static final bvjk ie;

    /* renamed from: if  reason: not valid java name */
    public static final bvjk f1if;
    public static final bvjk ig;
    public static final bvjk ih;
    public static final bvjk ii;
    public static final bvjk ij;
    public static final bvjk ik;
    public static final bvjk il;
    public static final bvjk im;
    public static final bvjk in;
    public static final bvjk io;
    public static final bvjk ip;
    public static final bvjk iq;
    public static final bvjk ir;
    public static final bvjk is;
    public static final bvjk it;
    public static final bvjk iu;
    @Deprecated
    public static final bvjk iv;
    public static final bvjk iw;
    public static final bvjk ix;
    public static final bvjk iy;
    @Deprecated
    static final bvjk iz;
    public static final bvjk j;
    public static final bvjk jA;
    public static final bvjk jB;
    public static final bvjk jC;
    public static final bvjk jD;
    public static final bvjk jE;
    public static final bvjk jF;
    public static final bvjk jG;
    public static final bvjk jH;
    public static final bvjk jI;
    public static final bvjk jJ;
    public static final bvjk jK;
    public static final bvjk jL;
    public static final bvjk jM;
    public static final bvjk jN;
    public static final bvjk jO;
    public static final bvjk jP;
    public static final bvjk jQ;
    public static final bvjk jR;
    public static final bvjk jS;
    public static final bvjk jT;
    public static final bvjk jU;
    public static final bvjk jV;
    public static final bvjk jW;
    public static final bvjk jX;
    public static final bvjk jY;
    public static final bvjk jZ;
    public static final bvjk ja;
    public static final bvjk jb;
    public static final bvjk jc;
    public static final bvjk jd;
    public static final bvjk je;
    public static final bvjk jf;
    public static final bvjk jg;
    public static final bvjk jh;
    public static final bvjk ji;
    public static final bvjk jj;
    public static final bvjk jk;
    public static final bvjk jl;
    public static final bvjk jm;
    public static final bvjk jn;
    public static final bvjk jo;
    public static final bvjk jp;
    public static final bvjk jq;
    public static final bvjk jr;
    public static final bvjk js;
    public static final bvjk jt;
    public static final bvjk ju;
    public static final bvjk jv;
    public static final bvjk jw;
    public static final bvjk jx;
    public static final bvjk jy;
    public static final bvjk jz;
    public static final bvjk k;
    private static final dcqe kB = dcqe.c("bvjk");
    private static final bvjp kC;
    public static final bvjk ka;
    public static final bvjk kb;
    public static final bvjk kc;
    public static final bvjk kd;
    public static final bvjk ke;
    public static final bvjk kf;
    public static final bvjk kg;
    public static final bvjk kh;
    public static final bvjk ki;
    public static final bvjk kj;
    public static final bvjk kk;
    public static final bvjk kl;
    public static final bvjk km;
    public static final bvjk kn;
    public static final bvjk ko;
    public static final bvjk kp;
    public static final bvjk kq;
    public static final bvjk kr;
    public static final bvjk ks;
    public static final bvjk kt;
    public static final bvjk ku;
    public static final bvjk kv;
    public static final bvjk kw;
    public static final bvjk kx;
    public static final bvjk ky;
    public static final bvjk l;
    public static final bvjk m;
    public static final bvjk n;
    public static final bvjk o;
    public static final bvjk p;
    public static final bvjk q;
    public static final bvjk r;
    public static final bvjk s;
    public static final bvjk t;
    public static final bvjk u;
    public static final bvjk v;
    public static final bvjk w;
    @Deprecated
    public static final bvjk x;
    public static final bvjk y;
    public static final bvjk z;
    public final bviw kA;
    public final String kz;

    static {
        bvjp bvjpVar = new bvjp();
        kC = bvjpVar;
        a = new bvjk("settings_version", bvjpVar);
        bvjl bvjlVar = new bvjl();
        b = bvjlVar;
        c = bvjpVar;
        d = new bvjk("aid#", bvjlVar);
        bvjk bvjkVar = new bvjk("NO_OP", bvjlVar);
        e = bvjkVar;
        f = new bvjk("INVALID", bvjlVar);
        g = new bvjk("launch_count", bvjpVar);
        new bvjk("review_thanks_toast", bvjpVar);
        h = new bvjk("location_denied_do_not_ask_again", bvjlVar);
        i = new bvjk("current_account_id", bvjpVar);
        j = new bvjk("last_account_id", bvjlVar);
        k = new bvjk("record_enter_incognito", bvjlVar);
        l = new bvjk("record_exit_incognito", bvjlVar);
        m = new bvjk("last_state", bvjlVar);
        n = new bvjk("incognito_exit_failure", bvjlVar);
        o = new bvjk("ineus", bvjpVar);
        p = new bvjk("incognito_account_id", bvjlVar);
        q = new bvjk("izb", bvjlVar);
        r = new bvjk("incognito_disclaimer_last_shown_millis", bvjlVar);
        s = new bvjk("incognito_session_start_date_time", bvjlVar);
        t = new bvjk("incognito_entry_num_tries", bvjlVar);
        u = new bvjk("signed_in_shared_pref_restore_checker", bvjlVar);
        v = new bvjk("incognito_staring_to_enter_or_exit_time_millis", bvjlVar);
        w = new bvjk("incognito_finished_entering_or_exiting_time_millis", bvjlVar);
        x = new bvjk("current_account_name", bvjpVar);
        y = new bvjk("signout_reason", bvjlVar);
        new bvjk("recent_account_names", bvjpVar);
        z = new bvjk("distance_units", new bvit(dowa.class));
        A = new bvjk("currency_units", bvjlVar);
        B = new bvjk("dark_mode", bvjpVar);
        C = new bvjk("dark_mode_session_count", bvjpVar);
        D = new bvjk("client_side_recent_history", bvjpVar);
        E = new bvjk("satellite_on_at_startup", bvjpVar);
        F = new bvjk("satellite_layer_enabled_count", bvjpVar);
        G = new bvjk("satellite_keep_on_dialog_shown", bvjpVar);
        H = new bvjk("show_scalebar", bvjpVar);
        I = new bvjk("shake_to_send_feedback_default_off", bvjpVar);
        J = new bvjk("taxi_notifications", bvjpVar);
        new bvjk("startscreen_key", bvjpVar);
        new bvjk("disable_startscreen_for_testing_key", bvjpVar);
        new bvjk("disable_goldfinger_for_testing_key", bvjpVar);
        K = new bvjk("notifications_inbox_tab_deleted_notifications", bvjpVar);
        new bvjk("goldfinger_key", bvjpVar);
        L = new bvjk("goldfinger_initial_tab", bvjpVar);
        new bvjk("goldfinger_initial_tab_epoch", bvjpVar);
        M = new bvjk("goldfinger_last_stop_state", bvjlVar);
        N = new bvjk("home_fragment_last_stop_timestamp_ms", bvjlVar);
        O = new bvjk("pa_cache_file_per_account", bvjlVar);
        new bvjk("pa_last_written_directory", bvjlVar);
        new bvjk("goldfinger_time_of_first_user_interaction_sec", bvjpVar);
        new bvjk("goldfinger_transit_cached_tab_state", bvjlVar);
        new bvjk("goldfinger_transit_cached_rtuts", bvjlVar);
        new bvjk("goldfinger_transit_cache_expiration", bvjlVar);
        P = new bvjk("goldfinger_attention_history", bvjlVar);
        Q = new bvjk("language_override", bvjlVar);
        R = new bvjk("pending_language_override", bvjlVar);
        S = new bvjk("language_background_download_request", bvjlVar);
        T = new bvjk("user_interacted_with_language_picker_promo", bvjlVar);
        U = bvjkVar;
        V = bvjkVar;
        new bvjk("vms_features_enabled", bvjlVar);
        W = bvjkVar;
        new bvjk("ev_profile", bvjlVar);
        X = new bvjk("ev_profile_search_result_promo_dismissed", bvjpVar);
        Y = new bvjk("current_ev_profile_id", bvjlVar);
        Z = bvjkVar;
        aa = bvjkVar;
        bvjl bvjlVar2 = b;
        ab = new bvjk("force_disable_hats_surveys_for_testing", bvjlVar2);
        bvjk bvjkVar2 = e;
        ac = bvjkVar2;
        bvjp bvjpVar2 = c;
        new bvjk("rover_notifications", bvjpVar2);
        ad = new bvjk("rover_notifications_dismiss", bvjpVar2);
        new bvjk("rover_notifications_opt_out_shown_count", bvjpVar2);
        ae = new bvjk("business_listings_notifications", bvjpVar2);
        af = new bvjk("business_listings_notification_opt_out_shown_count", bvjpVar2);
        ag = bvjkVar2;
        ah = bvjkVar2;
        ai = new bvjk("directions_multi_waypoint_promo_disabled", bvjpVar2);
        aj = new bvjk("directions_long_distance_offroad_promo_dismiss_count", bvjpVar2);
        ak = new bvjk("directions_international_offroad_promo_dismiss_count", bvjpVar2);
        al = new bvjk("directions_last_displayed_unique_id", bvjlVar2);
        am = bvjkVar2;
        an = bvjkVar2;
        ao = bvjkVar2;
        new bvjk("live_traffic_promo_banner_dismissed", bvjpVar2);
        ap = new bvjk("local_follow_opt_in_dialog_acknowledged", bvjpVar2);
        aq = bvjkVar2;
        ar = new bvjk("car_fake_recent_places", bvjlVar2);
        as = new bvjk("car_fake_implicit_destinations", bvjlVar2);
        at = bvjkVar2;
        au = new bvjk("demo_driving_simulation", bvjlVar2);
        av = new bvjk("demo_driving_simulation_freenav", bvjlVar2);
        aw = bvjkVar2;
        ax = bvjkVar2;
        ay = bvjkVar2;
        az = bvjkVar2;
        aA = bvjkVar2;
        aB = bvjkVar2;
        aC = bvjkVar2;
        aD = bvjkVar2;
        aE = bvjkVar2;
        aF = bvjkVar2;
        aG = new bvjk("local_stream_read_item_timestamp", bvjlVar2);
        aH = new bvjk("local_stream_latest_item_timestamp", bvjlVar2);
        new bvjk("local_stream_display_welcome_page", bvjlVar2);
        new bvjk("local_stream_display_confirm_area_module_count", bvjlVar2);
        aI = new bvjk("local_stream_display_post_onboard_one_tap_welcome_carousel_count", bvjlVar2);
        aJ = new bvjk("local_stream_one_tap_welcome_carousel_selected_index", bvjlVar2);
        aK = new bvjk("local_stream_octs", bvjpVar2);
        aL = new bvjk("local_stream_oifn", bvjpVar2);
        aM = new bvjk("local_stream_preference_card_last_time_shown_sec", bvjpVar2);
        aN = bvjkVar2;
        aO = new bvjk("local_stream_waa_sign_in_card_triggered_count", bvjlVar2);
        aP = new bvjk("local_stream_cookie", bvjpVar2);
        aQ = new bvjk("local_preferences_user_has_seen_dining_leaf_page", bvjlVar2);
        aR = bvjkVar2;
        aS = new bvjk("force_night_mode_2", bvjpVar2);
        aT = bvjkVar2;
        aU = bvjkVar2;
        aV = new bvjk("car_oem_settings", bvjlVar2);
        new bvjk("keep_car_oem_settings_override_dev", bvjlVar2);
        aW = new bvjk("free_nav_last_phone_timestamp", bvjpVar2);
        aX = new bvjk("fn_launch_count", bvjpVar2);
        aY = new bvjk("fn_shortcut_asked", bvjpVar2);
        aZ = new bvjk("fn_end_of_nav_shortcut_asked", bvjpVar2);
        ba = new bvjk("fn_shortcut_created", bvjpVar2);
        bvjp bvjpVar3 = c;
        bb = new bvjk("fn_traffic_by_default", bvjpVar3);
        bc = new bvjk("driving_mode_detection_notification", bvjpVar3);
        bvjl bvjlVar3 = b;
        bd = new bvjk("driving_mode_detection_notification_state", bvjlVar3);
        be = new bvjk("free_nav_simulate_driving_mode_detection", bvjpVar3);
        bvjk bvjkVar3 = e;
        bf = bvjkVar3;
        bg = bvjkVar3;
        bh = bvjkVar3;
        bi = bvjkVar3;
        bj = bvjkVar3;
        bk = bvjkVar3;
        new bvjk("override_webview_base_url", bvjlVar3);
        new bvjk("override_only_base_webview_url", bvjlVar3);
        new bvjk("webview_base_url", bvjlVar3);
        new bvjk("override_messaging_email_id", bvjlVar3);
        new bvjk("messaging_email_id", bvjlVar3);
        new bvjk("messaging_start_conversation_id", bvjlVar3);
        new bvjk("messaging_verify_pin", bvjlVar3);
        new bvjk("messaging_copy_notification_tag", bvjlVar3);
        new bvjk("messaging_notification_tag", bvjlVar3);
        bl = new bvjk("recent_messaging_activity_in_background", bvjlVar3);
        bm = new bvjk("messaging_conversation_view_opened_conversations_logged", bvjlVar3);
        bn = new bvjk("messaging_conversation_view_message_sent_conversations_logged", bvjlVar3);
        bo = new bvjk("messaging_bypass_filters_for_dev", bvjlVar3);
        bp = new bvjk("messaging_tab_opened_after_latest_new_message", bvjlVar3);
        bq = new bvjk("session_id", bvjlVar3);
        br = new bvjk("zb", bvjlVar3);
        bs = new bvjk("bk_zb", bvjlVar3);
        bt = new bvjk("zbuid", bvjlVar3);
        bu = new bvjk("cohort", bvjlVar3);
        bv = new bvjk("cle_flush_timeout_count", bvjpVar3);
        new bvjk("map_tile_settings_prefetching_over_mobile_networks", bvjpVar3);
        bw = new bvjk("oob_login_promo_shown", bvjpVar3);
        bx = new bvjk("oob_ulr_promo_shown", bvjpVar3);
        by = new bvjk("oob_offline_promo_shown", bvjpVar3);
        bz = new bvjk("oob_offline_recommended_region_proto", bvjlVar3);
        bA = new bvjk("oob_offline_recommended_region_name", bvjlVar3);
        bB = new bvjk("oob_offline_recommended_region", bvjlVar3);
        bC = new bvjk("offline_autodownload_region_name", bvjlVar3);
        bD = new bvjk("offline_autodownload_region_size_mb", bvjlVar3);
        new bvjk("offline_autodownload_region_id", bvjlVar3);
        new bvjk("offline_next_region_expiration", bvjlVar3);
        bE = new bvjk("offline_autoupdate_sched_state", bvjlVar3);
        bF = new bvjk("offline_autoupdate_time_budget", bvjlVar3);
        bG = new bvjk("offline_unlabeled_area_number", bvjlVar3);
        bH = new bvjk("offline_use_auto_update_v2", bvjlVar3);
        bI = new bvjk("offline_manual_selection_tutorial_shown", bvjpVar3);
        bJ = new bvjk("network_response_cache_account_id", bvjlVar3);
        bK = new bvjk("user_has_offline_region", bvjlVar3);
        bL = new bvjk("offline_last_out_of_coverage_notification_timestamp", bvjlVar3);
        bM = new bvjk("oob_ulr_on_tos", bvjpVar3);
        new bvjk("fut", bvjlVar3);
        bN = new bvjk("directions_travel_mode", bvjpVar3);
        bO = new bvjk("directions_bikesharing_last_provider", bvjpVar3);
        bP = new bvjk("directions_transit_ms", bvjpVar3);
        bQ = new bvjk("directions_show_initial_taxi_tab", bvjpVar3);
        new bvjk("directions_did_show_taxi_tab_results", bvjpVar3);
        bR = new bvjk("navigation_terms_accepted", bvjpVar3);
        bS = new bvjk("navigation_assistant_terms_accepted", bvjpVar3);
        bT = new bvjk("audio_disabled_modes", bvjlVar3);
        bU = new bvjk("binary_mute_level", bvjpVar3);
        bV = new bvjk("multi_mute_level", bvjpVar3);
        bW = new bvjk("commute_hub_shortcut_promo_count", bvjlVar3);
        bX = new bvjk("commute_hub_zero_state_visit_count", bvjlVar3);
        bY = new bvjk("commute_hub_visit_dates", bvjlVar3);
        bZ = new bvjk("commute_hub_visit_day_count_after_first_promo", bvjlVar3);
        bvjp bvjpVar4 = c;
        ca = new bvjk("heading_up_preferred", bvjpVar4);
        cb = new bvjk("north_up_preferred", bvjpVar4);
        new bvjk("checked_north_up_preferred", bvjpVar4);
        new bvjk("hotel_booking_options", bvjpVar4);
        new bvjk("hotel_booking_options_expiration", bvjpVar4);
        cc = new bvjk("home_work_side_menu_attention_promo_followed", bvjpVar4);
        cd = new bvjk("home_work_side_menu_attention_promo_showing", bvjpVar4);
        bvjl bvjlVar4 = b;
        new bvjk("your_directions_shortcuts", bvjlVar4);
        new bvjk("your_directions_card_shown", bvjpVar4);
        new bvjk("your_directions_customized", bvjpVar4);
        new bvjk("your_searches_customized", bvjpVar4);
        new bvjk("your_searches_card_shown", bvjpVar4);
        new bvjk("start_screen_enabled_your_shortcuts", bvjpVar4);
        new bvjk("your_shortcuts_enabled_types", bvjpVar4);
        new bvjk("your_shortcuts_editor_opened", bvjpVar4);
        new bvjk("your_shortcuts_editor_shown", bvjpVar4);
        new bvjk("your_shortcuts_card_shown", bvjpVar4);
        new bvjk("your_shortcuts_customized", bvjpVar4);
        new bvjk("start_screen_last_collapsed_state", bvjpVar4);
        new bvjk("start_screen_last_start_timestamp_ms", bvjpVar4);
        new bvjk("start_screen_happy_diwali_shown", bvjpVar4);
        new bvjk("start_screen_rangoli_seed", bvjlVar4);
        new bvjk("start_screen_rangoli_next_index", bvjlVar4);
        new bvjk("start_screen_rangoli_last_display_date", bvjlVar4);
        new bvjk("start_screen_completed_rangolis", bvjlVar4);
        ce = new bvjk("taxi_preferred_provider", bvjpVar4);
        cf = new bvjk("taxi_last_used_provider", bvjpVar4);
        cg = new bvjk("bikesharing_preferred_provider", bvjpVar4);
        ch = new bvjk("bikesharing_last_used_provider", bvjpVar4);
        new bvjk("taxi_preferred_provider_migrated", bvjpVar4);
        ci = new bvjk("taxi_preferred_provider_reset", bvjpVar4);
        cj = new bvjk("taxi_last_used_android_pay_card_name", bvjpVar4);
        ck = new bvjk("taxi_last_used_android_pay_card_network", bvjpVar4);
        cl = new bvjk("taxi_legal_notice_shown", bvjpVar4);
        cm = new bvjk("taxi_promo_state", bvjpVar4);
        new bvjk("traffic_promo_banner_impression_count", bvjpVar4);
        new bvjk("traffic_promo_banner_tapped", bvjpVar4);
        cn = new bvjk("inferred_notification_click_count", bvjlVar4);
        co = new bvjk("inferred_commute_destination_labeling_promo_display_timestamps", bvjlVar4);
        new bvjk("traffic_report_promo_display_count", bvjpVar4);
        new bvjk("traffic_report_promo_navigation_count", bvjpVar4);
        new bvjk("traffic_report_promo_directions_result_count", bvjpVar4);
        cp = new bvjk("commute_immersive_quick_sentiment_last_response_ms", bvjlVar4);
        cq = new bvjk("commute_notification_prober_marked_session_ids", bvjlVar4);
        cr = new bvjk("traffic_to_place_notifications", bvjpVar4);
        cs = new bvjk("traffic_to_place_notification_last_received", bvjlVar4);
        ct = new bvjk("traffic_to_place_notification_promo_suppressed", bvjpVar4);
        cu = new bvjk("traffic_to_place_notification_has_been_enabled_by_server", bvjlVar4);
        cv = new bvjk("traffic_to_place_notification_fence_list", bvjlVar4);
        cw = new bvjk("time_to_leave_notification_fence_list", bvjlVar4);
        cx = new bvjk("traffic_to_place_notification_dismissed_session_id_list", bvjlVar4);
        cy = new bvjk("time_to_leave_notification_dismissed_session_id_list", bvjlVar4);
        cz = new bvjk("traffic_to_place_notification_received_sessions", bvjlVar4);
        bvjk bvjkVar4 = f;
        cA = bvjkVar4;
        cB = new bvjk("traffic_to_place_notification_warmup_shown_timestamp", bvjpVar4);
        cC = new bvjk("home_only_commute_notification_info_warm_up", bvjpVar4);
        cD = new bvjk("commute_notification_home_only_opt_out_context", bvjlVar4);
        new bvjk("inferred_commute_destination_fake_test_notification_destination", bvjpVar4);
        cE = new bvjk("commute_notification_inferred_destination_opt_out_context", bvjlVar4);
        cF = new bvjk("driving_directions_search_count", bvjlVar4);
        cG = new bvjk("transit_directions_search_count", bvjlVar4);
        cH = new bvjk("time_to_leave_notifications", bvjpVar4);
        cI = new bvjk("traffic_two_wheeler", bvjlVar4);
        cJ = new bvjk("transit_to_place_notification_dismissed_session_id_list", bvjlVar4);
        cK = new bvjk("transit_to_place_disruption_notification_dismissed_session_id_list", bvjlVar4);
        cL = new bvjk("transit_to_place_notification_fence_list", bvjlVar4);
        new bvjk("transit_payment_banner_dismiss", bvjlVar4);
        cM = new bvjk("transit_payment_dismissed_cards", bvjlVar4);
        cN = new bvjk("transit_payment_dismissed_agency_ids", bvjlVar4);
        cO = new bvjk("transit_payment_banner_promo_click", bvjlVar4);
        cP = new bvjk("transit_disruption_seen_alerts", bvjlVar4);
        cQ = new bvjk("transit_layer_off_count", bvjpVar4);
        cR = new bvjk("transit_layer_as_default", bvjpVar4);
        cS = new bvjk("commute_basic_travel_mode", bvjlVar4);
        cT = new bvjk("last_cleared_parking_location_timestamp", bvjlVar4);
        cU = new bvjk("parking_location_notification_dismissed_id", bvjlVar4);
        cV = new bvjk("parking_location_expiration_notification_scheduled", bvjlVar4);
        cW = new bvjk("parking_location_expiration_notification_showing", bvjlVar4);
        new bvjk("parking_payment_session_details", bvjlVar4);
        bvjp bvjpVar5 = c;
        new bvjk("parking_payment_session_expiring_notification_enabled", bvjpVar5);
        new bvjk("parking_payment_educational_promo_timestamp", bvjlVar4);
        cX = bvjkVar4;
        new bvjk("transit_promo_banner_impression_count", bvjpVar5);
        new bvjk("transit_promo_banner_tapped", bvjpVar5);
        new bvjk("transit_promo_notification_tapped", bvjpVar5);
        new bvjk("transit_promo_odelay_card_tapped", bvjpVar5);
        new bvjk("transit_station_create_shortcut_promo_shown", bvjpVar5);
        new bvjk("area_traffic_in_metro", bvjpVar5);
        cY = new bvjk("area_traffic_notification", bvjpVar5);
        cZ = new bvjk("area_traffic_notification_subscription", bvjpVar5);
        da = new bvjk("area_traffic_notification_subscription_request_time_ms", bvjpVar5);
        db = new bvjk("traffic_hub_create_count", bvjpVar5);
        dc = new bvjk("traffic_hub_create_shortcut_promo_dismissal_time_ms", bvjpVar5);
        dd = new bvjk("traffic_hub_add_home_work_promo_dismissal_time_ms", bvjpVar5);
        de = new bvjk("traffic_hub_add_home_work_promo_first_create_count", bvjpVar5);
        df = new bvjk("suppress_area_traffic_warm_up", bvjpVar5);
        bvjk bvjkVar5 = e;
        dg = bvjkVar5;
        dh = new bvjk("transit_station_notification", bvjpVar5);
        di = new bvjk("transit_feedback_notification", bvjpVar5);
        new bvjk("transit_schematic_map_notification", bvjpVar5);
        dj = bvjkVar5;
        dk = new bvjk("transit_guidance_voice_on", bvjpVar5);
        dl = bvjkVar5;
        dm = bvjkVar5;
        dn = bvjkVar5;
        f0do = bvjkVar5;
        bvjl bvjlVar5 = b;
        new bvjk("transportation_tab_last_open_subtab", bvjlVar5);
        dp = new bvjk("notification_feedback_rated_entries", bvjpVar5);
        dq = new bvjk("tutorials_state_blue_dot_tutorial_done", bvjpVar5);
        dr = new bvjk("tutorials_state_personal_search_tutorial_done", bvjpVar5);
        new bvjk("tutorials_state_layers_tutorial_done", bvjpVar5);
        ds = new bvjk("tutorials_state_layers_menu_ever_opened", bvjpVar5);
        new bvjk("tutorials_state_list_view_tutorial_done", bvjpVar5);
        dt = new bvjk("tutorials_state_my_location_click_count", bvjpVar5);
        du = new bvjk("tutorials_state_pin_taps_count", bvjpVar5);
        dv = new bvjk("tutorials_state_pull_up_tutorial_done", bvjpVar5);
        dw = new bvjk("tutorials_state_search_count", bvjpVar5);
        dx = new bvjk("tutorials_state_place_sheet_ever_expanded", bvjpVar5);
        new bvjk("tutorials_state_swipe_tutorial_done", bvjpVar5);
        new bvjk("tutorials_state_location_sharing_incoming_share_done", bvjpVar5);
        new bvjk("tutorials_state_location_sharing_outgoing_share_done", bvjpVar5);
        new bvjk("tutorials_state_location_sharing_journey_popup_logged", bvjpVar5);
        new bvjk("tutorials_state_location_sharing_sidemenu_popup_logged", bvjpVar5);
        dy = new bvjk("tutorials_state_smart_drive_tutorial_done", bvjpVar5);
        new bvjk("tutorials_state_last_sidemenu_tutorials_timestamp", bvjpVar5);
        dz = new bvjk("tutorials_state_enroute_fab_tutorial_done", bvjpVar5);
        dA = new bvjk("tutorials_state_location_history_done_version", bvjpVar5);
        dB = new bvjk("tutorials_state_ugc_tasks_search_button_tutorial_done", bvjpVar5);
        dC = new bvjk("tutorial_history", bvjpVar5);
        dD = new bvjk("tutorial_history_sync_info", bvjlVar5);
        dE = new bvjk("hats_throttle_count", bvjlVar5);
        dF = new bvjk("personal_route_fetching_enabled_cache", bvjpVar5);
        dG = new bvjk("location_history_promo_opt_out", bvjpVar5);
        dH = bvjkVar5;
        dI = new bvjk("social_planning_show_collaboration_notifications", bvjpVar5);
        dJ = new bvjk("social_planning_collaboration_opt_out_shown_count", bvjpVar5);
        dK = new bvjk("private_google_photos_opt_out", bvjpVar5);
        dL = new bvjk("timeline_email_opt_out", bvjpVar5);
        dM = new bvjk("timeline_show_notifications", bvjpVar5);
        dN = new bvjk("timeline_notifications_opt_out_shown", bvjpVar5);
        dO = new bvjk("timeline_receipt_processing_opt_in", bvjpVar5);
        dP = new bvjk("timeline_receipts_webview", bvjpVar5);
        dQ = new bvjk("timeline_latest_receipt_processing_promo_dismiss_ms", bvjpVar5);
        dR = new bvjk("timeline_movie_event_onboarding_has_been_shown", bvjpVar5);
        dS = new bvjk("timeline_carousel_visible", bvjpVar5);
        dT = new bvjk("layers_state", new bvit(afwm.class));
        dU = new bvjk("explore_intent_map_state", bvjlVar5);
        dV = new bvjk("odelay_config_token", bvjlVar5);
        bvjp bvjpVar6 = c;
        new bvjk("guide_latest_entry_point", bvjpVar6);
        dW = new bvjk("app_version", bvjlVar5);
        new bvjk("om_area", bvjlVar5);
        new bvjk("om_redownload_prompt", bvjlVar5);
        dX = new bvjk("saved_directions", bvjlVar5);
        dY = new bvjk("navigation_early_exit_sentiment_survey_is_collapsed", bvjlVar5);
        dZ = new bvjk("navigation_session_in_progress", bvjlVar5);
        ea = new bvjk("navigation_session_creation_timestamp", bvjlVar5);
        eb = new bvjk("nav_restore_last_phone_timestamp", bvjlVar5);
        ec = new bvjk("nav_restore_last_projected_timestamp", bvjlVar5);
        ed = new bvjk("most_recent_nav_restore_attempt_timestamp", bvjlVar5);
        ee = new bvjk("most_recent_nav_restore_successful_attempt_timestamp", bvjlVar5);
        ef = new bvjk("most_recent_nav_restore_successful_load_proto_timestamp", bvjlVar5);
        eg = new bvjk("enroute_restore_last_projected_dismissed_onplug_card_timestamp", bvjlVar5);
        eh = new bvjk("save_this_route_last_saved_timestamp", bvjlVar5);
        new bvjk("reservation_info_first_name", bvjpVar6);
        new bvjk("reservation_info_last_name", bvjpVar6);
        new bvjk("reservation_info_email", bvjpVar6);
        new bvjk("reservation_info_phone", bvjpVar6);
        new bvjk("reservations_cache", bvjlVar5);
        new bvjk("voice_help_failure_count", bvjlVar5);
        new bvjk("voice_help_cycle_index", bvjlVar5);
        ei = new bvjk("offline_storage_internal", bvjlVar5);
        ej = new bvjk("offline_maps_while_signed_out", bvjlVar5);
        ek = new bvjk("offline_download_wifi_only", bvjpVar6);
        el = new bvjk("offline_last_sdcard_id_in_use", bvjlVar5);
        bvjl bvjlVar6 = b;
        em = new bvjk("offline_last_sdcard_id_missing", bvjlVar6);
        en = new bvjk("offline_storage_settings_in_dl_flow_shown", bvjlVar6);
        eo = new bvjk("offline_automatic_updates", bvjlVar6);
        ep = new bvjk("offline_dynamic_padding", bvjlVar6);
        eq = f;
        er = new bvjk("offline_regions_last_auto_update", bvjlVar6);
        es = new bvjk("offline_regions_last_critical_only_auto_update", bvjlVar6);
        et = new bvjk("restrict_cell_usage", bvjpVar6);
        eu = new bvjk("offline_use_caveat_shown", bvjlVar6);
        new bvjk("offline_initialization_crash_count", bvjlVar6);
        ev = new bvjk("offline_app_upgrade_shown", bvjlVar6);
        new bvjk("offline_min_data_version", bvjlVar6);
        new bvjk("offline_legacy_regions_migrated", bvjlVar6);
        ew = new bvjk("offline_onboarding_show_reminder", bvjlVar6);
        ex = new bvjk("offline_onboarding_last_shown_timestamp", bvjlVar6);
        ey = new bvjk("offline_autodownload_enabled", bvjlVar6);
        ez = new bvjk("offline_autodownload", bvjpVar6);
        eA = new bvjk("offline_manual_download_override_connectivity", bvjlVar6);
        eB = new bvjk("offline_autoupdate_tutorial_shown", bvjpVar6);
        eC = new bvjk("offroad_autoupdate_on_next_launch", bvjlVar6);
        eD = new bvjk("offroad_autoupdate_on_next_launch_last_set_timestamp_ms", bvjlVar6);
        eE = new bvjk("color_scheme", bvjpVar6);
        eF = new bvjk("avoid_highways", bvjpVar6);
        eG = new bvjk("avoid_ferries", bvjpVar6);
        eH = new bvjk("avoid_tolls", bvjpVar6);
        eI = new bvjk("voice_preference", bvjlVar6);
        eJ = new bvjk("voice_preference_locale", bvjlVar6);
        eK = new bvjk("voice_option", bvjlVar6);
        eL = new bvjk("voice_level", bvjpVar6);
        eM = new bvjk("voice_bundles", bvjlVar6);
        eN = new bvjk("play_nav_audio_while_in_call", bvjpVar6);
        eO = new bvjk("play_voice_over_bluetooth", bvjpVar6);
        eP = new bvjk("play_audio_cues_in_navigation", bvjpVar6);
        eQ = new bvjk("remember_monthly_nav_stats", bvjpVar6);
        eR = new bvjk("hotword_settings", bvjlVar6);
        bvjp bvjpVar7 = c;
        eS = new bvjk("speed_limits_enabled", bvjpVar7);
        eT = new bvjk("speed_limits_ever_shown", bvjpVar7);
        eU = new bvjk("speedometer_enabled", bvjpVar7);
        eV = new bvjk("nav_monthly_distance_meters", bvjpVar7);
        eW = new bvjk("nav_monthly_duration_sec", bvjpVar7);
        eX = new bvjk("nav_monthly_trip_count", bvjpVar7);
        eY = new bvjk("nav_monthly_time_spent_in_heavy_traffic_sec", bvjpVar7);
        new bvjk("nav_stat_last_reset_for_month", bvjpVar7);
        eZ = new bvjk("play_test_sound", bvjlVar6);
        fa = new bvjk("mymaps_map_state", bvjlVar6);
        fb = new bvjk("calibrate_compass_dialog", bvjpVar7);
        fc = new bvjk("calibrate_compass_dialog_ar_camera", bvjpVar7);
        new bvjk("calibrate_compass_dialog_shown_count", bvjpVar7);
        fd = new bvjk("calibrate_compass_figure_eight_dialog_shown_count", bvjpVar7);
        fe = new bvjk("calibrate_compass_ar_camera_dialog_shown_count", bvjpVar7);
        ff = new bvjk("improve_location_dialog", bvjpVar7);
        fg = new bvjk("improve_location_dialog_last_response", bvjpVar7);
        fh = new bvjk("location_history_promo_version", bvjpVar7);
        bvjl bvjlVar7 = b;
        fi = new bvjk("notification_history_salt", bvjlVar7);
        new bvjk("here_notifications", bvjpVar7);
        new bvjk("here_notification_intro_version_shown", bvjpVar7);
        fj = new bvjk("riddler_full_screen_tutorial_shown", bvjpVar7);
        fk = new bvjk("riddler_local_guides_opt_in_shown", bvjpVar7);
        fl = new bvjk("riddler_show_notifications", bvjpVar7);
        fm = new bvjk("riddler_notification_opt_out_shown_count", bvjpVar7);
        fn = new bvjk("event_show_notifications", bvjpVar7);
        new bvjk("event_notification_last_shown_timestamp", bvjpVar7);
        fo = new bvjk("event_notification_tags_shown", bvjpVar7);
        fp = new bvjk("announcement_show_notifications", bvjpVar7);
        fq = new bvjk("announcement_show_notifications_optout_shown_count", bvjpVar7);
        new bvjk("journey_sharing_show_arrival_notifications", bvjpVar7);
        fr = new bvjk("location_share_show_notifications", bvjpVar7);
        new bvjk("location_sharing_show_geofence_alert_notifications", bvjpVar7);
        new bvjk("location_sharing_show_geofence_reminder_notifications", bvjpVar7);
        fs = new bvjk("location_sharing_request_show_notifications", bvjpVar7);
        new bvjk("location_sharing_user_rescue_show_notifications", bvjpVar7);
        new bvjk("edit_published_show_notification", bvjpVar7);
        ft = new bvjk("edit_published_notifications_opt_out_shown_count", bvjpVar7);
        fu = new bvjk("riddler_notifications_tutorial_shown", bvjpVar7);
        new bvjk("todo_photos_notification", bvjpVar7);
        new bvjk("todo_list_notification", bvjpVar7);
        fv = new bvjk("todo_list_show_notifications_opt_out_shown_count", bvjpVar7);
        fw = new bvjk("business_owner_hours_show_notifications_opt_out_shown_count", bvjpVar7);
        fx = new bvjk("employee_hours_show_notifications_opt_out_shown_count", bvjpVar7);
        new bvjk("photo_taken_notification_tutorial_shown", bvjpVar7);
        fy = new bvjk("times_asked_for_storage_permission_for_ptn_plus", bvjlVar7);
        fz = new bvjk("storage_permission_request_history_for_ptn_mplus", bvjlVar7);
        fA = new bvjk("photo_taken_notifications", bvjpVar7);
        fB = new bvjk("photo_taken_notifications_opt_out_shown_count", bvjpVar7);
        new bvjk("photo_taken_notification_slf_photo_range_start_time", bvjlVar7);
        new bvjk("photo_taken_notification_slf_photo_range_end_time", bvjlVar7);
        fC = new bvjk("be_the_first_photo_notifications", bvjpVar7);
        fD = new bvjk("be_the_first_notification_opt_out_shown_count", bvjpVar7);
        fE = new bvjk("popular_place_notifications", bvjpVar7);
        fF = new bvjk("popular_place_notification_opt_out_shown_count", bvjpVar7);
        new bvjk("factual_contributions_notification", bvjpVar7);
        new bvjk("factual_contributions_notification_opt_out_shown_count", bvjpVar7);
        fG = new bvjk("personal_place_notification", bvjpVar7);
        fH = new bvjk("personal_places_set_alias_notifications_opt_out_shown_count", bvjpVar7);
        new bvjk("place_qa_notifications", bvjpVar7);
        fI = new bvjk("place_qa_merchant_notification_opt_out_shown_count", bvjpVar7);
        fJ = new bvjk("place_qa_notification_opt_out_shown_count", bvjpVar7);
        fK = new bvjk("offroad_trips_notification", bvjlVar7);
        fL = new bvjk("review_at_a_place_notifications", bvjpVar7);
        fM = new bvjk("reengagement_categorical_search_reopened_business", bvjpVar7);
        fN = new bvjk("reengagement_categorical_search_takeout_notification_opt_out_shown_count", bvjpVar7);
        fO = new bvjk("reengagement_placesheet_reopened_business_notification_opt_out_shown_count", bvjpVar7);
        bvjp bvjpVar8 = c;
        fP = new bvjk("reengagement_placesheet_takeout_notification_opt_out_shown_count", bvjpVar8);
        fQ = new bvjk("review_at_a_place_notification_opt_out_shown_count", bvjpVar8);
        fR = new bvjk("madden_show_notifications", bvjpVar8);
        fS = new bvjk("madden_growth_notification_opt_out_shown_count", bvjpVar8);
        fT = new bvjk("madden_landing_page_shortcut", bvjpVar8);
        fU = new bvjk("madden_shortcut_promo_last_dismiss_millis", bvjpVar8);
        fV = new bvjk("todo_list_not_been_dialog_shown", bvjpVar8);
        fW = new bvjk("timeline_warm_welcome_show_notifications_opt_out_shown_count", bvjpVar8);
        bvjk bvjkVar6 = f;
        fX = bvjkVar6;
        fY = bvjkVar6;
        bvjk bvjkVar7 = e;
        fZ = bvjkVar7;
        ga = new bvjk("user_parameters", bvjlVar7);
        gb = new bvjk("celebration_settings", bvjpVar8);
        gc = new bvjk("personal_action_card_dismissed", bvjpVar8);
        gd = new bvjk("notification_settings", bvjpVar8);
        bvjl bvjlVar8 = b;
        ge = new bvjk("gcm_token_business_messaging", bvjlVar8);
        gf = new bvjk("gcm_registration_id", bvjlVar8);
        gg = new bvjk("gcm_registration_version", bvjlVar8);
        gh = new bvjk("gcm_registration_id_for_user", bvjlVar8);
        gi = new bvjk("gcm_last_registration_per_user_timestamp", bvjlVar8);
        gj = new bvjk("car_traffic", bvjpVar8);
        gk = new bvjk("car_satellite", bvjpVar8);
        gl = new bvjk("user_has_entered_covid19_layer", bvjpVar8);
        gm = new bvjk("user_is_aware_of_covid19_layer", bvjpVar8);
        new bvjk("car_overview_expiring_suggestions", bvjpVar8);
        new bvjk("home_screen_transit_commute_survey_answered", bvjpVar8);
        new bvjk("home_screen_nearby_stations_survey_answered", bvjlVar8);
        new bvjk("home_screen_transit_system_survey_answered", bvjpVar8);
        new bvjk("home_screen_tab_promotion_shown", bvjpVar8);
        new bvjk("home_screen_tab_promoted", bvjpVar8);
        new bvjk("home_screen_map_tab_promoted", bvjpVar8);
        gn = new bvjk("home_screen_last_tab_promo_shown_id", bvjpVar8);
        new bvjk("last_home_shortcut_directions_request_timestamp_ms", bvjpVar8);
        new bvjk("last_work_shortcut_directions_request_timestamp_ms", bvjpVar8);
        go = new bvjk("gmm_last_used", bvjlVar8);
        gp = new bvjk("last_intent_millis", bvjlVar8);
        gq = new bvjk("last_background_timestamp_ms", bvjlVar8);
        gr = new bvjk("start_of_current_promo_throttler_visit_timestamp_ms", bvjpVar8);
        gs = new bvjk("location_sharing_last_report_time_ms", bvjlVar8);
        new bvjk("location_sharing_layer_enabled", bvjpVar8);
        new bvjk("location_sharing_new_badge_clicked", bvjpVar8);
        gt = new bvjk("location_sharing_share_journey_clicked", bvjpVar8);
        new bvjk("location_sharing_new_years_eve_popup_done", bvjpVar8);
        gu = new bvjk("location_sharing_tos_accepted", bvjlVar8);
        gv = new bvjk("location_sharing_tos_accepted_time_ms", bvjlVar8);
        gw = new bvjk("location_sharing_last_poll_with_no_sharing_timestamp_ms", bvjlVar8);
        gx = new bvjk("location_sharing_last_event_timestamp_ms", bvjpVar8);
        gy = new bvjk("previously_announced_navigation_popups", bvjpVar8);
        gz = new bvjk("location_sharing_link_share_warning_dont_ask_again", bvjpVar8);
        gA = new bvjk("location_sharing_request_location_email_dont_ask_again", bvjpVar8);
        gB = new bvjk("location_sharing_latest_clock_skew_millis", bvjlVar8);
        new bvjk("todo_photo_promo_dismissed", bvjpVar8);
        gC = new bvjk("todo_photo_show_notifications_opt_out_shown_count", bvjpVar8);
        gD = new bvjk("streetview_swipe_to_go_tutorial_shown", bvjpVar8);
        new bvjk("streetview_odometer_shown", bvjpVar8);
        new bvjk("streetview_swipe_to_go_meters_traveled", bvjpVar8);
        gE = new bvjk("streetview_connected_photo_banner_shown_count", bvjpVar8);
        gF = new bvjk("directions_search_history", bvjpVar8);
        new bvjk("nav_go_allow_autologin", bvjlVar8);
        gG = new bvjk("custom_place_lists_to_show_on_base_map", bvjlVar8);
        gH = bvjkVar7;
        gI = new bvjk("starred_places_to_show_on_base_map", bvjpVar8);
        gJ = new bvjk("show_contacts_on_base_map", bvjpVar8);
        bvjp bvjpVar9 = c;
        gK = new bvjk("upcoming_events_opt_out", bvjpVar9);
        gL = new bvjk("last_tile_prefetch_finished", bvjlVar8);
        gM = new bvjk("waa_status", bvjlVar8);
        new bvjk("force_inferred_home_for_testing", bvjlVar8);
        gN = new bvjk("force_alias_setting_frequent_places_for_testing", bvjpVar9);
        new bvjk("inferred_home_no_thanks", bvjlVar8);
        new bvjk("inferred_work_no_thanks", bvjlVar8);
        new bvjk("inferred_label_no_thanks", bvjpVar9);
        new bvjk("set_home_impressions_count", bvjlVar8);
        new bvjk("set_work_impressions_count", bvjlVar8);
        new bvjk("timeline_checkin", bvjlVar8);
        gO = new bvjk("edit_contributions_tab_notice_banner_dismissed", bvjpVar9);
        gP = new bvjk("contributions_shortcut_promo_dismissed", bvjpVar9);
        gQ = new bvjk("task_set_cover_pages_shown", bvjpVar9);
        gR = new bvjk("ugc_door_to_door_specific_thank_you_card_shown", bvjpVar9);
        gS = new bvjk("ugc_tasks_tutorial_callout_shown", bvjpVar9);
        gT = new bvjk("ugc_verify_task_completed", bvjlVar8);
        gU = new bvjk("ugc_video_live_camera_record_timestamp", bvjlVar8);
        new bvjk("image_quality_low", bvjpVar9);
        new bvjk("image_quality_highlight", bvjpVar9);
        gV = new bvjk("pf_unread_follow_list_badge", bvjlVar8);
        gW = new bvjk("pf_onboarding_shown", bvjlVar8);
        gX = new bvjk("pf_onboarding_completion_time_sec", bvjpVar9);
        gY = new bvjk("pf_onboarding_consent_version", bvjlVar8);
        gZ = new bvjk("pf_follower_list_freshness", bvjlVar8);
        ha = new bvjk("pf_applicant_list_freshness", bvjlVar8);
        hb = new bvjk("pf_nf_notification_opt_out_shown_count", bvjpVar9);
        bvjk bvjkVar8 = e;
        hc = bvjkVar8;
        hd = bvjkVar8;
        he = new bvjk("last_foreground_location", bvjpVar9);
        hf = new bvjk("last_foreground_location_expiration_minutes", bvjpVar9);
        bvjl bvjlVar9 = b;
        new bvjk("your_places_list_details_context", bvjlVar9);
        new bvjk("categorical_search_history", bvjlVar9);
        new bvjk("popular_search", bvjlVar9);
        hg = new bvjk("restore_start_count", bvjlVar9);
        hh = new bvjk("restore_complete_count", bvjlVar9);
        hi = new bvjk("restore_non_empty_start_count", bvjlVar9);
        hj = new bvjk("restore_non_complete_start_count", bvjlVar9);
        hk = new bvjk("restore_invalid_preference", bvjlVar9);
        hl = new bvjk("restore_invalid_preference_restored", bvjlVar9);
        hm = new bvjk("restore_invalid_preference_still_invalid", bvjlVar9);
        hn = new bvjk("saved_parking_notifications", bvjpVar9);
        ho = new bvjk("saved_parking_notifications_opt_out_shown_count", bvjpVar9);
        hp = new bvjk("user_aware_of_parking_planner", bvjpVar9);
        hq = new bvjk("user_aware_of_saved_parking", bvjpVar9);
        hr = new bvjk("last_arrival_dashboard_timestamp_millis", bvjlVar9);
        hs = new bvjk("nontransit_route_options", new bvit(vux.class));
        ht = new bvjk("transit_route_options", bvjpVar9);
        hu = new bvjk("ugc_post_trip_questions_notification_opt_in", bvjlVar9);
        hv = new bvjk("ugc_post_trip_questions_notification_opt_out_shown_count", bvjpVar9);
        new bvjk("ugc_tasks_nearby_need_notification_opt_in", bvjpVar9);
        hw = new bvjk("ugc_tasks_nearby_need_notification_manually_changed_opting_status", bvjpVar9);
        hx = new bvjk("ugc_tasks_nearby_need_notification_ringtone", bvjpVar9);
        hy = new bvjk("ugc_tasks_nearby_need_notification_vibration", bvjpVar9);
        hz = new bvjk("ugc_tasks_nearby_need_notification_active_hour_start", bvjpVar9);
        hA = new bvjk("ugc_tasks_nearby_need_notification_active_hour_end", bvjpVar9);
        hB = new bvjk("ugc_tasks_nearby_need_exclude_home", bvjpVar9);
        hC = new bvjk("ugc_tasks_nearby_need_exclude_work", bvjpVar9);
        hD = new bvjk("ugc_tasks_nearby_need_state", bvjpVar9);
        hE = bvjkVar8;
        hF = bvjkVar8;
        bvjp bvjpVar10 = c;
        hG = new bvjk("ugc_disclosure_shown_lists", bvjpVar10);
        hH = new bvjk("ugc_disclosure_shown_qa", bvjpVar10);
        hI = new bvjk("ugc_disclosure_shown_reviews", bvjpVar10);
        hJ = new bvjk("ugc_disclosure_shown_photos", bvjpVar10);
        hK = new bvjk("ugc_disclosure_shown_creator_zone", bvjpVar10);
        hL = new bvjk("ugc_public_profile_opt_in", bvjlVar9);
        hM = new bvjk("profile_privacy_opt_in", bvjlVar9);
        new bvjk("maps_badges_notification_opt_in", bvjlVar9);
        hN = new bvjk("maps_badges_notification_opt_out_shown_count", bvjpVar10);
        hO = new bvjk("wheelchair_accessibility_opt_in", bvjpVar10);
        hP = new bvjk("local_guides_perks_notification_opt_out_shown_count", bvjpVar10);
        hQ = new bvjk("post_contribution_impact_notification_opt_in", bvjlVar9);
        hR = new bvjk("post_contribution_impact_notification_opt_out_shown_count", bvjpVar10);
        new bvjk("d2d_goldfinger_card_dismissed", bvjlVar9);
        new bvjk("ugc_home_street_notification_opt_in", bvjlVar9);
        hS = new bvjk("ugc_home_street_notification_opt_out_shown_count", bvjlVar9);
        new bvjk("ugc_home_street_notification_timestamp_ms", bvjlVar9);
        new bvjk("ugc_home_street_notification_shown_campaigns", bvjlVar9);
        new bvjk("ugc_home_street_notification_campaigns_sent", bvjlVar9);
        hT = new bvjk("ugc_rap_webview_base_url", bvjlVar9);
        hU = new bvjk("ugc_rap_override_webview_url", bvjlVar9);
        new bvjk("ugc_aaa_webview_base_url", bvjlVar9);
        new bvjk("ugc_aaa_override_webview_url", bvjlVar9);
        hV = bvjkVar8;
        hW = bvjkVar8;
        new bvjk("sticky_enable_two_wheeler_mode", bvjlVar9);
        hX = new bvjk("two_wheeler_route_obtained", bvjpVar10);
        hY = new bvjk("user_aware_of_two_wheeler", bvjpVar10);
        hZ = new bvjk("transit_route_obtained", bvjpVar10);
        ia = new bvjk("user_aware_of_transit", bvjpVar10);
        ib = new bvjk("user_aware_of_wimt_promo", bvjpVar10);
        new bvjk("commute_setup_v0_promo_gf_suppress", bvjlVar9);
        ic = new bvjk("commute_setup_v1_promo_gf_suppress", bvjlVar9);
        bvjl bvjlVar10 = b;
        new bvjk("commute_setup_v0_promo_notif_suppress", bvjlVar10);
        id = new bvjk("commute_hub_last_used_travel_mode", bvjlVar10);
        ie = new bvjk("commute_hub_transit_tab_travel_mode_prompt", bvjlVar10);
        f1if = new bvjk("commute_travel_mode_nudge_bar", bvjlVar10);
        new bvjk("commute_settings_nudge_bar_dismiss", bvjlVar10);
        ig = new bvjk("commute_settings_unset_home_work_nudge_bar_dismiss", bvjlVar10);
        ih = new bvjk("commute_settings_stale_vague_home_work_nudge_bar_click", bvjlVar10);
        ii = new bvjk("commute_settings_stale_vague_home_work_nudge_bar_dismiss", bvjlVar10);
        ij = new bvjk("commute_settings_unset_route_nudge_bar_dismiss", bvjlVar10);
        ik = new bvjk("user_let_maps_choose_route_to_home", bvjlVar10);
        il = new bvjk("user_let_maps_choose_route_to_work", bvjlVar10);
        im = new bvjk("commute_immersive_inferred_home_work_rejection_timestamp", bvjlVar10);
        in = new bvjk("enforce_incognito", bvjlVar10);
        io = new bvjk("primes_local_storage", bvjlVar10);
        ip = new bvjk("smartspace_commute_notification_last_disabled_timestamp", bvjlVar10);
        new bvjk("last_map_type_layer", bvjlVar10);
        new bvjk("last_map_details_layer", bvjlVar10);
        iq = new bvjk("pip_dismissed", bvjpVar10);
        ir = new bvjk("thick_tiles_states", bvjpVar10);
        is = new bvjk("is_user_aware_of_license_plate_restrictions", bvjlVar10);
        new bvjk("force_experience_sheet", bvjlVar10);
        it = new bvjk("ar_settings", bvjpVar10);
        iu = new bvjk("arwn_settings", bvjpVar10);
        iv = new bvjk("business_message_from_merchant_notifications_enabled", bvjlVar10);
        iw = new bvjk("business_message_from_customer_notifications", bvjlVar10);
        ix = new bvjk("dismiss_business_messaging_toast_promo_for_business", bvjlVar10);
        iy = new bvjk("business_messaging_inline_response_sent", bvjlVar10);
        iz = new bvjk("business_messaging_gcm_registration_id", bvjlVar10);
        iA = new bvjk("business_messaging_gcm_registration_version", bvjlVar10);
        new bvjk("review_reply_notifications_enabled", bvjlVar10);
        new bvjk("suppress_update_commute_travel_mode_notification", bvjlVar10);
        iB = new bvjk("update_commute_travel_mode_notification_last_timestamp_ms", bvjpVar10);
        new bvjk("local_discovery_at_a_place_notifications", bvjpVar10);
        new bvjk("local_discovery_foodie_favorite_notifications", bvjpVar10);
        iC = new bvjk("local_discovery_at_a_place_notifications_opt_out_shown_count", bvjpVar10);
        bvjp bvjpVar11 = c;
        iD = new bvjk("local_discovery_foodie_favorite_notifications_opt_out_shown_count", bvjpVar11);
        new bvjk("local_discovery_newly_opened_places_notifications", bvjpVar11);
        iE = new bvjk("local_discovery_newly_opened_places_notifications_opt_out_shown_count", bvjpVar11);
        iF = new bvjk("local_discovery_personalized_recommendation_notifications", bvjpVar11);
        iG = new bvjk("local_discovery_personalized_recommendation_notifications_opt_out_shown_count", bvjpVar11);
        new bvjk("local_discovery_upcoming_events_notifications", bvjpVar11);
        iH = new bvjk("local_discovery_upcoming_events_notifications_opt_out_shown_count", bvjpVar11);
        new bvjk("local_discovery_places_in_the_news_notifications_opt_out_shown_count", bvjpVar11);
        new bvjk("local_discovery_public_list_notifications", bvjpVar11);
        iI = new bvjk("local_discovery_public_list_notifications_opt_out_shown_count", bvjpVar11);
        iJ = new bvjk("local_discovery_saved_place_nearby_notifications", bvjpVar11);
        iK = new bvjk("local_discovery_saved_place_nearby_notifications_opt_out_shown_count", bvjpVar11);
        new bvjk("local_discovery_travel_notifications", bvjpVar11);
        new bvjk("local_discovery_trending_places_notifications", bvjpVar11);
        iL = new bvjk("local_discovery_trending_places_notifications_opt_out_shown_count", bvjpVar11);
        new bvjk("local_discovery_new_post_notifications", bvjpVar11);
        iM = new bvjk("local_discovery_new_post_notifications_opt_out_shown_count", bvjpVar11);
        new bvjk("local_discovery_welcome_to_destination_notifications", bvjpVar11);
        new bvjk("local_discovery_welcome_to_destination_notifications_opt_out_shown_count", bvjpVar11);
        iN = new bvjk("has_even_license_plate", bvjpVar11);
        iO = new bvjk("has_odd_license_plate", bvjpVar11);
        iP = new bvjk("user_has_ever_set_odd_even_license_plate_value", bvjpVar11);
        iQ = new bvjk("user_has_ever_set_rodizio_license_plate_value", bvjpVar11);
        iR = new bvjk("rodizio_license_plate", bvjpVar11);
        iS = new bvjk("user_has_ever_set_manila_number_coding_license_plate_value", bvjpVar11);
        iT = new bvjk("manila_number_coding_license_plate", bvjpVar11);
        iU = new bvjk("personal_score_onboarding_started", bvjpVar11);
        iV = new bvjk("personal_score_exemplars_rated", bvjpVar11);
        iW = f;
        iX = new bvjk("incident_vote_request_timestamps", bvjlVar10);
        iY = new bvjk("report_incident_cooloff_settings", bvjlVar10);
        iZ = new bvjk("report_incident_card_shown", bvjpVar11);
        ja = new bvjk("seen_incident_types_in_midtrip_report", bvjpVar11);
        jb = new bvjk("personal_score_search_result_promo_dismissed", bvjpVar11);
        bvjl bvjlVar11 = b;
        jc = new bvjk("commute_notification_current_stage_list", bvjlVar11);
        jd = new bvjk("force_personal_score_tool_tip", bvjlVar11);
        je = new bvjk("show_media_controls", bvjlVar11);
        jf = new bvjk("default_media_app", bvjlVar11);
        jg = new bvjk("media_promo_times_shown", bvjlVar11);
        jh = new bvjk("media_promo_was_interacted_with", bvjlVar11);
        ji = new bvjk("media_spotify_play_store_link_timestamp", bvjlVar11);
        jj = new bvjk("bypass_media_app_allowlist", bvjlVar11);
        jk = new bvjk("bypass_media_app_validation", bvjlVar11);
        bvjk bvjkVar9 = e;
        jl = bvjkVar9;
        jm = new bvjk("custom_chevron_opt_in", bvjlVar11);
        jn = new bvjk("custom_chevron_model_name", bvjlVar11);
        jo = new bvjk("experience_sheet_suggest_photo_promo_shown", bvjpVar11);
        jp = new bvjk("merchant_mode_num_businesses", bvjlVar11);
        jq = new bvjk("merchant_experience_action_flow_completed_marker", bvjlVar11);
        jr = bvjkVar9;
        js = new bvjk("merchant_account_list", bvjlVar11);
        jt = new bvjk("merchant_mode_business_unobfuscated_gmb_listing_ids", bvjlVar11);
        ju = new bvjk("merchant_mode_messaging_manages_gmm_listing", bvjlVar11);
        jv = new bvjk("merchant_mode_messaging_cleared_history", bvjlVar11);
        jw = new bvjk("merchant_account_list_last_refresh_ms", bvjlVar11);
        jx = new bvjk("merchant_account_list_last_refresh_device_accounts", bvjlVar11);
        jy = new bvjk("merchant_mode_messaging_listings_edited_welcome_message", bvjlVar11);
        bvjp bvjpVar12 = c;
        new bvjk("rap_add_missing_road_polyline_add_tip_count", bvjpVar12);
        jz = new bvjk("votable_incident_prompt_disclaimer_count", bvjpVar12);
        jA = new bvjk("midtrip_report_prompt_disclaimer_count", bvjpVar12);
        new bvjk("directions_sentiment_survey_trip_count", bvjpVar12);
        jB = new bvjk("incident_callout_long_vote_label_timestamps", bvjpVar12);
        jC = new bvjk("answered_ugc_post_trip_questions_session_ids", bvjpVar12);
        jD = new bvjk("location_sharing_diversion_criteria", bvjlVar11);
        new bvjk("assistant_driving_mode_plate_height", bvjlVar11);
        jE = new bvjk("assistant_driving_mode_bluetooth_latency_calibration_force_calibration", bvjlVar11);
        new bvjk("assistant_driving_mode_bluetooth_latency_calibration_force_delay", bvjlVar11);
        new bvjk("always_show_assistant_driving_mode_oobe_promo_in_directions", bvjlVar11);
        jF = new bvjk("always_show_assistant_driving_mode_opt_in_dialog", bvjlVar11);
        new bvjk("assistant_driving_mode_oobe_interacted_with", bvjlVar11);
        new bvjk("car_road_state", bvjpVar12);
        jG = new bvjk("car_store_signed_out_recents", bvjlVar11);
        jH = new bvjk("saved_personal_driving_route_to_home", bvjpVar12);
        jI = new bvjk("saved_personal_driving_route_to_work", bvjpVar12);
        jJ = new bvjk("saved_personal_driving_routes_force_enable", bvjlVar11);
        jK = new bvjk("saved_personal_driving_routes_on_save_toeast_shown", bvjlVar11);
        jL = new bvjk("saved_personal_driving_routes_on_undo_save_toast_shown", bvjlVar11);
        jM = new bvjk("go_tab_welcome_shown", bvjlVar11);
        jN = new bvjk("implicit_commute_to_work_trip_pinned", bvjpVar12);
        jO = new bvjk("implicit_commute_to_home_trip_pinned", bvjpVar12);
        new bvjk("off_route_alerts_user_has_arrived", bvjlVar11);
        new bvjk("off_route_alerts_exit_warning_dont_ask_again", bvjpVar12);
        jP = new bvjk("eyes_free_walking_guidance_enabled", bvjpVar12);
        jQ = new bvjk("already_seen_trips", bvjpVar12);
        jR = new bvjk("eyes_free_walking_guidance_promo_dismissed", bvjpVar12);
        jS = new bvjk("finish_directions_merge_result", bvjlVar11);
        new bvjk("transit_space_enable_focus_state", bvjlVar11);
        new bvjk("transit_space_show_new_badge", bvjlVar11);
        new bvjk("transit_space_onboarding_card_shown", bvjlVar11);
        new bvjk("transit_space_onboarding_card_dismissed", bvjlVar11);
        new bvjk("transit_space_initial_tab", bvjlVar11);
        jT = bvjkVar9;
        jU = new bvjk("user_prefs_last_read_timestamp_ms", bvjlVar11);
        jV = new bvjk("in_app_survey_notification", bvjpVar12);
        jW = new bvjk("ev_connector_info_last_read_timestamp_ms", bvjlVar11);
        jX = new bvjk("ev_connector_info_value", bvjlVar11);
        bvjl bvjlVar12 = b;
        jY = new bvjk("notifications_os_enabled_last_logged", bvjlVar12);
        jZ = new bvjk("demo_ev_connector_types", bvjlVar12);
        ka = new bvjk("ev_profile_applciation_tooltip_shown", bvjpVar12);
        kb = bvjkVar9;
        new bvjk("side_menu_tutorial_have_clicked_other_tabs", bvjpVar12);
        new bvjk("side_menu_tutorial_have_clicked_og", bvjpVar12);
        kc = bvjkVar9;
        kd = f;
        ke = new bvjk("creator_zone_helper_message_tooltip_last_timestamp_ms", bvjlVar12);
        kf = new bvjk("creator_zone_helper_message_tooltip_shown_count", bvjlVar12);
        bvjk bvjkVar10 = e;
        kg = bvjkVar10;
        kh = new bvjk("transit_trip_attributes_banner_shown", bvjpVar12);
        ki = bvjkVar10;
        kj = new bvjk("ugc_tab_onboarding_card_enabled", bvjlVar12);
        kk = new bvjk("car_most_recent_arrival_time_ms", bvjlVar12);
        kl = bvjkVar10;
        km = new bvjk("transit_ugc_feedback_last_directions_ei", bvjpVar12);
        kn = new bvjk("saved_tab_location_history_promo_dismissal_timestamp_ms", bvjpVar12);
        ko = bvjkVar10;
        kp = bvjkVar10;
        kq = new bvjk("promoted_places_user_education_hard_dismissed", bvjpVar12);
        kr = new bvjk("promoted_places_user_education_soft_dismissals", bvjpVar12);
        new bvjk("work_manager_task_reset_count", bvjpVar12);
        ks = new bvjk("car_widget_suggested_destinations_is_collapsed", bvjlVar12);
        kt = new bvjk("notifications_inbox_has_unread", bvjpVar12);
        ku = new bvjk("last_saved_trip_timestamp_ms", bvjlVar12);
        kv = new bvjk("last_accessed_saved_trip_timestamp_ms", bvjlVar12);
        kw = bvjkVar10;
        kx = new bvjk("assistive_shortcuts_count", bvjlVar12);
        ky = bvjkVar10;
    }

    public bvjk(String str, bviw bviwVar) {
        this.kz = str;
        this.kA = bviwVar;
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    public static boolean b(String str) {
        if (!str.equals(f.kz)) {
            return !str.equals(e.kz);
        }
        bvoo.h("You are using invalid setting key.", new Object[0]);
        return false;
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    public final boolean a() {
        return b(this.kz);
    }

    public final boolean equals(@dzsi Object obj) {
        if (obj instanceof bvjk) {
            return this.kz.equals(((bvjk) obj).kz);
        }
        Object[] objArr = new Object[1];
        objArr[0] = obj == null ? "null" : obj.getClass().getSimpleName();
        bvoo.h("setting key should be only compared with key object, However, %s is given.", objArr);
        return false;
    }

    public final int hashCode() {
        return this.kz.hashCode();
    }

    public final String toString() {
        a();
        return this.kz;
    }
}
