package defpackage;
/* compiled from: PG */
/* renamed from: ckdz  reason: default package */
/* loaded from: classes4.dex */
public final class ckdz {
    public static final ckgz A;
    public static final ckgz B;
    public static final ckha C;
    public static final ckha D;
    public static final ckha E;
    public static final ckhg F;
    public static final ckhg G;
    public static final ckhg H;
    public static final ckgz I;
    public static final ckha J;
    public static final ckgz K;
    public static final ckgz L;
    public static final ckgz M;
    public static final ckgz N;
    public static final ckgu O;
    public static final ckgz P;
    public static final ckgz Q;
    public static final ckhg R;
    public static final ckhg S;
    public static final ckgz T;
    public static final ckgu U;
    public static final ckgu V;
    public static final ckhg W;
    public static final ckgz X;
    public static final ckgz Y;
    public static final ckha Z;
    public static final ckgu a;
    public static final ckgz aA;
    public static final ckgz aB;
    public static final ckgz aC;
    public static final ckhg aD;
    public static final ckgz aE;
    public static final ckha aF;
    public static final ckgt aG;
    public static final ckgu aH;
    public static final ckgu aI;
    public static final ckgz aJ;
    public static final ckgz aK;
    public static final ckgz aL;
    public static final ckgz aM;
    public static final ckha aa;
    public static final ckha ab;
    public static final ckha ac;
    public static final ckgu ad;
    public static final ckgu ae;
    public static final ckgu af;
    public static final ckgu ag;
    public static final ckgu ah;
    public static final ckgu ai;
    public static final ckgz aj;
    public static final ckgz ak;
    public static final ckgu al;
    public static final ckgz am;
    public static final ckgz an;
    public static final ckgz ao;
    public static final ckhg ap;
    public static final ckgu aq;
    public static final ckgu ar;
    public static final ckgz as;
    public static final ckgu at;
    public static final ckha au;
    public static final ckgu av;
    public static final ckgz aw;
    public static final ckgu ax;
    public static final ckgz ay;
    public static final ckgz az;
    public static final ckgz b;
    public static final ckgz c;
    public static final ckgu d;
    public static final ckgz e;
    public static final ckgz f;
    public static final ckgz g;
    public static final ckgu h;
    public static final ckgz i;
    public static final ckgz j;
    public static final ckgz k;
    public static final ckgz l;
    public static final ckgz m;
    public static final ckha n;
    public static final ckha o;
    public static final ckgz p;
    public static final ckgz q;
    public static final ckgz r;
    public static final ckgz s;
    public static final ckgz t;
    public static final ckgz u;
    public static final ckgz v;
    public static final ckgt w;
    public static final ckgt x;
    public static final ckgt y;
    public static final ckgz z;

    static {
        new ckgu("PhotoGalleryThumbnailLoadFailureCount", ckgy.BILLIONS);
        new ckgu("PhotoLightboxImageLoadingFailureCount", ckgy.BILLIONS);
        a = new ckgu("PhotoPickTakeHelperNullOriginalUriOnHandleEditPhotoResultCount", ckgy.BILLIONS);
        b = new ckgz("PhotoLiveCameraStatus", ckgy.BILLIONS);
        c = new ckgz("PhotoShareIntentEmbeddedMetadata", ckgy.BILLIONS);
        d = new ckgu("PhotoTakenNotificationTimeouts", ckgy.BILLIONS);
        e = new ckgz("PhotoTakenNotificationReceiverStatus", ckgy.BILLIONS);
        f = new ckgz("PhotoTakenNotificationReceiverDisabledReason", ckgy.BILLIONS);
        g = new ckgz("PhotoTakenNotificationServiceStatus", ckgy.BILLIONS);
        h = new ckgu("PhotoTakenNotificationStartNotifierSecurityExceptionCount", ckgy.BILLIONS);
        i = new ckgz("PhotoTakenNotificationServiceNotStartingReason", ckgy.BILLIONS);
        j = new ckgz("PhotoTakenNotificationPhotoResult", ckgy.BILLIONS);
        new ckgz("PhotoTakenNotificationClassifierRawConfidence", ckgy.BILLIONS);
        k = new ckgz("PhotoTakenNotificationBitmapLoadStatus", ckgy.BILLIONS);
        l = new ckgz("PhotoTakenNotificationThumbnailStatus", ckgy.BILLIONS);
        new ckgz("PhotoTakenNotificationMergeStatus", ckgy.BILLIONS);
        new ckgz("PhotoTakenNotificationContentQueryStatus", ckgy.BILLIONS);
        m = new ckgz("PhotoTakenNotificationPhotoCount", ckgy.BILLIONS);
        n = new ckha("PhotoTakenNotificationJobServiceProcessingDelayMins", ckgy.BILLIONS, new cnkg(1, -1, 1000));
        o = new ckha("PhotoTakenNotificationIntentServiceProcessingDelayMins", ckgy.BILLIONS, new cnkg(1, 0, 1000));
        p = new ckgz("PhotoTakenNotificationIntentServicePhotoStatus", ckgy.BILLIONS);
        q = new ckgz("PhotoTakenNotificationJobServiceStatus", ckgy.BILLIONS);
        r = new ckgz("PhotoTakenNotificationJobServiceJobStatus", ckgy.BILLIONS);
        s = new ckgz("PhotoTakenNotificationJobServiceTriggerUris", ckgy.BILLIONS);
        t = new ckgz("PhotoTakenNotificationJobServicePhotoUris", ckgy.BILLIONS);
        u = new ckgz("UgcMediaTakenNotificationJobServiceVideoUris", ckgy.BILLIONS);
        new ckgz("PhotoTakenNotificationPermissionPromptResult", ckgy.BILLIONS);
        v = new ckgz("PhotoTakenNotificationWithoutPermissionContribution", ckgy.BILLIONS);
        w = new ckgt("PhotoTakenNotificationPhotoContainingLatlng", ckgy.BILLIONS);
        x = new ckgt("PhotoTakenNotificationPhotoContainingCaptureTimestamp", ckgy.BILLIONS);
        y = new ckgt("PhotoTakenNotificationPhotoContainingLastModifiedTimestamp", ckgy.BILLIONS);
        z = new ckgz("PhotoTakenDevicePhotoDatabasePhotoSaveStatus", ckgy.BILLIONS);
        A = new ckgz("PhotoTakenDevicePhotoDatabaseImageLabelSaveSuccesses", ckgy.BILLIONS);
        B = new ckgz("PhotoTakenDevicePhotoDatabaseImageLabelSaveFailures", ckgy.BILLIONS);
        C = new ckha("PhotoTakenDevicePhotoDatabaseRowsContainedAfterSave", ckgy.BILLIONS, new cnkg(1, 0, 1000));
        D = new ckha("PhotoTakenDevicePhotoDatabaseRowsContainedBeforeRemoval", ckgy.BILLIONS, new cnkg(1, 0, 1001));
        E = new ckha("PhotoTakenDevicePhotoDatabaseRowsContainedAfterRemoval", ckgy.BILLIONS, new cnkg(1, 0, 1000));
        F = new ckhg("PhotoTakenDevicePhotoDatabaseTimeTakenToClean", ckgy.BILLIONS);
        G = new ckhg("PhotoTakenDevicePhotoDatabaseTimeTakenToRetrievePhotoData", ckgy.BILLIONS);
        H = new ckhg("PhotoTakenDevicePhotoDatabaseTimeTakenToSavePhotoData", ckgy.BILLIONS);
        I = new ckgz("PhotoTakenDevicePhotoDatabaseRowRemovalReasonFromCleaning", ckgy.BILLIONS);
        J = new ckha("PhotoTakenDevicePhotoDatabaseRowsRemovedFromCleaning", ckgy.BILLIONS, new cnkg(1, 0, 1000));
        K = new ckgz("PhotoTakenDevicePhotoDatabaseCleanerStatus", ckgy.BILLIONS);
        L = new ckgz("GenericPhotoTakenNotificationFilterStatus", ckgy.BILLIONS);
        M = new ckgz("PhotoTakenNotificationEnableStatus", ckgy.BILLIONS);
        N = new ckgz("PhotoUploadInvalidFeatureIdCount", ckgy.BILLIONS);
        O = new ckgu("ReviewAtAPlaceNotificationConversionCount", ckgy.BILLIONS);
        P = new ckgz("ReviewAtAPlaceNotificationConversionMethod", ckgy.BILLIONS);
        Q = new ckgz("PhotoUploadSourceAndCount", ckgy.BILLIONS);
        new ckgz("PhotoMognetStatus", ckgy.BILLIONS);
        R = new ckhg("PhotoGalleryThumbnailLoadTime", ckgy.BILLIONS);
        S = new ckhg("PhotoLightboxImageLoadTime", ckgy.BILLIONS);
        T = new ckgz("PhotoShareFlowStates", ckgy.BILLIONS);
        U = new ckgu("PhotoTakenFindImageDestinationFailureCount", ckgy.BILLIONS);
        V = new ckgu("PhotoTakenAndroidFaceDetectorFallbackCount", ckgy.BILLIONS);
        W = new ckhg("PhotoTakenNotificationProcessingTime", ckgy.BILLIONS);
        X = new ckgz("PublishPrivatePhotoPlacesCount", ckgy.BILLIONS);
        Y = new ckgz("PublishPrivatePhotoDismissPhotoCount", ckgy.BILLIONS);
        Z = new ckha("PublishPrivatePhotoUniquePlacesCountOnPublishClick", ckgy.BILLIONS, new cnkg(1, 0, 500));
        aa = new ckha("PublishPrivatePhotoPhotoCountOnPublishClick", ckgy.BILLIONS, new cnkg(1, 0, 999));
        ab = new ckha("TodoPhotoFirstPageWithNumPhotos", ckgy.BILLIONS, new cnkg(1, 0, 100));
        ac = new ckha("TodoPhotoFirstPageWithNumPhotosPreselected", ckgy.BILLIONS, new cnkg(1, 0, 100));
        new ckgz("OpeningHoursNotificationShowStatus", ckgy.BILLIONS);
        new ckgu("OpeningHoursNotificationHideCount", ckgy.BILLIONS);
        ad = new ckgu("OpeningHoursNotificationConversionCount", ckgy.BILLIONS);
        ae = new ckgu("OpeningHoursNotificationAddConversionCount", ckgy.BILLIONS);
        af = new ckgu("OpeningHoursNotificationModifyConversionCount", ckgy.BILLIONS);
        ag = new ckgu("OpeningHoursNotificationVerifyConversionCount", ckgy.BILLIONS);
        ah = new ckgu("TodoPhotoNotificationImpressionPreNetworkCount", ckgy.BILLIONS);
        ai = new ckgu("TodoPhotoNotificationImpressionPreImageFetchCount", ckgy.BILLIONS);
        aj = new ckgz("TodoPhotoNotificationImpressionPreHandleStatus", ckgy.BILLIONS);
        ak = new ckgz("TodoPhotoNotificationImageFetchStatus", ckgy.BILLIONS);
        new ckgz("FactualModerationNotificationShowStatus", ckgy.BILLIONS);
        new ckgu("FactualModerationNotificationHideCount", ckgy.BILLIONS);
        al = new ckgu("FactualModerationNotificationConversionCount", ckgy.BILLIONS);
        new ckgz("FactualModerationPendingEditsWithNoVoteCountOnShow", ckgy.BILLIONS);
        new ckgz("FactualModerationPendingEditsWithNoVoteCountOnClick", ckgy.BILLIONS);
        new ckgz("ReviewAtAPlaceNotificationDwellStatus", ckgy.BILLIONS);
        new ckgz("ReviewAtAPlaceNotificationShowStatus", ckgy.BILLIONS);
        am = new ckgz("UgcPhotoUploadSourceAndCount", ckgy.BILLIONS);
        an = new ckgz("ReadExternalStoragePermissionAcceptance", ckgy.BILLIONS);
        ao = new ckgz("ReadExternalStoragePermissionRejection", ckgy.BILLIONS);
        new ckgz("ReadExternalStoragePermissionPermanentRejection", ckgy.BILLIONS);
        new ckha("PhotoNumLocalPhotos", ckgy.BILLIONS);
        ap = new ckhg("PhotoPickerGalleryLoadTime", ckgy.BILLIONS);
        aq = new ckgu("EmployeeHoursNotificationConversionCount", ckgy.BILLIONS);
        ar = new ckgu("BusinessOwnerHoursNotificationConversionCount", ckgy.BILLIONS);
        new ckgz("ReviewAtAPlaceNotificationImageUriRetrievedMode", ckgy.BILLIONS);
        new ckgu("ReviewAtAPlaceNotificationIconCreationFailure", ckgy.BILLIONS);
        as = new ckgz("ReviewAtAPlaceNotificationInlineExternalContextRetrievalStatus", ckgy.BILLIONS);
        at = new ckgu("ReviewAtAPlaceNotificationInlineStarClickedWhenDeviceIsLocked", ckgy.BILLIONS);
        au = new ckha("ReviewAtAPlaceNotificationInlineSubmittingReviewLength", ckgy.BILLIONS);
        av = new ckgu("ReviewAtAPlaceNotificationFailureToLoadCachedLargeIcon", ckgy.BILLIONS);
        aw = new ckgz("TwoAtATimeReviewSubmitterRequestDroppedReason", ckgy.BILLIONS);
        new ckgz("AtAPlacePersonalPlacesFirstSyncCompletedStatus", ckgy.BILLIONS);
        ax = new ckgu("UgcGcorePlacePickerLatlngCount", ckgy.BILLIONS);
        ay = new ckgz("SemanticLocationControllerRegistrationByComponent", ckgy.BILLIONS);
        az = new ckgz("SemanticLocationControllerDoubleRegistrationByComponent", ckgy.BILLIONS);
        aA = new ckgz("SemanticLocationControllerDeregistrationByComponent", ckgy.BILLIONS);
        aB = new ckgz("SemanticLocationControllerBadDeregistrationByComponent", ckgy.BILLIONS);
        aC = new ckgz("SemanticLocationControllerStartListeningByComponent", ckgy.BILLIONS);
        aD = new ckhg("SemanticLocationControllerTimeSpentListening", ckgy.BILLIONS);
        aE = new ckgz("NearbyNeedFetchUgcTaskSetsStatus", ckgy.BILLIONS);
        aF = new ckha("TodoListDevicePhotosItemPhotoCount", ckgy.BILLIONS, new cnkg(1, 0, 100));
        aG = new ckgt("TodoListStoragePermissionGranted", ckgy.BILLIONS);
        aH = new ckgu("PhotoTakenOnDeviceIcaClassifierNotOperationalCount", ckgy.BILLIONS);
        new ckgz("BulkUploadGcorePlacePickerOpenStatus", ckgy.BILLIONS);
        aI = new ckgu("SinglePlacePhotoPickerPlacePickedCount", ckgy.BILLIONS);
        aJ = new ckgz("SinglePlacePhotoPickerGcorePlacePickerResultReceiveStatus", ckgy.BILLIONS);
        aK = new ckgz("StoragePermissionFishingRequestShownStatus", ckgy.BILLIONS);
        aL = new ckgz("WeeklyTodolistWeekOffsetImpression", ckgy.BILLIONS);
        aM = new ckgz("WeeklyTodolistWeekOffsetCompletion", ckgy.BILLIONS);
    }
}
