package defpackage;
/* compiled from: PG */
/* renamed from: ckee  reason: default package */
/* loaded from: classes.dex */
public final class ckee {
    public static final ckgz A;
    public static final ckgz B;
    public static final ckgz C;
    public static final ckgz D;
    public static final ckgz E;
    public static final ckgz F;
    public static final ckgz G;
    public static final ckgz H;
    public static final ckgz I;
    public static final ckgz J;
    public static final ckgz K;
    public static final ckgz L;
    public static final ckgz M;
    public static final ckhf N;
    public static final ckhf O;
    public static final ckhf P;
    public static final ckhf Q;
    public static final ckhf R;
    public static final ckhf S;
    public static final ckhf T;
    public static final ckhf U;
    public static final ckhf V;
    public static final ckhf W;
    public static final ckhf X;
    public static final ckhf Y;
    public static final ckgz Z;
    public static final ckgz aA;
    public static final ckhf aB;
    public static final ckhf aC;
    public static final ckgz aD;
    public static final ckgz aE;
    public static final ckgz aF;
    public static final ckgz aG;
    public static final ckgz aa;
    public static final ckgz ab;
    public static final ckgz ac;
    public static final ckgz ad;
    public static final ckhg ae;
    public static final ckgz af;
    public static final ckhg ag;
    public static final ckhg ah;
    public static final ckgz ai;
    public static final ckgz aj;
    public static final ckgz ak;
    public static final ckgz al;
    public static final ckgz am;
    public static final ckgz an;
    public static final ckgz ao;
    public static final ckgz ap;
    public static final ckgz aq;
    public static final ckgz ar;
    public static final ckgz as;
    public static final ckgz at;
    public static final ckgz au;
    public static final ckgz av;
    public static final ckhg aw;
    public static final ckhg ax;
    public static final ckha ay;
    public static final ckhf az;
    public static final ckhf o;
    public static final ckha p;
    public static final ckhf q;
    public static final ckgz r;
    public static final ckgz s;
    public static final ckgz t;
    public static final ckgz u;
    public static final ckgz v;
    public static final ckgz w;
    public static final ckgz x;
    public static final ckgz y;
    public static final ckgz z;
    public static final ckha a = new ckha("CarActivityOnCreateTime", ckgy.CAR);
    public static final ckhg b = new ckhg("CarActivityOnNewIntentTime", ckgy.CAR);
    public static final ckhg c = new ckhg("CarActivityOnStartTime", ckgy.CAR);
    public static final ckhg d = new ckhg("CarActivityOnResumeTime", ckgy.CAR);
    public static final ckhg e = new ckhg("CarActivityOnPauseTime", ckgy.CAR);
    public static final ckhg f = new ckhg("CarActivityOnStopTime", ckgy.CAR);
    public static final ckhg g = new ckhg("CarActivityOnDestroyTime", ckgy.CAR);
    public static final ckhg h = new ckhg("CarActivityOnConfigurationChangedTime", ckgy.CAR);
    public static final ckhg i = new ckhg("CarActivityInputFocusChangedTime", ckgy.CAR);
    public static final ckhf j = new ckhf("CarActivityCreationToFirstFrameTime", ckgy.CAR);
    public static final ckhf k = new ckhf("CarActivityCreationToResumeTime", ckgy.CAR);
    public static final ckhg l = new ckhg("CarActivityDelayedUiWorkTime", ckgy.CAR);
    public static final ckhf m = new ckhf("CarActivityCreationToFirstFullUiFrameTime", ckgy.CAR);
    public static final ckhf n = new ckhf("CarActivityCreationToFirstMapTileTime", ckgy.CAR);

    static {
        new ckhf("CarActivityRestartToResumeTime", ckgy.CAR);
        o = new ckhf("CarNavigationProviderServiceCreationToGmmCarActivityCreationTime", ckgy.CAR);
        p = new ckha("CarNavigationProviderServiceOnCreateTime", ckgy.CAR);
        q = new ckhf("CarNavigationProviderServiceCreationToFirstNotificationPostedTime", ckgy.CAR);
        new ckhg("CarNavStateManagerGenerateBundle", ckgy.CAR);
        new ckhg("CarNavStateManagerOnNavigationServiceStateEvent", ckgy.CAR);
        r = new ckgz("CarProjectionIntentReceivedCount", ckgy.CAR);
        new ckgz("CarProjectionVoiceActionReceivedCount", ckgy.CAR);
        s = new ckgz("CarGmmActionNonVoiceReceivedCount", ckgy.CAR);
        t = new ckgz("CarGmmActionVoiceReceivedCount", ckgy.CAR);
        u = new ckgz("CarDirectionsIntentDestinationsCount", ckgy.CAR);
        v = new ckgz("CarDirectionsIntentResultVoice", ckgy.CAR);
        w = new ckgz("CarDirectionsIntentResultNonVoice", ckgy.CAR);
        x = new ckgz("CarPhoneIntentReceivedCount", ckgy.CAR);
        y = new ckgz("CarPhoneVoiceActionReceivedCount", ckgy.CAR);
        z = new ckgz("CarJourneySharingSurfacedResult", ckgy.CAR);
        A = new ckgz("CarJourneySharingNumPeopleSuggestions", ckgy.CAR);
        B = new ckgz("CarJourneySharingSelectedEmailLength", ckgy.CAR);
        C = new ckgz("CarSuggestionInteractionType", ckgy.CAR);
        new ckgz("CarSuggestionImpressionType", ckgy.CAR);
        new ckgz("CarSuggestionTriggerType", ckgy.CAR);
        new ckgz("CarSignInActionResult", ckgy.CAR);
        new ckgz("CarPersonalPlacesNumLabeledPlaces", ckgy.CAR);
        new ckgz("CarPersonalPlacesNumSavedPlaces", ckgy.CAR);
        D = new ckgz("CarPersonalPlacesNumNicknamePlaces", ckgy.CAR);
        E = new ckgz("CarPersonalPlacesNumContacts", ckgy.CAR);
        F = new ckgz("CarPersonalPlacesNumStarredPlaces", ckgy.CAR);
        G = new ckgz("CarPersonalPlacesNumFavoritePlaces", ckgy.CAR);
        H = new ckgz("CarPersonalPlacesNumWantToGoPlaces", ckgy.CAR);
        I = new ckgz("CarPersonalPlacesNumCustomListPlaces", ckgy.CAR);
        J = new ckgz("CarPersonalPlacesListClicked", ckgy.CAR);
        K = new ckgz("CarKeyboardSuggestionType", ckgy.CAR);
        L = new ckgz("CarKeyboardClickedSuggestionType", ckgy.CAR);
        M = new ckgz("CarKeyboardClickedSuggestionQueryLength", ckgy.CAR);
        N = new ckhf("CarActivityCreationToRecentPlaceSelectedTime", ckgy.CAR);
        O = new ckhf("CarActivityCreationToKeyboardOpenedTime", ckgy.CAR);
        P = new ckhf("CarActivityCreationToFavoritePlaceSelectedTime", ckgy.CAR);
        Q = new ckhf("CarActivityCreationToStarredPlaceSelectedTime", ckgy.CAR);
        R = new ckhf("CarActivityCreationToWantToGoPlaceSelectedTime", ckgy.CAR);
        S = new ckhf("CarActivityCreationToCustomListPlaceSelectedTime", ckgy.CAR);
        T = new ckhf("CarActivityCreationToNicknamedPlaceSelectedTime", ckgy.CAR);
        U = new ckhf("CarActivityCreationToContactAddressSelectedTime", ckgy.CAR);
        V = new ckhf("CarActivityCreationToCategoryGasStationSelectedTime", ckgy.CAR);
        W = new ckhf("CarActivityCreationToCategoryRestaurantSelectedTime", ckgy.CAR);
        X = new ckhf("CarActivityCreationToCategoryGrocerySelectedTime", ckgy.CAR);
        Y = new ckhf("CarActivityCreationToCategoryCafeSelectedTime", ckgy.CAR);
        new ckgz("CarAuditRecordsLogged", ckgy.CAR);
        new ckgz("CarAuthEmbeddedSignOutReason", ckgy.CAR);
        new ckgz("CarAuthRecoverableGetTokenCheckResult", ckgy.CAR);
        new ckgz("CarAuthRemoveAccountOnUserRecoverableAuthExceptionResult", ckgy.CAR);
        Z = new ckgz("CarPermissionsGranted", ckgy.CAR);
        aa = new ckgz("CarRecentsDeduplicationReason", ckgy.CAR);
        ab = new ckgz("CarRecentsNewItemsDiffCount", ckgy.CAR);
        ac = new ckgz("CarRecentsNumRecents", ckgy.CAR);
        ad = new ckgz("CarRecentsResponseFailureType", ckgy.CAR);
        ae = new ckhg("CarPlaceDetailsDirectionsFetchTimer", ckgy.CAR);
        af = new ckgz("CarPlaceDetailsEntryPoint", ckgy.CAR);
        ag = new ckhg("CarPlaceDetailsNavigationStartTimerAutomaticNavigate", ckgy.CAR);
        ah = new ckhg("CarPlaceDetailsNavigationStartTimerManualNavigate", ckgy.CAR);
        ai = new ckgz("CarPlacemarkFetchSource", ckgy.CAR);
        aj = new ckgz("CarNavigationEntryPointSingleStop", ckgy.CAR);
        ak = new ckgz("CarNavigationEntryPointMultiStop", ckgy.CAR);
        al = new ckgz("CarVoiceActionExitNavigationResult", ckgy.CAR);
        new ckgz("CarExitNavigationInBackground", ckgy.CAR);
        am = new ckgz("CarPlaceDetailsFinalStateFromVoice", ckgy.CAR);
        an = new ckgz("CarPlaceDetailsFinalStateFromNonVoice", ckgy.CAR);
        ao = new ckgz("CarVoiceActionShowRoutesResult", ckgy.CAR);
        new ckgu("CarNavigationRepeatedWaypoints", ckgy.CAR);
        new ckgu("CarNavigationRepeatedWaypointsPlaceDetailsOverlay", ckgy.CAR);
        new ckhg("CarNavigationNewNavigationStartMethodToOldMethodTimer", ckgy.CAR);
        new ckgz("CarSettingsFeedbackCount", ckgy.CAR);
        new ckhg("CarNavigationOldNavigationStartMethodToNewMethodTimer", ckgy.CAR);
        ap = new ckgz("CarNavRestoreOutcome", ckgy.CAR);
        aq = new ckgz("CarNavRestoreCheckpoint", ckgy.CAR);
        ar = new ckgz("CarMicrophoneAvailability", ckgy.CAR);
        as = new ckgz("CarPreflightWaypointAlertTiming", ckgy.CAR);
        at = new ckgz("CarSearchResultsCount", ckgy.CAR);
        new ckgz("CarAccountParticleSignInResult", ckgy.CAR);
        new ckgz("CarAccountParticleSignOutResult", ckgy.CAR);
        au = new ckgz("CarNavigationEndingScreenType", ckgy.CAR);
        av = new ckgz("CarSearchNoResultsReason", ckgy.CAR);
        aw = new ckhg("CarRecentsNewItemsAutoRefreshTimer", ckgy.CAR);
        ax = new ckhg("CarRecentsItemSelectedTimer", ckgy.CAR);
        ay = new ckha("CarRecentsLastInteractionElapsedTime", ckgy.CAR);
        az = new ckhf("CarActivityCreationToDelayedUiStartTime", ckgy.CAR);
        aA = new ckgz("CarEvInfoCompareResult", ckgy.CAR);
        aB = new ckhf("CarLimitedMapsNonMapHopToNextStart", ckgy.CAR);
        aC = new ckhf("CarLimitedMapsMapTapHopToNextStart", ckgy.CAR);
        aD = new ckgz("CarIntentMultiWaypointDirectionsResult", ckgy.CAR);
        aE = new ckgz("CarSearchDisambiguationCategoryChargingStationsItem", ckgy.CAR);
        aF = new ckgz("CarSearchDisambiguationCategoryItem", ckgy.CAR);
        aG = new ckgz("CarSearchDisambiguationStringItem", ckgy.CAR);
    }
}
