package defpackage;
/* compiled from: PG */
/* renamed from: ckgd  reason: default package */
/* loaded from: classes4.dex */
public final class ckgd {
    public static final ckgz A;
    public static final ckgz B;
    public static final ckhg C;
    public static final ckhg D;
    public static final ckgz E;
    public static final ckgz F;
    public static final ckhg G;
    public static final ckgz H;
    public static final ckha I;
    public static final ckgz J;
    public static final ckgz K;
    public static final ckgz L;
    public static final ckgz M;
    public static final ckha N;
    public static final ckgz O;
    public static final ckgu P;
    public static final ckgz Q;
    public static final ckgu R;
    public static final ckgz S;
    public static final ckgu T;
    public static final ckgz a;
    public static final ckgz b;
    public static final ckgz c;
    public static final ckgz d;
    public static final ckgz e;
    public static final ckgz f;
    public static final ckgz g;
    public static final ckgz h;
    public static final ckgz i;
    public static final ckgz j;
    public static final ckgz k;
    public static final ckgz l;
    public static final ckgz m;
    public static final ckgz n;
    public static final ckgz o;
    public static final ckgz p;
    public static final ckgz q;
    public static final ckgz r;
    public static final ckgz s;
    public static final ckgz t;
    public static final ckgz u;
    public static final ckgz v;
    public static final ckgz w;
    public static final ckhg x;
    public static final ckgz y;
    public static final ckgz z;

    static {
        new ckgz("LocationSharingJourneyShareNumPeople", ckgy.LOCATION_SHARING);
        new ckgz("LocationSharingLocationShareNumPeople", ckgy.LOCATION_SHARING);
        a = new ckgz("LocationSharingLocationShareSmsIntentResult", ckgy.LOCATION_SHARING);
        b = new ckgz("LocationSharingLocationShareSmsSendResult", ckgy.LOCATION_SHARING);
        new ckgz("LocationSharingLocationShareBurstRequestResult", ckgy.LOCATION_SHARING);
        c = new ckgz("LocationSharingLocationShareForegroundBurstRequestResult", ckgy.LOCATION_SHARING);
        d = new ckgz("LocationSharingOvenfreshLocationReportingState", ckgy.LOCATION_SHARING);
        e = new ckgz("LocationSharingStartupLocationReportingState", ckgy.LOCATION_SHARING);
        f = new ckgz("LocationSharingLocationUploadOnceJustification", ckgy.LOCATION_SHARING);
        g = new ckgz("LocationSharingLocationUploadOngoingJustification", ckgy.LOCATION_SHARING);
        h = new ckgz("LocationSharingLocationSharePollReason", ckgy.LOCATION_SHARING);
        i = new ckgz("LocationSharingLocationSharePollingThrottlerResult", ckgy.LOCATION_SHARING);
        new ckgu("LocationSharingHorizontalPageSwipeCompletedCount", ckgy.LOCATION_SHARING);
        j = new ckgz("LocationSharingNotificationImpression", ckgy.LOCATION_SHARING);
        new ckgz("LocationSharingUlrExpectedOptInStatusWhenOnboardingNewUser", ckgy.LOCATION_SHARING);
        k = new ckgz("AndroidOvenfreshStartCount", ckgy.LOCATION_SHARING);
        l = new ckgz("AndroidOvenfreshEndCount", ckgy.LOCATION_SHARING);
        m = new ckgz("AndroidOvenfreshTimeTillAccountAcquired", ckgy.LOCATION_SHARING);
        n = new ckgz("AndroidOvenfreshTimeTillServiceStarted", ckgy.LOCATION_SHARING);
        o = new ckgz("AndroidOvenfreshTimeTillUlrOngoingBurstRequestSent", ckgy.LOCATION_SHARING);
        p = new ckgz("AndroidOvenfreshTimeTillUlrOngoingBurstResponseReceived", ckgy.LOCATION_SHARING);
        q = new ckgz("AndroidOvenfreshTimeTillFirstLocationCollected", ckgy.LOCATION_SHARING);
        r = new ckgz("AndroidOvenfreshTimeTillLastLocationCollected", ckgy.LOCATION_SHARING);
        s = new ckgz("AndroidOvenfreshTimeTillFirstUlrBurstRequestSent", ckgy.LOCATION_SHARING);
        t = new ckgz("AndroidOvenfreshTimeTillLastUlrBurstResponseReceived", ckgy.LOCATION_SHARING);
        u = new ckgz("AndroidOvenfreshTimeWithServiceRunning", ckgy.LOCATION_SHARING);
        v = new ckgz("AndroidOvenfreshCreateServiceCount", ckgy.LOCATION_SHARING);
        w = new ckgz("LocationSharingLsvUploadBecomePrimaryOutcomeCount", ckgy.LOCATION_SHARING);
        x = new ckhg("LocationSharingIpcAuthorizationTime", ckgy.LOCATION_SHARING);
        y = new ckgz("LocationSharingIpcAuthorizedRequestCount", ckgy.LOCATION_SHARING);
        z = new ckgz("LocationSharingIpcBecomePrimaryUiFailureCount", ckgy.LOCATION_SHARING);
        A = new ckgz("LocationSharingIpcEnableReportingFinishUiCount", ckgy.LOCATION_SHARING);
        B = new ckgz("LocationSharingIpcEnableReportingStartUiCount", ckgy.LOCATION_SHARING);
        C = new ckhg("LocationSharingIpcEnableReportingTime", ckgy.LOCATION_SHARING);
        D = new ckhg("LocationSharingIpcIsReportingTime", ckgy.LOCATION_SHARING);
        E = new ckgz("LocationSharingIpcPrepareForShareCreationFinishUiCount", ckgy.LOCATION_SHARING);
        F = new ckgz("LocationSharingIpcPrepareForShareCreationStartUiCount", ckgy.LOCATION_SHARING);
        G = new ckhg("LocationSharingIpcPrepareForShareCreationTime", ckgy.LOCATION_SHARING);
        H = new ckgz("LocationSharingIpcUnauthorizedRequestCount", ckgy.LOCATION_SHARING);
        I = new ckha("LocationSharingBackgroundCollectionAgeOfNewestLocation", ckgy.LOCATION_SHARING);
        J = new ckgz("LocationSharingBackgroundCollectionAccuracyOfNewestLocation", ckgy.LOCATION_SHARING);
        K = new ckgz("LocationSharingBackgroundCollectionNumberOfQualityLocations", ckgy.LOCATION_SHARING);
        L = new ckgz("LocationSharingBackgroundCollectionNumberOfLocations", ckgy.LOCATION_SHARING);
        M = new ckgz("LocationSharingCollectionFailureNumberOfLocationsCollected", ckgy.LOCATION_SHARING);
        N = new ckha("LocationSharingCollectionAgeOfLowQualityLocation", ckgy.LOCATION_SHARING);
        O = new ckgz("LocationSharingCollectionAccuracyOfLowQualityLocation", ckgy.LOCATION_SHARING);
        P = new ckgu("LocationSharingLocationUploaderNumberOfLocations", ckgy.LOCATION_SHARING);
        Q = new ckgz("LocationSharingLocationUploaderNumberOfLocationsInUpload", ckgy.LOCATION_SHARING);
        R = new ckgu("LocationSharingLocationUploaderNumberOfLocationsCleanedAfterSuccessfulUpload", ckgy.LOCATION_SHARING);
        S = new ckgz("LocationSharingLocationUploaderNumberOfLocationsLeftAfterFailedUpload", ckgy.LOCATION_SHARING);
        T = new ckgu("LocationSharingLocationUploaderNumberOfLocationsFilteredDueToOldAge", ckgy.LOCATION_SHARING);
    }
}
