package defpackage;
/* compiled from: PG */
/* renamed from: cqdv  reason: default package */
/* loaded from: classes5.dex */
final class cqdv {
    static final dcco<dgyd, dgxs> a;

    static {
        dccm dccmVar = new dccm();
        dccmVar.d(dgyd.DEMO_APP, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_LOHIBOSHE_DEMO);
        dccmVar.d(dgyd.PLAY_MUSIC_ON_APP_START, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_PLAY_MUSIC_ON_APP_START);
        dccmVar.d(dgyd.PLAY_MUSIC_ON_SETTINGS, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_PLAY_MUSIC_ON_SETTINGS);
        dccmVar.d(dgyd.GPAY_APP_NOTIFICATION_SETTINGS, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_GPAY_APP_NOTIFICATION_SETTINGS);
        dccmVar.d(dgyd.PHOTOS_ASSISTANT_CARD, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_PHOTOS_ASSISTANT_CARD);
        dccmVar.d(dgyd.SAFETYHUB_SHARING_ONBOARDING, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_SAFETYHUB_SHARING_ONBOARDING);
        dccmVar.d(dgyd.OPINION_REWARDS_ON_APP_START, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_OPINION_REWARDS_ON_APP_START);
        dccmVar.d(dgyd.OPINION_REWARDS_CARD, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_OPINION_REWARDS_CARD);
        dccmVar.d(dgyd.OPINION_REWARDS_ON_CONSENT_CHECK, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_OPINION_REWARDS_ON_CONSENT_CHECK);
        dccmVar.d(dgyd.YOUTUBE_MUSIC_HOME_DIRECT_ASK, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_YOUTUBE_MUSIC_HOME_LH_DIRECT_ASK);
        dccmVar.d(dgyd.YOUTUBE_MUSIC_HOME_PROMO, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_YOUTUBE_MUSIC_HOME_LH_PROMO);
        dccmVar.d(dgyd.MAPS_TIMELINE_ONBOARDING, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_MAPS_TIMELINE_ONBOARDING);
        dccmVar.d(dgyd.MAPS_CREATOR_ZONE, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_MAPS_CREATOR_ZONE);
        dccmVar.d(dgyd.MAPS_HOME_SCREEN_CONTRIBUTE_TAB, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_MAPS_HOME_SCREEN_CONTRIBUTE_TAB);
        dccmVar.d(dgyd.MAPS_PERSONAL_SCORE_SETUP, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_MAPS_PERSONAL_SCORE_SETUP);
        dccmVar.d(dgyd.MAPS_YOUR_PLACES_VISITIED, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_MAPS_YOUR_PLACES_VISITED);
        dccmVar.d(dgyd.MAPS_ULR_OOB_TUTORIAL, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_MAPS_ULR_OOB_TUTORIAL);
        dccmVar.d(dgyd.MAPS_LH_PROMO1350786, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_MAPS_LH_PROMO1350786);
        dccmVar.d(dgyd.MAPS_COMMUTE_SETUP, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_MAPS_COMMUTE_SETUP);
        dccmVar.d(dgyd.MAPS_FALLBACK_FLOW, dgxs.MOBILE_CONSENT_FLOWS_ANDROID_MAPS_CATCH_ALL);
        a = dccmVar.b();
    }
}
