package defpackage;
/* compiled from: PG */
/* renamed from: dmnl  reason: default package */
/* loaded from: classes.dex */
public final class dmnl {
    public static final dsqv<dmmu, dmol> a = dsqw.newSingularGeneratedExtension(dmmu.l, dmol.n, dmol.n, null, 53863091, dsur.MESSAGE, dmol.class);
    public static final dsqv<dmmu, dmjg> b = dsqw.newSingularGeneratedExtension(dmmu.l, dmjg.g, dmjg.g, null, 32819068, dsur.MESSAGE, dmjg.class);
    public static final dsqv<dmmu, dmjo> c = dsqw.newSingularGeneratedExtension(dmmu.l, dmjo.b, dmjo.b, null, 42466818, dsur.MESSAGE, dmjo.class);
    public static final dsqv<dmmu, dmji> d = dsqw.newSingularGeneratedExtension(dmmu.l, dmji.a, dmji.a, null, 52617685, dsur.MESSAGE, dmji.class);
    public static final dsqv<dmmu, Boolean> e = dsqw.newSingularGeneratedExtension(dmmu.l, false, null, null, 69077470, dsur.BOOL, Boolean.class);
    public static final dsqv<dmmu, dnbc> f = dsqw.newSingularGeneratedExtension(dmmu.l, dnbc.c, dnbc.c, null, 40154408, dsur.MESSAGE, dnbc.class);
    public static final dsqv<dmmu, dnay> g = dsqw.newSingularGeneratedExtension(dmmu.l, dnay.c, dnay.c, null, 30096869, dsur.MESSAGE, dnay.class);
    public static final dsqv<dmmu, dmwe> h = dsqw.newSingularGeneratedExtension(dmmu.l, dmwe.TYPE_ALL, null, dmwe.S, 116878127, dsur.ENUM, dmwe.class);
    public static final dsqv<dmmu, dfwv> i = dsqw.newSingularGeneratedExtension(dmmu.l, dfwv.e, dfwv.e, null, 51650189, dsur.MESSAGE, dfwv.class);
    public static final dsqv<dmmu, dmsf> j = dsqw.newSingularGeneratedExtension(dmmu.l, dmsf.a, dmsf.a, null, 177034656, dsur.MESSAGE, dmsf.class);
    public static final dsqv<dmmu, dmsb> k = dsqw.newSingularGeneratedExtension(dmmu.l, dmsb.a, dmsb.a, null, 216564156, dsur.MESSAGE, dmsb.class);
    public static final dsqv<dmqg, dnbp> l = dsqw.newSingularGeneratedExtension(dmqg.p, dnbp.a, dnbp.a, null, 28517612, dsur.MESSAGE, dnbp.class);
    public static final dsqv<dmqg, dnau> m = dsqw.newSingularGeneratedExtension(dmqg.p, dnau.a, dnau.a, null, 48343962, dsur.MESSAGE, dnau.class);
    public static final dsqv<dmqg, dnbn> n = dsqw.newSingularGeneratedExtension(dmqg.p, dnbn.a, dnbn.a, null, 49095464, dsur.MESSAGE, dnbn.class);
    public static final dsqv<dmqg, dnay> o = dsqw.newSingularGeneratedExtension(dmqg.p, dnay.c, dnay.c, null, 30096869, dsur.MESSAGE, dnay.class);
    public static final dsqv<dmqg, dnbe> p = dsqw.newSingularGeneratedExtension(dmqg.p, dnbe.a, dnbe.a, null, 132080860, dsur.MESSAGE, dnbe.class);
    public static final dsqv<dmqg, dfwv> q = dsqw.newSingularGeneratedExtension(dmqg.p, dfwv.e, dfwv.e, null, 51650189, dsur.MESSAGE, dfwv.class);
    public static final dsqv<dmqg, dmnv> r = dsqw.newSingularGeneratedExtension(dmqg.p, dmnv.a, dmnv.a, null, 49156371, dsur.MESSAGE, dmnv.class);
    public static final dsqv<dmqg, dmwe> s = dsqw.newSingularGeneratedExtension(dmqg.p, dmwe.TYPE_ALL, null, dmwe.S, 116878127, dsur.ENUM, dmwe.class);
    public static final dsqv<dmqg, dmol> t = dsqw.newSingularGeneratedExtension(dmqg.p, dmol.n, dmol.n, null, 53863091, dsur.MESSAGE, dmol.class);
    public static final dsqv<dmqg, dmsb> u = dsqw.newSingularGeneratedExtension(dmqg.p, dmsb.a, dmsb.a, null, 216564156, dsur.MESSAGE, dmsb.class);
    public static final dsqv<dmpn, dnbt> v = dsqw.newSingularGeneratedExtension(dmpn.r, dnbt.a, dnbt.a, null, 30929027, dsur.MESSAGE, dnbt.class);
    public static final dsqv<dmpn, dnan> w = dsqw.newSingularGeneratedExtension(dmpn.r, dnan.a, dnan.a, null, 66786615, dsur.MESSAGE, dnan.class);
    public static final dsqv<dmpn, dnbp> x = dsqw.newSingularGeneratedExtension(dmpn.r, dnbp.a, dnbp.a, null, 28517612, dsur.MESSAGE, dnbp.class);
    public static final dsqv<dmpn, dnbv> y = dsqw.newSingularGeneratedExtension(dmpn.r, dnbv.c, dnbv.c, null, 30511227, dsur.MESSAGE, dnbv.class);
    public static final dsqv<dmpn, dnay> z = dsqw.newSingularGeneratedExtension(dmpn.r, dnay.c, dnay.c, null, 30096869, dsur.MESSAGE, dnay.class);
    public static final dsqv<dmpn, dnba> A = dsqw.newSingularGeneratedExtension(dmpn.r, dnba.a, dnba.a, null, 172661375, dsur.MESSAGE, dnba.class);
    public static final dsqv<dmpn, dnbl> B = dsqw.newSingularGeneratedExtension(dmpn.r, dnbl.c, dnbl.c, null, 33356690, dsur.MESSAGE, dnbl.class);
    public static final dsqv<dmpn, dnbr> C = dsqw.newSingularGeneratedExtension(dmpn.r, dnbr.a, dnbr.a, null, 40251317, dsur.MESSAGE, dnbr.class);
    public static final dsqv<dmpn, dtym> D = dsqw.newSingularGeneratedExtension(dmpn.r, dtym.f, dtym.f, null, 43229016, dsur.MESSAGE, dtym.class);
    public static final dsqv<dmpn, dfwv> E = dsqw.newSingularGeneratedExtension(dmpn.r, dfwv.e, dfwv.e, null, 51650189, dsur.MESSAGE, dfwv.class);
    public static final dsqv<dmpn, dnbc> F = dsqw.newSingularGeneratedExtension(dmpn.r, dnbc.c, dnbc.c, null, 40154408, dsur.MESSAGE, dnbc.class);
    public static final dsqv<dmpn, dmlm> G = dsqw.newSingularGeneratedExtension(dmpn.r, dmlm.g, dmlm.g, null, 60681369, dsur.MESSAGE, dmlm.class);
    public static final dsqv<dmpn, dmrh> H = dsqw.newSingularGeneratedExtension(dmpn.r, dmrh.f, dmrh.f, null, 135491995, dsur.MESSAGE, dmrh.class);
    public static final dsqv<dmpn, dmqq> I = dsqw.newSingularGeneratedExtension(dmpn.r, dmqq.d, dmqq.d, null, 137907910, dsur.MESSAGE, dmqq.class);
    public static final dsqv<dmpn, dmng> J = dsqw.newSingularGeneratedExtension(dmpn.r, dmng.e, dmng.e, null, 253079038, dsur.MESSAGE, dmng.class);
    public static final dsqv<dmpn, dmqs> K = dsqw.newSingularGeneratedExtension(dmpn.r, dmqs.a, dmqs.a, null, 140063746, dsur.MESSAGE, dmqs.class);
    public static final dsqv<dmpn, dmol> L = dsqw.newSingularGeneratedExtension(dmpn.r, dmol.n, dmol.n, null, 53863091, dsur.MESSAGE, dmol.class);
    public static final dsqv<dmpn, dmjo> M = dsqw.newSingularGeneratedExtension(dmpn.r, dmjo.b, dmjo.b, null, 42466818, dsur.MESSAGE, dmjo.class);
    public static final dsqv<dmpn, dmsh> N = dsqw.newSingularGeneratedExtension(dmpn.r, dmsh.a, dmsh.a, null, 145321205, dsur.MESSAGE, dmsh.class);
    public static final dsqv<dmpn, dmnx> O = dsqw.newSingularGeneratedExtension(dmpn.r, dmnx.a, dmnx.a, null, 252725312, dsur.MESSAGE, dmnx.class);
    public static final dsqv<dmpn, dmwe> P = dsqw.newSingularGeneratedExtension(dmpn.r, dmwe.TYPE_ALL, null, dmwe.S, 116878127, dsur.ENUM, dmwe.class);
    public static final dsqv<dmpn, dmox> Q = dsqw.newSingularGeneratedExtension(dmpn.r, dmox.a, dmox.a, null, 190976051, dsur.MESSAGE, dmox.class);
    public static final dsqv<dmpn, dmpb> R = dsqw.newSingularGeneratedExtension(dmpn.r, dmpb.b, dmpb.b, null, 282806283, dsur.MESSAGE, dmpb.class);
    public static final dsqv<dmpn, dmly> S = dsqw.newSingularGeneratedExtension(dmpn.r, dmly.b, dmly.b, null, 212656839, dsur.MESSAGE, dmly.class);
    public static final dsqv<dmpn, dmsb> T = dsqw.newSingularGeneratedExtension(dmpn.r, dmsb.a, dmsb.a, null, 216564156, dsur.MESSAGE, dmsb.class);
    public static final dsqv<dmpn, dmmq> U = dsqw.newSingularGeneratedExtension(dmpn.r, dmmq.a, dmmq.a, null, 324957562, dsur.MESSAGE, dmmq.class);
    public static final dsqv<dmtc, dmol> V = dsqw.newSingularGeneratedExtension(dmtc.h, dmol.n, dmol.n, null, 53863091, dsur.MESSAGE, dmol.class);
    public static final dsqv<dmtc, Boolean> W = dsqw.newSingularGeneratedExtension(dmtc.h, false, null, null, 36512758, dsur.BOOL, Boolean.class);
    public static final dsqv<dmtc, dmjg> X = dsqw.newSingularGeneratedExtension(dmtc.h, dmjg.g, dmjg.g, null, 85448653, dsur.MESSAGE, dmjg.class);
    public static final dsqv<dmtc, dmwe> Y = dsqw.newSingularGeneratedExtension(dmtc.h, dmwe.TYPE_ALL, null, dmwe.S, 116878127, dsur.ENUM, dmwe.class);
    public static final dsqv<dmtc, dmsb> Z = dsqw.newSingularGeneratedExtension(dmtc.h, dmsb.a, dmsb.a, null, 216564156, dsur.MESSAGE, dmsb.class);
    public static final dsqv<dmmq, dfvs> aa = dsqw.newSingularGeneratedExtension(dmmq.a, dfvs.a, dfvs.a, null, 1000, dsur.MESSAGE, dfvs.class);

    public static void a(dsqa dsqaVar) {
        dsqaVar.e(a);
        dsqaVar.e(b);
        dsqaVar.e(c);
        dsqaVar.e(d);
        dsqaVar.e(e);
        dsqaVar.e(f);
        dsqaVar.e(g);
        dsqaVar.e(h);
        dsqaVar.e(i);
        dsqaVar.e(j);
        dsqaVar.e(k);
        dsqaVar.e(l);
        dsqaVar.e(m);
        dsqaVar.e(n);
        dsqaVar.e(o);
        dsqaVar.e(p);
        dsqaVar.e(q);
        dsqaVar.e(r);
        dsqaVar.e(s);
        dsqaVar.e(t);
        dsqaVar.e(u);
        dsqaVar.e(v);
        dsqaVar.e(w);
        dsqaVar.e(x);
        dsqaVar.e(y);
        dsqaVar.e(z);
        dsqaVar.e(A);
        dsqaVar.e(B);
        dsqaVar.e(C);
        dsqaVar.e(D);
        dsqaVar.e(E);
        dsqaVar.e(F);
        dsqaVar.e(G);
        dsqaVar.e(H);
        dsqaVar.e(I);
        dsqaVar.e(J);
        dsqaVar.e(K);
        dsqaVar.e(L);
        dsqaVar.e(M);
        dsqaVar.e(N);
        dsqaVar.e(O);
        dsqaVar.e(P);
        dsqaVar.e(Q);
        dsqaVar.e(R);
        dsqaVar.e(S);
        dsqaVar.e(T);
        dsqaVar.e(U);
        dsqaVar.e(V);
        dsqaVar.e(W);
        dsqaVar.e(X);
        dsqaVar.e(Y);
        dsqaVar.e(Z);
        dsqaVar.e(aa);
    }
}
