package defpackage;
/* compiled from: PG */
/* renamed from: dr  reason: default package */
/* loaded from: classes6.dex */
public final class dr {
    public int b;
    public int c;
    int d;
    public boolean a = false;
    public int e = -1;
    public int f = -1;
    public float g = -1.0f;
    public int h = -1;
    public int i = -1;
    public int j = -1;
    public int k = -1;
    public int l = -1;
    public int m = -1;
    public int n = -1;
    public int o = -1;
    public int p = -1;
    public int q = -1;
    public int r = -1;
    public int s = -1;
    public int t = -1;
    public float u = 0.5f;
    public float v = 0.5f;
    public String w = null;
    public int x = -1;
    public int y = -1;
    public int z = -1;
    public int A = -1;
    public int B = -1;
    public int C = -1;
    public int D = -1;
    public int E = -1;
    public int F = -1;
    public int G = 0;
    public int H = -1;
    public int I = -1;
    public int J = -1;
    public int K = -1;
    public int L = -1;
    public int M = -1;
    public float N = 0.0f;
    public float O = 0.0f;
    public int P = 0;
    public int Q = 0;
    public float R = 1.0f;
    public boolean S = false;
    public float T = 0.0f;
    public float U = 0.0f;
    public float V = 0.0f;
    public float W = 1.0f;
    public float X = 1.0f;
    public float Y = 0.0f;
    public float Z = 0.0f;
    public float aa = 0.0f;
    public float ab = 0.0f;
    public float ac = 0.0f;
    public int ad = -1;
    public int ae = -1;
    public int af = -1;
    public int ag = -1;
    public int ah = -1;
    public int ai = -1;

    /* renamed from: a */
    public final dr clone() {
        dr drVar = new dr();
        drVar.a = this.a;
        drVar.b = this.b;
        drVar.c = this.c;
        drVar.e = this.e;
        drVar.f = this.f;
        drVar.g = this.g;
        drVar.h = this.h;
        drVar.i = this.i;
        drVar.j = this.j;
        drVar.k = this.k;
        drVar.l = this.l;
        drVar.m = this.m;
        drVar.n = this.n;
        drVar.o = this.o;
        drVar.p = this.p;
        drVar.q = this.q;
        drVar.r = this.r;
        drVar.s = this.s;
        drVar.t = this.t;
        drVar.u = this.u;
        drVar.v = this.v;
        drVar.w = this.w;
        drVar.x = this.x;
        drVar.y = this.y;
        drVar.u = this.u;
        drVar.u = this.u;
        drVar.u = this.u;
        drVar.u = this.u;
        drVar.u = this.u;
        drVar.z = this.z;
        drVar.A = this.A;
        drVar.B = this.B;
        drVar.C = this.C;
        drVar.D = this.D;
        drVar.E = this.E;
        drVar.F = this.F;
        drVar.G = this.G;
        drVar.H = this.H;
        drVar.I = this.I;
        drVar.J = this.J;
        drVar.K = this.K;
        drVar.L = this.L;
        drVar.M = this.M;
        drVar.N = this.N;
        drVar.O = this.O;
        drVar.P = this.P;
        drVar.Q = this.Q;
        drVar.R = this.R;
        drVar.S = this.S;
        drVar.T = this.T;
        drVar.U = this.U;
        drVar.V = this.V;
        drVar.W = this.W;
        drVar.X = this.X;
        drVar.Y = this.Y;
        drVar.Z = this.Z;
        drVar.aa = this.aa;
        drVar.ab = this.ab;
        drVar.ac = this.ac;
        drVar.ad = this.ad;
        drVar.ae = this.ae;
        drVar.af = this.af;
        drVar.ag = this.ag;
        drVar.ah = this.ah;
        drVar.ai = this.ai;
        return drVar;
    }

    public final void b(dq dqVar) {
        dqVar.d = this.h;
        dqVar.e = this.i;
        dqVar.f = this.j;
        dqVar.g = this.k;
        dqVar.h = this.l;
        dqVar.i = this.m;
        dqVar.j = this.n;
        dqVar.k = this.o;
        dqVar.l = this.p;
        dqVar.m = this.q;
        dqVar.n = this.r;
        dqVar.o = this.s;
        dqVar.p = this.t;
        dqVar.leftMargin = this.A;
        dqVar.rightMargin = this.B;
        dqVar.topMargin = this.C;
        dqVar.bottomMargin = this.D;
        dqVar.u = this.M;
        dqVar.v = this.L;
        dqVar.w = this.u;
        dqVar.x = this.v;
        dqVar.y = this.w;
        dqVar.J = this.x;
        dqVar.K = this.y;
        dqVar.A = this.N;
        dqVar.z = this.O;
        dqVar.C = this.Q;
        dqVar.B = this.P;
        dqVar.D = this.ad;
        dqVar.E = this.ae;
        dqVar.H = this.af;
        dqVar.I = this.ag;
        dqVar.F = this.ah;
        dqVar.G = this.ai;
        dqVar.L = this.z;
        dqVar.c = this.g;
        dqVar.a = this.e;
        dqVar.b = this.f;
        dqVar.width = this.b;
        dqVar.height = this.c;
        dqVar.setMarginStart(this.F);
        dqVar.setMarginEnd(this.E);
        dqVar.a();
    }
}
