package defpackage;
/* compiled from: PG */
/* renamed from: dtxz  reason: default package */
/* loaded from: classes.dex */
public final class dtxz {
    public static final ddho A;
    public static final ddho B;
    public static final ddho C;
    public static final ddho D;
    public static final ddho E;
    public static final ddho F;
    public static final ddho G;
    public static final ddho H;
    public static final ddho I;
    public static final ddho J;
    public static final ddho K;
    public static final ddho a;
    public static final ddho b;
    public static final ddho c;
    public static final ddho d;
    public static final ddho e;
    public static final ddho f;
    public static final ddho g;
    public static final ddho h;
    public static final ddho i;
    public static final ddho j;
    public static final ddho k;
    public static final ddho l;
    public static final ddho m;
    public static final ddho n;
    public static final ddho o;
    public static final ddho p;
    public static final ddho q;
    public static final ddho r;
    public static final ddho s;
    public static final ddho t;
    public static final ddho u;
    public static final ddho v;
    public static final ddho w;
    public static final ddho x;
    public static final ddho y;
    public static final ddho z;

    static {
        new dtxi(10197);
        a = new dtxi(10532);
        b = new dtxi(10531);
        c = new dtxi(11293);
        d = new dtxi(10278);
        e = new dtxi(10434);
        f = new dtxi(12479);
        g = new dtxi(12481);
        h = new dtxi(11276);
        i = new dtxi(25357);
        j = new dtxi(30125);
        k = new dtxi(32270);
        l = new dtxi(17171);
        m = new dtxi(17172);
        n = new dtxi(17173);
        o = new dtxi(17174);
        p = new dtxi(30940);
        q = new dtxi(30941);
        r = new dtxi(30942);
        s = new dtxi(9357);
        t = new dtxi(9358);
        u = new dtxi(36306);
        v = new dtxi(12962);
        w = new dtxi(17976);
        new dtxi(19954);
        x = new dtxi(38471);
        y = new dtxi(38470);
        z = new dtxi(38469);
        A = new dtxi(11278);
        B = new dtxi(11280);
        new dtxi(11279);
        C = new dtxi(12017);
        D = new dtxi(12013);
        new dtxi(11316);
        new dtxi(11315);
        new dtxi(11277);
        E = new dtxi(20868);
        F = new dtxi(17343);
        new dtxi(9474);
        new dtxi(9473);
        new dtxi(9359);
        G = new dtxi(10707);
        H = new dtxi(36008);
        new dtxi(10927);
        I = new dtxi(9790);
        J = new dtxi(11565);
        K = new dtxi(11566);
        new dtxi(8723);
        new dtxi(7834);
    }
}
