package defpackage;

import com.google.android.filament.R;
/* compiled from: PG */
/* renamed from: nqo  reason: default package */
/* loaded from: classes7.dex */
public final class nqo {
    public static final cqrp A;
    public static final cqrp B;
    public static final cqrp C;
    public static final cqrp D;
    public static final cqrp E;
    public static final cqrp F;
    public static final cqrp G;
    public static final cqtv H;
    public static final cqtv I;
    public static final cqtv J;
    public static final cqtv K;
    public static final cqtv L;
    public static final cqrp M;
    public static final cqtv N;
    public static final cqtv O;
    public static final cqrp P;
    public static final cqrp Q;
    public static final cqrp R;
    public static final cqrp S;
    public static final cqrp T;
    public static final cqrp U;
    public static final cqrp V;
    public static final cqtv W;
    public static final cqtv X;
    @Deprecated
    public static final cqrp Y;
    public static final cqrp Z;
    @Deprecated
    public static final cqrp a;
    public static final cqtv aA;
    public static final cqtv aB;
    public static final cqtv aC;
    public static final cqtv aD;
    public static final cqtv aE;
    public static final cqtv aF;
    public static final cqtv aG;
    public static final cqtv aH;
    public static final cqrp aI;
    public static final cqrp aJ;
    public static final cqrp aK;
    public static final cqrp aL;
    public static final cqrp aM;
    public static final cqrp aN;
    public static final cqrp aO;
    public static final cqrp aP;
    public static final cqrp aQ;
    public static final cqtv aR;
    public static final cqtv aS;
    public static final cqrp aa;
    public static final cqrp ab;
    public static final cqrp ac;
    public static final cqrp ad;
    public static final cqrp ae;
    public static final cqrp af;
    public static final cqrp ag;
    public static final cqrp ah;
    public static final cqrp ai;
    public static final cqrp aj;
    public static final cqrp ak;
    public static final cqtv al;
    public static final cqtv am;
    public static final cqtv an;
    public static final cqtv ao;
    public static final cqtv ap;
    public static final cqtv aq;
    public static final cqrp ar;
    public static final cqtv as;
    public static final cqtv at;
    public static final cqtv au;
    public static final cqrp av;
    public static final cqrp aw;
    public static final cqrp ax;
    public static final cqrp ay;
    public static final cqrp az;
    @Deprecated
    public static final cqrp b;
    @Deprecated
    public static final cqrp c;
    @Deprecated
    public static final cqrp d;
    public static final cqrp e;
    public static final cqrp f;
    public static final cqrp g;
    public static final cqrp h;
    public static final cqrp i;
    public static final cqrp j;
    public static final cqrp k;
    public static final cqrp l;
    public static final cqrp m;
    public static final cqrp n;
    public static final cqrp o;
    public static final cqrp p;
    public static final cqrp q;
    public static final cqrp r;
    public static final cqrp s;
    public static final cqrp t;
    public static final cqtv u;
    public static final cqrp v;
    public static final cqrp w;
    public static final cqrp x;
    public static final cqrp y;
    public static final cqrp z;

    static {
        cqrp.d(80.0d);
        cqrp.d(48.0d);
        a = cqrp.d(32.0d);
        b = cqrp.d(28.0d);
        c = cqrp.d(26.0d);
        cqrp.d(22.0d);
        d = cqrp.d(25.0d);
        e = cqrp.d(44.0d);
        f = cqrp.d(dcyn.a);
        cqrp.d(36.0d);
        cqrp.d(dcyn.a);
        g = cqrp.d(32.0d);
        h = cqrp.d(dcyn.a);
        i = cqrp.d(28.0d);
        cqrp.d(1.100000023841858d);
        j = cqrp.d(26.0d);
        k = cqrp.d(1.7899999618530273d);
        l = cqrp.d(24.0d);
        cqrp.d(1.7899999618530273d);
        m = cqrp.d(26.0d);
        n = cqrp.d(1.7899999618530273d);
        o = cqrp.d(26.0d);
        p = cqrp.d(3.799999952316284d);
        q = cqrp.d(24.0d);
        r = cqrp.d(3.809999942779541d);
        s = cqrp.d(26.0d);
        t = cqrp.d(1.7899999618530273d);
        cqrp.d(16.0d);
        new nsg(nsf.WIDTH_CONSTRAINED, cqrp.d(14.0d), 800).g(cqrp.d(18.0d), 1024);
        u = cqrp.d(176.0d);
        v = cqrp.d(36.0d);
        w = cqrp.d(36.0d);
        x = cqrp.d(48.0d);
        y = cqrp.d(48.0d);
        cqrp.d(40.0d);
        cqrp.d(40.0d);
        z = cqrp.d(28.0d);
        A = cqrp.d(28.0d);
        cqrp.d(8.0d);
        B = cqrp.d(96.0d);
        C = cqrp.d(96.0d);
        D = cqrp.d(24.0d);
        E = cqrp.d(24.0d);
        F = cqrp.d(24.0d);
        G = cqrp.d(36.0d);
        cqrp.d(18.0d);
        cqrp.d(76.0d);
        H = cqrp.d(76.0d);
        I = cqrp.d(180.0d);
        J = cqrp.d(480.0d);
        cqrp d2 = cqrp.d(30.0d);
        K = d2;
        L = cqsg.f(d2, Float.valueOf(2.0f));
        M = cqrp.d(46.0d);
        N = cqrp.d(2.0d);
        O = nsg.f(64, 72);
        cqrp d3 = cqrp.d(16.0d);
        P = d3;
        Q = d3;
        R = cqrp.d(16.0d);
        S = cqrp.d(32.0d);
        T = cqrp.d(12.0d);
        U = cqrp.d(8.0d);
        V = cqrp.d(80.0d);
        W = cqrp.d(16.0d);
        X = cqrp.d(8.0d);
        cqrp.d(16.0d);
        Y = cqrp.d(64.0d);
        Z = cqrp.d(60.0d);
        cqrp.d(36.0d);
        aa = cqrp.d(72.0d);
        cqrp.d(80.0d);
        ab = cqrp.d(20.0d);
        ac = cqrp.d(36.0d);
        ad = cqrp.d(16.0d);
        ae = cqrp.d(8.0d);
        af = cqrp.d(2.0d);
        cqrp.d(88.0d);
        ag = cqrp.d(36.0d);
        cqrp.d(8.0d);
        ah = cqrp.d(28.0d);
        ai = cqrp.d(56.0d);
        aj = cqrp.d(4.0d);
        ak = cqrp.d(6.0d);
        new nsg(nsf.WIDTH_CONSTRAINED, cqrp.d(432.0d), 800).g(cqrp.d(480.0d), 1024);
        nsg nsgVar = new nsg(nsf.WIDTH_CONSTRAINED, cqrp.d(376.0d), 800);
        nsgVar.g(cqrp.d(400.0d), 1024);
        al = nsgVar;
        am = cqrp.d(360.0d);
        an = nsg.c(258, 288);
        cqrp.d(48.0d);
        ao = nsg.f(64, 72);
        nsg.f(74, 82);
        ap = nsg.f(14, 18);
        aq = cqrp.d(104.0d);
        ar = cqrp.d(4.0d);
        cqrp.d(-4.0d);
        nsg nsgVar2 = new nsg(nsf.WIDTH_CONSTRAINED, cqrp.d(352.0d), 800);
        nsgVar2.g(cqrp.d(400.0d), 1024);
        as = nsgVar2;
        at = nsg.f(88, R.styleable.AppCompatTheme_toolbarNavigationButtonStyle);
        au = nsg.f(88, 104);
        av = cqrp.d(26.0d);
        aw = cqrp.d(720.0d);
        cqrp.d(96.0d);
        ax = cqrp.d(1.0d);
        ay = cqrp.d(96.0d);
        az = cqrp.d(96.0d);
        aA = nsgVar;
        nsg nsgVar3 = new nsg(nsf.WIDTH_CONSTRAINED, cqrp.d(336.0d), 800);
        nsgVar3.g(cqrp.d(400.0d), 1024);
        aB = nsgVar3;
        cqrp.d(96.0d);
        new nsg(nsf.WIDTH_CONSTRAINED, cqrp.d(336.0d), 800).g(cqrp.d(400.0d), 1024);
        aC = cqrp.d(670.0d);
        aD = cqrp.d(480.0d);
        cqrp d4 = cqrp.d(64.0d);
        aE = d4;
        cqrp.d(96.0d);
        aF = cqsg.d(d4, d3, d3);
        aG = nsg.d(72, 80, 96);
        aH = cqrp.d(72.0d);
        cqrp.d(6.0d);
        aI = cqrp.d(30.0d);
        aJ = cqrp.d(64.0d);
        aK = cqrp.d(72.0d);
        aL = cqrp.d(80.0d);
        aM = cqrp.d(72.0d);
        aN = cqrp.d(56.0d);
        cqrp.d(50.0d);
        aO = cqrp.d(18.0d);
        aP = cqrp.d(84.0d);
        aQ = cqrp.d(28.0d);
        aR = cqrp.d(88.0d);
        aS = nsg.d(88, 88, R.styleable.AppCompatTheme_windowFixedHeightMajor);
        cqrp.d(302.0d);
    }

    private nqo() {
    }
}
